npm/src/worker-common.ts, npm/test/basics.js
I'm actually planning to delete/rewrite this code in #426 .  But I discovered a bug in error handling while working on that PR, and wanted to be super clear about the current behavior before I merge a huge refactoring change.
=> Fix inconsistent error handling in JavaScript layer

.eslintrc.cjs, npm/src/cancellation.ts, npm/src/compiler.ts, npm/src/log.ts, npm/src/worker-common.ts, package-lock.json, playground/src/main.tsx
Turning off this linter rule. Not very useful in practice and we have a lot of suppression comments for it.
=> Turn off no-explicit-any ESLint rule

library/std/convert.qs, library/tests/src/test_convert.rs
As I was trying to run some of my code I realized `ResultAsBool` and `BoolAsResult` were missing and the code that used to compile with qsharp-compiler does not compile anymore.
I am not sure of what is the process for including functions (whether they were missed or omitted intentionally) but given that they are super simple and that there are already `ResultArrayAsBoolArray` and `BoolArrayAsResultArray` I think it makes sense to have them as they are quite commonly used.
=> added ResultAsBool and BoolAsResult to std

library/std/arrays.qs
Added a fact check for Head/Tail array functions, which improves a bit the feedback.
```
let foo : Int[] = [];
let bar = Head(foo);
```
current error: `ERROR: runtime error: index out of range: 0`
new error: `ERROR: runtime error: program failed: Array must have at least 1 element`
```
let foo : Int[] = [];
let bar = Tail(foo);
```
current error: `ERROR: runtime error: value cannot be used as an index: -1`
new error: `ERROR: runtime error: program failed: Array must have at least 1 element`
---
Regarding for the trailing whitespace changes - VS Code cleaned it up "on its own" due to `"editor.formatOnType": true` setting - but I kept them because they seem anyway to be consistent with the rest of the codebase.
=> added Fact check for Head/Tail

library/std/arrays.qs, library/tests/src/test_arrays.rs
Ported function HeadAndRest and MostAndTail. The following explanation is for HeadAndRest, the other one is similar. 
Although they seem redundant because the following two lines are equivalent:
```
let (h, r) = (Head(a), Rest(a));
let (h, r) = HeadAndRest(a);
```
This doesn't work efficiently where a is computed in the expression. Such as
`let (h, r) = HeadAndRest(a[..2^(n-1)..2^(n+1)];`
In this case separate Head() and Rest() would require lengthier expressions.
Implementation uses library functions Head() and Rest() rather than inline implementation as the function name really calls for them.
=> Added HeadAndRest, MostAndTail

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs
This change updates the way fixed arguments are handled for lambdas to properly interact with controlled invocations, where the argument tuple that must be modified is an inner tuple.
Fixes #459
=> Update fixed argument handling for lambda

npm/src/browser.ts, package-lock.json, package.json, vscode/build.mjs, vscode/package.json, vscode/src/common.ts, vscode/src/compilerWorker.ts, vscode/src/debugger/activate.ts, vscode/src/debugger/output.ts, vscode/src/debugger/session.ts, vscode/src/debugger/types.ts, vscode/src/extension.ts, vscode/tsconfig.json
Set up compiler with minimal end-to-end interface allowing the F5 execution of current Q# file open in editor, no debugging.
This PR uses the deprecated check call as a placeholder. Next PR will sub out the compiler for the debugger, replacing the check call.
=> Adding Q# execution scaffolding

compiler/qsc_passes/src/common.rs, compiler/qsc_passes/src/conjugate_invert.rs, compiler/qsc_passes/src/conjugate_invert/tests.rs, compiler/qsc_passes/src/entry_point.rs, compiler/qsc_passes/src/entry_point/tests.rs, compiler/qsc_passes/src/id_update.rs, compiler/qsc_passes/src/lib.rs, compiler/qsc_passes/src/loop_unification.rs, compiler/qsc_passes/src/loop_unification/tests.rs, compiler/qsc_passes/src/replace_qubit_allocation.rs, compiler/qsc_passes/src/replace_qubit_allocation/tests.rs, compiler/qsc_passes/src/spec_gen.rs, compiler/qsc_passes/src/spec_gen/ctl_gen.rs, compiler/qsc_passes/src/spec_gen/tests.rs
This change updates the transformation passes to include refreshing node ids for cloned blocks as well as reducing use of `NodeId::default()` in the code. As a result, transformed code should now correctly include valid, non-duplicate node ids throughout.
Fixes #453
=> Set `NodeId` during transformation passes

vscode/package.json, vscode/src/debugger/activate.ts
There is a type error on the program causing a hang when executing the `runEditorContents` command. This was missed in an earlier refactor.
=> Removing unused default and fixing Run Q# file menu command

compiler/qsc_passes/src/conjugate_invert/tests.rs, compiler/qsc_passes/src/loop_unification/tests.rs, compiler/qsc_passes/src/replace_qubit_allocation/tests.rs, compiler/qsc_passes/src/spec_gen.rs, compiler/qsc_passes/src/spec_gen/tests.rs
This change fixes a missed case from #471, and adds the validor pass to tests for transformation.
Fixes #496
=> Fix node ids in spec gen

compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/intrinsic/tests.rs, library/std/canon.qs, library/std/random.qs, library/tests/src/tests.rs
Added library functions and basic tests.
Note that DrawRandomDouble documentations calls for inclusive bounds, but the code doesn't include the lower bound as underlying Rust function doesn't seem to allow inclusion of the lower bound. This may be OK because the probability of drawing exact number is very slim when the interval is reasonable.
=> Added ApplyPauliFromInt, ApplyControlledOnInt, DrawRandomDouble

library/std/arrays.qs, library/tests/src/test_arrays.rs
Padded function now allows user to ask for the length that is the same as current array length. This matches functionality of the QDK version.
=> Fixed bug in Padded function

language_service/src/display.rs, language_service/src/hover.rs, language_service/src/hover/tests.rs, language_service/src/test_utils.rs
Display parameter names when hovering over callables.
Preface UDT display with `newtype` to help indicate that it is a UDT.
Put doc strings below other information, as it can get lengthy and we don't want to burry the other info displayed.
=> Improve Hover Display

.github/workflows/fuzz.yml
This updates the Fuzz workflow conditions to include running on merges to main as long as certain conditions are met, namely:
- Any fuzzing infrastructure was changed
- The reporting template was changed
- The workflow itself was changed
- The compiler was changed (excluding the evaluator and codegen)
=> Update Fuzz workflow to run on some merges to main

compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_frontend/src/incremental.rs
This fixes an oversight where the incremental compiler did not include the core library in the set of globals, meaning callables like `Length` were not available. Also adds a test to confirm availability of those callables.
=> Include core package in incremental compilation

library/std/diagnostics.qs
Some diagnostic callables were written as functions when they are not pure functions, so should instead be operations.
=> Change diagnostic callables to operations

compiler/qsc/benches/large.rs, compiler/qsc/src/bin/qsc.rs, compiler/qsc/src/compile.rs, compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateless.rs, compiler/qsc/src/lib.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_passes/src/entry_point.rs, compiler/qsc_passes/src/entry_point/tests.rs, compiler/qsc_passes/src/lib.rs, fuzz/fuzz_targets/compile.rs, language_service/src/qsc_utils.rs, language_service/src/test_utils.rs, wasm/src/lib.rs
This change updates the way entry point attributes and/or expressions are checked to ensure that the error messages get propageted as expected. Recent changes regressed the error cases, and this introduces a new parameter to compile that lets the caller decide whether an entry point attribute or expression should be treated as required. This is essentially the difference between a library compilation (no entry required) and and executable compilation (single entry required), so this code is a placeholder until we formalize the difference between library compilation and exe compilation.
=> Fix entry point error checking

vscode/package.json
Extension wasn't loading when installing locally without `"main"` entry defined.
=> Adding main def in package.json

language_service/src/display.rs, language_service/src/hover.rs, language_service/src/hover/tests.rs, language_service/src/qsc_utils.rs
Adds what namespace a callable is in to the callable's hover info card.
=> Namespace Info on Hover over Callables

compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_data_structures/src/index_map.rs, compiler/qsc_frontend/src/incremental.rs, compiler/qsc_frontend/src/typeck/check.rs, compiler/qsc_frontend/src/typeck/infer.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_passes/src/lib.rs
This change adds the option for an persistent `Inferrer` and `Solution` struct used during type inference, allowing incremental compilation to remember types that are solved for in separate statements.
This fixes #205.
=> Add incremental context for type inference

compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_passes/src/lib.rs
This adds a context for passes that can be persisted in incremental compilation. For now, the only pass with context that must persist is the borrow checker that verifies mutability rules are followed. Future passes can include context in the struct when/if needed.
Fixes #398
=> Add pass context for incremental compilation

language_service/src/completion.rs, language_service/src/completion/tests.rs, playground/src/main.tsx, vscode/src/completion.ts, wasm/src/language_service.rs
Adds the detail field to the completions to display.
=> LS Completions Details

vscode/package.json, vscode/src/common.ts, vscode/src/debugger/activate.ts, vscode/src/debugger/types.ts
In testing the current run/debug experience on github.dev (which uses a virtual file system to the repo), the Play/Debug experience was broken.
This is as the code was trying to pass Uri objects across boundaries, however in getting serialized/deserialized it becomes just a regular object with the same data fields but none of the Uri methods, as shown below. VS Code would see this "Uri-like" object and try and call Uri methods on it (such as .with or .parse) which would then throw (e.g. `path.with is undefined`)
Basically, just pass data values across boundaries, not objects with methods on their prototype chain (which then get lost)
CC @idavis
=> Fix debugging on virtual file systems

compiler/qsc/src/interpret/stateful.rs, compiler/qsc_eval/src/lower.rs, compiler/qsc_fir/src/assigner.rs, compiler/qsc_fir/src/fir.rs, compiler/qsc_fir/src/lib.rs
Adds an assigner for FIR converting the sparse index maps into dense maps. Correctness is verified by the interpreter tests. Any missing entry mapping and the a "stmt/expr/block/pat should have been lowered" error will be emitted.
=> FIR assigner

compiler/qsc/src/interpret.rs, compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/stepping_tests.rs, compiler/qsc_eval/src/debug.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, npm/src/browser.ts, npm/src/debug-service/debug-service.ts, npm/src/debug-service/worker-node.ts, npm/src/debug-service/worker-proxy.ts, npm/src/main.ts, npm/test/basics.js, vscode/src/common.ts, vscode/src/debugger/output.ts, vscode/src/debugger/session.ts, vscode/src/extension.ts, wasm/src/debug_service.rs, wasm/src/lib.rs
Debug stepping ~has introduced enough overhead that it~ may be worthwhile to split eval_continue into two calls. There is a lot going on in the eval for debugging. We will probably want to take a look after scopes support is added. Step granularity on expressions may also introduce noticeable overhead, but that is speculation at the moment.
```
Teleport evaluation     time:   [103.03 µs 103.08 µs 103.14 µs]
change: [+0.3841% +0.6847% +0.9592%] (p = 0.00 < 0.05)
Change within noise threshold.
Deutsch-Jozsa evaluation
time:   [22.510 ms 22.517 ms 22.525 ms]
change: [+0.6672% +0.8058% +0.8961%] (p = 0.00 < 0.05)
Change within noise threshold.
```
=> Add Step Next/In/Out to Debugger

vscode/src/common.ts, vscode/src/debugger/activate.ts, vscode/src/diagnostics.ts, vscode/src/extension.ts, vscode/src/notebook.ts
- For now, exclude notebook cells altogether until we have proper language service support. (`%%qsharp` magic and top-level statements just don't play well with the parser at the moment).
- For stdlib/corelib files, hide diagnostics but allow other language service features.
=> Don't report errors in library files or notebook cells

compiler/qsc/src/interpret/stateful.rs, compiler/qsc_passes/src/common.rs, compiler/qsc_passes/src/conjugate_invert.rs, compiler/qsc_passes/src/conjugate_invert/tests.rs, compiler/qsc_passes/src/invert_block.rs, compiler/qsc_passes/src/loop_unification.rs, compiler/qsc_passes/src/loop_unification/tests.rs, compiler/qsc_passes/src/replace_qubit_allocation.rs, compiler/qsc_passes/src/replace_qubit_allocation/tests.rs, compiler/qsc_passes/src/spec_gen/tests.rs
For passes that create new local bindings added to the code, we use `generated_name` to include an `@` symbol that differentiates them from normal Q# identifiers and lets the debugger successfully ignore them.
=> Use `@` to identify and ignore generated locals

pip/qsharp/__init__.py, pip/qsharp/_qsharp.py, pip/samples/sample.ipynb, pip/tests/test_qsharp.py
A while back during the spec review we decided that `eval()` would be a more user-friendly name (echoing Python's `eval()`).
Dropping the name "interpret" from all user-facing contexts. We continue to use "interpreter" in the implementation though.
=> Rename interpret() to eval() in Python module

katas/content/multi_qubit_systems/examples/MultiQubitSystems.qs, katas/content/multi_qubit_systems/index.md, katas/content/single_qubit_measurements/implementing_measurement/example.qs, npm/test/basics.js
This change adds validation for Q# examples that are part of katas.
=> Test that Q# examples in katas build and run successfully

vscode/src/common.ts, vscode/src/debugger/activate.ts, vscode/src/debugger/session.ts
This is a workaround for windows which doesn't play well with URIs. The DAP `setDebuggerPathFormat`/`convertClientPathToDebugger`/`convertDebuggerPathToClient` can't be used as there is a [bug requiring nodejs](https://github.com/microsoft/vscode-debugadapter-node/issues/298) which prevents usage in web extensions. Once the bug is fixed we can update the debugger to use URIs without this PR's retry conversion.
This PR also fixes an issue where if the user closed the file being debugged or it was open as 'temporarily open' then we couldn't step back into the code.
=> Unify file access in debugger

compiler/qsc/src/interpret/stateful.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_codegen/src/qir_base/prefix.ll, compiler/qsc_codegen/src/qir_base/tests.rs, compiler/qsc_frontend/src/incremental.rs, compiler/qsc_passes/src/baseprofck.rs, pip/qsharp/__init__.py, pip/qsharp/_ipython.py, pip/qsharp/_native.pyi, pip/qsharp/_qsharp.py, pip/samples/azure_submission.ipynb, pip/samples/sample.ipynb, pip/src/interpreter.rs, pip/tests/test_interpreter.py, pip/tests/test_qsharp.py
This adds a `compile` method to the Python `qsharp` module and introduces an `init` pattern to be used when starting up a session. The expected usage is that for full compilation and simulation, `qsharp.init()` or `qsharp.init(target=qsharp.Target.Full)` are called at the outset to configure compilation (NOTE: latest allows the user to skip this and just takes the default on first use). If `qsharp.init(target=qsharp.Target.Base)` is used instead then local simulation will follow the same restrictions as base profile code generation. When in this mode, `qsharp.compile(<expr>)` will produce output that can be used as part of submitting to QIR capable targets.
=> Python `compile` for QIR codegen

playground/public/style.css, playground/src/main.tsx
The Monaco editor makes use of a `header` css class internally for rendering completion item detail panel contents. We had also defined a `header` css class for the page title element, and this was effecting how the Monaco editor rendered the details panel. This PR fixes the issue by renaming our `header` css class to `page-header` to avoid the name collision.
=> Fix Completion Items Display Panel Style

Cargo.toml
This updates the workspace settings for cargo to remove `debug =1` and instead use `strip = true` to reduce binary sizes. Previously, the Linux .so that was part of the Python wheel was ~31 MB while other platforms were in the single digits. After this change, the same .so is only ~3.2 MB. Perf testing showed no change in behavior, so the only trade-off for the binary size is no longer including debug symbols for the release binaries.
=> Use `strip = true` to reduce Linux binary sizes

library/std/arithmetic.qs, library/std/arrays.qs, library/std/canon.qs, library/std/intrinsic.qs, library/std/math.qs, library/std/measurement.qs, library/std/random.qs, pip/pyproject.toml
Limits the use of LaTex syntax to the Remarks second of doc strings in the SDT library files.
=> Removed or Moved LaTex Syntax from STD Doc Strings

compiler/qsc/src/interpret/stateful.rs, compiler/qsc_data_structures/src/span.rs, compiler/qsc_passes/src/replace_qubit_allocation.rs, compiler/qsc_passes/src/replace_qubit_allocation/tests.rs, npm/test/basics.js, package.json, vscode/src/debugger/session.ts
This PR adds
- metadata to the debug breakpoint information stored in the debugger extension.
- enables inline breakpoints and fixes issues with multi-line statements where breakpoints weren't being set correctly.
- breakpoints for if/while loops
- more work needs to be done to support stepping for the conditional checks (while, elif) 
- filters bp requests to ensure we are processing Q# files
- trace instead of error logging when failing to load files. Almost all failures are false positives for cached BPs from previous sessions.
=> Better breakpoint granularity and diagnostic information in debug adapter

Cargo.lock, compiler/qsc/Cargo.toml, compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_frontend/src/incremental.rs
This fixes a missed case after the changes in #628 that meant `compile_expr` could panic if the given expression was a block that included defining new items.
=> Fix panic when QIR entry expr defines items

compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/tests.rs
Missed case in the interpreter. I believe #628 originally intended to address this.
=> Items in a cell should be usable before definition

build.py, pip/test_requirements.txt, pip/tests-qir/test_qir.py, pip/tests-qir/test_requirements.txt, pip/tests/test_qsharp.py
This change adds new test logic to the Python tests to verify output QIR is valid and contains the expected gate sequence.
Fixes #572
=> Use PyQIR to validate base profile output

.devcontainer/devcontainer.json, .github/workflows/ci.yml, .github/workflows/publish-playground.yml, Cargo.toml, compiler/qsc/src/interpret/debug.rs, compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateless.rs, compiler/qsc_ast/src/ast.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_fir/src/ty.rs, compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_frontend/src/error.rs, compiler/qsc_frontend/src/incremental.rs, compiler/qsc_frontend/src/lower.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/typeck/convert.rs, compiler/qsc_frontend/src/typeck/infer.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_hir/src/ty.rs, compiler/qsc_parse/src/expr.rs, compiler/qsc_parse/src/lex/cooked/tests.rs, compiler/qsc_passes/src/lib.rs, compiler/qsc_passes/src/loop_unification.rs, compiler/qsc_passes/src/spec_gen.rs, language_service/src/lib.rs, prereqs.py, wasm/src/lib.rs
This update comes with changes to clippy and rustfmt that can cause validation failures, so the change includes all the updates to source code and configuration to bring the codebase into alignment with the latest Rust lints. Without this, new users who install the latest stable rust would see these failures locally and be blocked from developing.
The prerequisites check is also updated to force everyone to upgrade.
=> Update to Rust 1.72.0

compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_parse/src/item/tests.rs, compiler/qsc_parse/src/prim.rs, compiler/qsc_parse/src/scan.rs
Avoids duplicate EOF errors by ignoring additonal EOFs when recovery has already happened.
Fixes #431
=> Two errors at EOF when parser error recovery occurs

compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/item/tests.rs, compiler/qsc_parse/src/ty.rs
This updates the logic for parsing UDT field definitions to treat any `TyDef` with no named fields as a single field rather than a tuple of fields, and in that case allow that field's type to be an array or arrow type. This ends up being simpler and more consistent, since individual unnamed field entries are not directly addressable. All user-facing functionality thus remains the same: you access unnamed fields by using the unwrap (`!`) unary operator, while named fields are treated as separate entities tht are individually addressable.
Fixes #437
=> Parsing Error with UDTs based on Arrays

compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs
=> Return statements in lambdas are checked against the surrounding scope's expected return type

Cargo.lock, Cargo.toml
This updates the rust dependencies for criterion and pyo3 to the latest versions. Notably, newer versions of criterion do not depend on atty, which was the source of a component governance warning. Also, the dependency on the indenter crate was left as-is since newer versions change the API in a way that will require some refactoring and is better left for a follow up PR.
=> Update Rust dependencies for component governance

.github/workflows/ci.yml
Problem: 
The MacOS agent experiences extreme queue contention today.
- Multiple PRs are in progress, running checks at the same time.
- Person A's PR's checks complete, Person A merges their PR. This causes checks to be queued on `main`.
- Person B's checks are still in progress.
- Person B notices their branch is outdated and will eventually fail to merge. So they hit "Update branch". This queues up yet _another_ set of checks. These new checks are now queued _behind_ their existing checks _and_ behind the `main` checks, delaying Person B even further.
The delays are compounded as we hit "update branch" over and over again hoping to get our PRs in.
Mitigation: cancel any existing workflows for a PR if that PR gets updated.
=> Cancel queued CI workflows if PR gets updated

compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/item/tests.rs, compiler/qsc_parse/src/prim.rs, compiler/qsc_parse/src/stmt.rs, compiler/qsc_parse/src/stmt/tests.rs
This is to lay the groundwork for signature help.
We should be able to parse just enough to know that the below is a function call, even before the user has typed the trailing semicolon. This way signature help can provide accurate parameter info when invoked at the cursor shown below.
```qsharp
namespace MyQuantumProgram {
open Microsoft.Quantum.Intrinsic;
operation Foo(x: Int, y: Double, z: String) : Unit {}
@EntryPoint()
operation Main() : Unit {
Foo(↘️)
let x = 3;
}
}
```
cc @ScottCarda-MS
=> Recover from missing semicolons

.github/workflows/ci.yml, .github/workflows/publish-playground.yml, npm/README.md, npm/package.json, package-lock.json, package.json, prereqs.py
Node.js seems to have fixed a bunch of test runner issues v18.
Bumping the prerequisite to v18.
=> Use Node 18 for GitHub workflows

language_service/src/lib.rs, language_service/src/protocol.rs, language_service/src/qsc_utils.rs, language_service/src/tests.rs, npm/package.json, npm/src/compiler/compiler.ts, npm/src/language-service/language-service.ts, npm/src/language-service/worker-proxy.ts, npm/test/basics.js, playground/src/editor.tsx, vscode/src/extension.ts, wasm/src/language_service.rs
Introducing a `WorkspaceConfiguration` concept to the language service which provides a central means of setting compiler options, including `TargetProfile` as well as `PackageType`, which we were previously passing in `update_document`.
In a future PR, these settings can be wired up to VS Code settings or to a VS Code command. (Draft PR #663)
I'm keeping compatibility with LSP in mind. The new `update_configuration` method carries the semantics of the [`workspace/didChangeConfiguration`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration) notification in LSP. 
We don't currently support per-document settings. I'm not sure if we would want to, given our current user scenarios (where would we persist such a setting …
=> Add ability to set target profile in language service

vscode/src/completion.ts
Add the samples as snippets to the completion list. Now in a file if you start typing 'sample' it will filter to the completions as shown below.
Adding a new menu command to "Open sample" seemed like overkill, and creating/opening a new doc comes with it's own issues. This is a super simple way just to create a new .qs file, type 'sample', and then hit tab to insert the sample.
=> Add samples as snippets to completions

samples/language/GettingStarted.qs
Updates the Minimal Sample to not explicitly open `Microsoft.Quantum.Intrinsic` since it is implicitly opened.
=> Remove Unnecessary open of `Microsoft.Quantum.Intrinsic`

compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_codegen/src/qir_base/tests.rs, pip/tests-qir/test_qir.py
This change applies a temporary fix to output recording when only a single result is present. By treating it as a tuple with arity one we include at least one aggregate recording function and trigger logic in the service.
=> Fixes a bug in single output recording

compiler/qsc_passes/src/baseprofck.rs, compiler/qsc_passes/src/baseprofck/tests.rs
=> Base profile validation should fail for entry point that returns `Unit`

version.py, vscode/package.json
The two different marketplace extensions can't have the same name. Prefix the dev build with '[DEV BUILD]'
=> Fix dev build name

.github/workflows/ci.yml, .github/workflows/devskim.yml
This ensures the same checks are used for pull_requests and merge_groups. See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions.
=> Enable CI checks for merge group

.vscode/launch.shared.json
If you have the QDK installed already, pressing F5 to launch/test the extension while developing causes conflicts. This settings disables other extensions when launch the extension from the repo for testing.
=> Disable other extensions when testing

compiler/qsc_eval/src/lib.rs
This adds additional help text to the `ReleasedQubitNotZero` error to help users understand the value of the strictness. Combined with a call-out in https://github.com/microsoft/qsharp/wiki/Differences-from-the-previous-QDK#stricter-checks-on-qubit-release fixes #450.
=> Add help comment to qubit release error

.ado/publish.yml, .cargo/config.toml, Cargo.lock, build.py, docker/linux-aarch64/Dockerfile, docker/linux-aarch64/build.sh, docker/linux-aarch64/entrypoint.sh, docker/linux-aarch64/install_prereqs.sh, docker/linux-aarch64/run.sh, pip/Cargo.toml
- Added `--samples/--no-samples` so that we can disable the compilation of samples during builds. This is needed when cross-compiling as we can't execute the compiler.
- Adding aarch64 linux release target. Cross-compiling on x86_64 and then running tests in an emulated aarch64 container along with auditwheel
- Adding aarch64 windows release target. This is built but not tested.
=> Publish aarch64 wheels for Linux and Windows

language_service/src/signature_help.rs, language_service/src/signature_help/tests.rs
Fixes a bug where the signature help wasn't handling single parameter callables correctly due to single-element tuples getting unwrapped.
=> Signature Help: Fixed Single-Param Lists

compiler/qsc/build.rs, compiler/qsc/src/bin/qsc.rs, compiler/qsc/src/bin/qsi.rs, compiler/qsc/src/lib.rs, compiler/qsc_ast/src/lib.rs, compiler/qsc_codegen/src/lib.rs, compiler/qsc_data_structures/src/lib.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_fir/src/lib.rs, compiler/qsc_frontend/src/lib.rs, compiler/qsc_hir/src/lib.rs, compiler/qsc_passes/src/lib.rs, katas/src/lib.rs, language_service/src/lib.rs, library/tests/src/lib.rs, pip/src/lib.rs, wasm/build.rs
We've discussed relaxing the clippy requirements for doc comments on public functions given that our crates are not published for use outside of the codebase. If we ever decide to publish we can turn these back on and follow more formal commenting requirements.
=> Relax clippy docs requirements

.ado/publish.yml, build.py
Reverting workaround for avoiding samples as they now run when they're supposed to.
=> Cleaning up samples execution in build script

compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs
This change adds an additional, optional to implement function for the `Backend` trait that can handle custom intrinsic callables by name. This will be an important extensibility point for later backends, though for now the only use is in the test that verifies the behavior.
=> Add custom intrinsic support to `Backend` trait

compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_frontend/src/typeck/check.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_hir/src/hir.rs, compiler/qsc_hir/src/ty.rs
This fixes a subtle bug in usage of UDTs across compilation units. Because a UDT is captured as a type that includes a `Res` in it, it wil have the placeholder `None` for it's package id when initially compiled (package ids are only known after insertion into the store). Later, a type mismatch could occur because the caller has the package id in the UDT type but the signature stored in the scheme uses UDT types with `None`. This fix adds a notion of updating a scheme to include the package id at type checking time by using `with_package` such that type checking for both internal/`None` resolutions and dependencies from other compilation units with known package ids can all be properly used.
=> Fix cross-unit UDT dependency

vscode/package.json, vscode/src/azure/commands.ts, vscode/src/azure/workspaceActions.ts
Fixes #761 
Also adds the ability to right-click on a workspace in the tree view and generate the Python code to connect to it.
=> Generate Python code and open browser for workspace

language_service/src/hover.rs, language_service/src/hover/tests.rs
Prevents generating a hover card for UDT fields expressions referencing erroneous field names.
Fixes #755.
=> Prevent Hover for Incorrect UDT Field

vscode/package.json
The correct notebook type to use for activation is `jupyter-notebook`, as seen [here](https://github.com/microsoft/qsharp/blob/569711f6df6a4790eed57f54015b2a2c1887c2be/vscode/src/notebook.ts#L13C30-L13C30) and [here](https://github.com/microsoft/vscode-jupyter/blob/450e4d0b8aa08e5471f108ee7100e7439aa34e49/package.json#L56). I'm not sure of the original reason that I had it wrong, but I'm guessing I copied [this incorrect sample](https://github.com/microsoft/notebook-extension-samples/blob/eb8c02dc206ee74f6550359af20881c8f3a98209/notebook-provider/package.json#L22).
Also fixed an issue where `npm start` was opening VS Code on the wrong workspace directory because the arguments were being parsed incorrectly.
=> Fix activation event for notebooks

.github/workflows/ci.yml, build.py, vscode/test/runTests.mjs
Temporary until I figure out what's going on:
- Don't run integration tests on pull requests (run on main only)
- Enable verbose output.
Permanent:
- Use `stable` vscode channel instead of `insiders`. No need to be on the bleeding edge for CI.
- Set job timeout to 15 minutes (from the default of 6 hours). This is very generous for the current run. We can extend it later if needed.
- Use `::group::` to collapse chatty workflow output https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
=> Mitigate impact of flaky integration tests

compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs
Previous fix for #510 incorrectly checked inferred lambda body type for unit instead of checking for convergence. This created two bugs: ambiguous types would be treated as unit improperly and implicit unit return would be treated as ambiguous.
Fixes #700
Fixes #790
=> Fix lambda return type inference

compiler/qsc/src/bin/qsc.rs, compiler/qsc/src/compile.rs, compiler/qsc/src/error.rs, compiler/qsc/src/incremental.rs, compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/lib.rs, compiler/qsc_frontend/src/error.rs, compiler/qsc_frontend/src/error/tests.rs, language_service/src/tests.rs, npm/src/compiler/compiler.ts, npm/src/language-service/language-service.ts, npm/src/vsdiagnostic.ts, npm/test/basics.js, playground/src/editor.tsx, vscode/src/diagnostics.ts, wasm/src/debug_service.rs, wasm/src/diagnostic.rs, wasm/src/language_service.rs, wasm/src/lib.rs, wasm/src/tests.rs
Fixes #750 . Addresses some of #149 .
Runtime error squiggles in the playground were off by one. The root cause was that we actually use `SourceMap` offsets, not `Source` offsets, to report the error. This sometimes used to "just work" since we always have a single file in the compilation. However, this really broke down when #614 inserted an additional EOF character between sources... and then when #622 moved the entry expression (`""` in this case) to the _beginning_ of the source map. 
Moreover, when runtime error spans came from stdlib, the offsets were just wildly off (since the spans were actually coming from stdlib). This probably wasn't noticeable since the UI "covered up" the problem by mapping the squiggles to the very end of the document.
So, the bulk of this PR is properly …
=> Error squiggle span fixes

Cargo.lock, Cargo.toml, compiler/qsc_ast/src/ast.rs, compiler/qsc_fir/src/fir.rs, compiler/qsc_fir/src/ty.rs, compiler/qsc_hir/src/hir.rs, compiler/qsc_hir/src/ty.rs
Per discussion with @swernli , now pinning major.minor in Cargo.toml instead of major.minor.patch.
Updated all direct dependencies to the latest version on crates.io (and in the case of qir-runner, the most recent commit). Then `cargo update` to bring indirect dependencies up to date.
`indenter` changed the type of `Format::Custom::inserter`. Updated our usage to fix the build break.
=> Update cargo dependencies to latest

.devcontainer/devcontainer.json
This change updates the devcontainer definition to use a Python base image and install Rust as a feature rather than the other way around. This avoids an issue where the Python feature fails building 3.12 from source, and generally makes perf better for fresh containers since Rust and npm features install quickly. Of note, this also adds `cargo update --dry-run` as a post-build command to ensure the crates.io index is updated on new container creation, preventing an issue where crates would get downgraded on first build due to old index cache.
=> Update devcontainer for Python 3.12

language_service/src/display.rs, language_service/src/signature_help.rs, language_service/src/signature_help/tests.rs
Adds signature help to the language server for indirect call expressions based on the type of the callee expression. This allows signature help to be given for all call expressions, including lambdas, local captures of callables and partial applications, functor applications, arrays of callables, and callables returned from a block, and UDT constructors.
=> Signature Help for Indirect Calls Based on Type

compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/item/tests.rs, compiler/qsc_parse/src/lib.rs
This adds more granular error messages when attributes or visibility modifiers are present without an attribute, following the pattern introducing for the "floating" doc comment errors.
Fixes #757
=> Provide more specific error messages for missing `Item`s

npm/src/compiler/compiler.ts
Apparently, the website intends to use this to check the validity of generated Q# snippets. This seems like a legitimate use case. It's a perfectly good API :)
My original intention for deprecating `checkCode` was to guide people towards using the language service for editor squiggles, and that mission has already been accomplished...
=> Un-deprecate `checkCode`

compiler/qsc/src/incremental.rs, compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc/src/lib.rs, compiler/qsc_frontend/src/incremental.rs, compiler/qsc_frontend/src/incremental/tests.rs
This change is required for the notebook language service (#759). The new public method is not used in this PR yet. It will be used in #759.
This change adds two flavors of `compile_fragments` to the incremental compiler: one that fails fast and one that accumulates errors but continues compilation.
When calling from the interpreter, we want to fail fast when parsing fails, so that we don't pollute the resolver/checker/lowerer state with flawed data when we already _know_ that cell execution will fail.
On the other hand, when calling from the language service, we want to continue compilation even in the case of errors, so we can finish building our AST & HIR we will use for editor features. Also, this way we can report resolve/check errors even if there are syntax error elsewhere in the …
=> Add ability to continue on error for incremental compiler

katas/content/oracles/index.md
This change fixes a math rendering error in the conclusion of the Oracles kata.
=> Fix math rendering in Oracles kata

.ado/publish.yml, version.py
Publish the RC builds of VS Code and qsharp-jupyterlab without the pre-release specifiers (until we get to the final 1.0 build)
=> Remove prerelease on rc builds for ext and jupyter

.github/workflows/ci.yml, .github/workflows/devskim.yml
Since we now use merge queues to handle ensuring up-to-date code is checked before going into main, there really isn't value in running these two pipelines after each merge to main. This change disables them for those scenarios and leaves them as part of PR and merge queue runs. After merge to main we still run playground publishing and fuzzing (if applicable).
=> Remove push trigger for main branch in CI and DevSkim workflows

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_parse/src/expr.rs, compiler/qsc_parse/src/expr/tests.rs, library/tests/src/test_math.rs
* Fixes #828, using wrapped arithmetic operations for the 64 bit ints, preventing panic in debug mode.
* Modulo by 0 now produces Error::DivZero rather than panicking
* Allow i64::MIN literals of any radix (not just decimal)
* Added relevant tests
Note: For consistency, wrapping_* methods are now  used for almost all arithmetic operations, except for exponentiation and shifting:
* In the case of exponentiation, the previous behavior was to produce Error::IntTooLarge for extremely large exponents (larger than u32::MAX).  I simply extended that behavior to always produce Error::IntTooLarge in case of overflow.  Since this error complains about the exponent, it could be misleading since `10000000^3` will say that 3 is too large, so you may want to consider changing this.  Alternatively, it …
=> Improved handling of int overflow

compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_codegen/src/qir_base/tests.rs
The previous change to disallow qubit reuse was too aggresive with how it used fresh qubit ids, causing programs to get too big too fast. The problem was the assumption that a qubit that is released can never be used again. Instead, this updates the logic to ensure that qubits that are released without ever having been measured or reset can be reused in later allocations. As an example, this takes the Grover's Search sample program from using 29 qubits to using 9 by allowing reuse of unmeasing auxiliary qubits used during decomposition of multi-controlled gates.
=> Allow reuse of unmeasured qubits in QIR codegen

compiler/qsc_ast/src/ast.rs, compiler/qsc_ast/src/mut_visit.rs, compiler/qsc_ast/src/visit.rs, compiler/qsc_data_structures/src/span.rs, compiler/qsc_eval/src/lower.rs, compiler/qsc_frontend/src/lower.rs, compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/typeck/convert.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_hir/src/hir.rs, compiler/qsc_hir/src/mut_visit.rs, compiler/qsc_hir/src/visit.rs, compiler/qsc_parse/src/expr/tests.rs, compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/item/tests.rs, compiler/qsc_parse/src/lib.rs, compiler/qsc_parse/src/prim.rs, compiler/qsc_parse/src/stmt/tests.rs, compiler/qsc_passes/src/borrowck.rs, compiler/qsc_passes/src/replace_qubit_allocation.rs, language_service/src/display.rs, language_service/src/hover.rs, language_service/src/signature_help.rs, language_service/src/signature_help/tests.rs
This uses a more complex but ultimately more correct approach that fixes #672. By creating default error kinds for several of the AST and HIR types that can appear in sequences, sequence parsing recovery now inserts error entries to correspond to places where commas appear at the start of a sequence or back-to-back in the sequence. The end result is better signature help due to recovered HIR including placeholder error entries.
=> Use `Default` to handle missing entry in sequence

package-lock.json, package.json
Contains a fix for https://github.com/microsoft/vscode-test-web/issues/106 . I see at least one 504 error in main in the last couple of weeks, so this should improve stability.
I'll continue to monitor the integration tests after this and reenable them on PRs if they're stable.
=> Update @vscode/test-web for integration test stability fix

compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_frontend/src/typeck/check.rs, compiler/qsc_parse/src/item/tests.rs
When an attriute expression includes the nested definition of an item, we were incorrectly checking the type signatures of that item even though it was not included in early parts of type checking, leading to a panic. This update correctly ignores items in attributes for both phases of type checking instead of just the first one.
Fixes #846
=> Fuzz: "thread '<unnamed>' panicked at compiler/qsc_frontend/src/typeck/rules.rs:368:57:" (ubuntu-latest)

compiler/qsc_ast/src/ast.rs, compiler/qsc_data_structures/src/span.rs, compiler/qsc_parse/src/prim.rs
This follows up on feedback from #836 and removes the `DefaultWithSpan` trait in favor of a cleaner implementation of the `WithSpan` trait for boxed types. The impl for `Box<T>` now correctly avoids the extra allocation by editing the item in place and then returning it.
=> Remove `DefaultWithSpan` trait

Cargo.lock, Cargo.toml, compiler/qsc/src/interpret/stateful.rs, pip/Cargo.toml, pip/qsharp/__init__.py, pip/qsharp/_native.pyi, pip/qsharp/_qsharp.py, pip/src/displayable_output.rs, pip/src/displayable_output/tests.rs, pip/src/interpreter.rs, pip/tests/test_interpreter.py, pip/tests/test_qsharp.py
This adds a `dump_machine` API that allows Python code to get the allocated qubit count and dictionary of sparse state amplitudes in Python. This will enable more test scenarios in Python for Q# code.
This also includes an update to how `BigInt` values are returned in Python by using the arbitrary bitwidth Python integer type instead of formatting them as a string.
=> Add `dump_machine` to Python API

library/std/internal.qs
This enables higher flexibility for the backends.
=> Use CCX intrinsic for CCZ decomposition

compiler/qsc/benches/eval.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/val.rs
This change updates the way array append and index update are performed in the evaluator to optimize the cases where the updates are known to happen "in-place" and change the original array. These are of the form `set arr += other;` and `set arr w/= i <- val;`, which are quite common in user code. This change introduces two new benchmarks to evaluate the perf impact of the changes, where 10k appends/updates are performed in a loop. The benchmarks show significant improvement, about 78% in append and 98% in update:
```
Array append evaluation time:   [555.13 µs 558.17 µs 561.69 µs]
change: [-77.935% -77.702% -77.539%] (p = 0.00 < 0.05)
Performance has improved.
Array update evaluation time:   [498.40 µs 499.06 µs 499.84 µs]
change: [-98.646% -98.632% -98.621%] (p = 0.00 < 0.05)
Performance …
```
=> Improve perf on array operations that can be done in-place

compiler/qsc_eval/src/val.rs
This changes the implementation of `Value::unit()` to use a thread local `Rc` for the empty tuple, allowing unit to be created once and then reused instead of allocating a fresh instance each time. Because many Q# expressions return unit that then just gets consumed by the semicolon terminated statement they are part of, this saves both an allocation on the creation and a deallocation as the `Rc` count gets decremented but does not go to zero, keeping the underlying empty array from needing to be dropped. This results in some nice performance gains during execution:
```
Teleport evaluation     time:   [79.585 µs 79.755 µs 79.976 µs]
change: [-9.9140% -9.2630% -8.6576%] (p = 0.00 < 0.05)
Performance has improved.
Deutsch-Jozsa evaluation
time:   [19.515 ms 19.539 ms 19.563 ms]
change: …
```
=> Optimize `Value::unit()` to avoid additional allocations

compiler/qsc/src/interpret/debug/tests.rs, compiler/qsc/src/interpret/stateful/stepping_tests.rs, compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_codegen/src/qir_base/tests.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_frontend/src/error/tests.rs, compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_frontend/src/resolve/tests.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_passes/src/baseprofck/tests.rs, compiler/qsc_passes/src/borrowck/tests.rs, compiler/qsc_passes/src/callable_limits/tests.rs, compiler/qsc_passes/src/conjugate_invert/tests.rs, compiler/qsc_passes/src/entry_point/tests.rs, compiler/qsc_passes/src/logic_sep/tests.rs, compiler/qsc_passes/src/spec_gen/tests.rs, language_service/src/completion/tests.rs, language_service/src/definition/tests.rs, language_service/src/hover/tests.rs, language_service/src/references/tests.rs, language_service/src/rename/tests.rs, language_service/src/signature_help/tests.rs, language_service/src/tests.rs, library/tests/src/test_canon.rs, library/tests/src/test_measurement.rs, library/tests/src/tests.rs
The solution does not compile with Rust/Cargo 1.74.0 and clippy 0.1.74 due to to a flood of [unnecessary hashes around raw string literal](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_raw_string_hashes) clippy complaints
=> removed unnecessary hashes around raw string literals

vscode/src/common.ts, vscode/src/diagnostics.ts
This was exposed when multi-file project support was added in #849 . Diagnostics can be returned from closed files. We have to load the file contents to be able to map line/column offsets.
=> Handle diagnostics for closed documents in VS Code

compiler/qsc_project/Cargo.toml
Profile settings are not respected in a child Cargo.toml of a workspace, so these should just be removed.
=> Remove test profile from qsc_project Cargo.toml

compiler/qsc/src/interpret/stateful/re/counts/tests.rs, compiler/qsc/src/interpret/stateful/re/estimates/data/report.rs
This fixes builds with Rust 1.74
=> Suppress more raw string hash warnings

jupyterlab/pyproject.toml
This adds the newly required sections to the hatchling build and making sure the right files get included in the wheel.
See https://github.com/pypa/hatch/issues/1113 for context.
=> Fix hatchling build by adding required sections

samples/algorithms/Grover.qs
Because the Grover's algorithm sample does a bit shift by the number of qubits, we should verify that the sample does not use more than 63 qubits since that would cause a somewhat arcane error in the bitwise operation.
=> Add qubit number pre-check to Grover

Cargo.lock, Cargo.toml, language_service/Cargo.toml, language_service/src/lib.rs, language_service/src/project_system.rs, language_service/src/protocol.rs, language_service/src/state.rs, language_service/src/state/tests.rs, language_service/src/tests.rs, npm/src/compiler/compiler.ts, npm/src/language-service/language-service.ts, npm/test/basics.js, vscode/src/extension.ts, wasm/Cargo.toml, wasm/src/language_service.rs, wasm/src/lib.rs, wasm/src/serializable_type.rs
This PR allows us to use async methods (e.g. for loading the project) when updating the compilation state in the language service, without interfering with read operations such as `getCompletions`. 
We can divide language service methods into two kinds of operations: reads and updates. The `CompilationState` is shared.
* Read operations, which are always synchronous, immutably borrow the `CompilationState`.
* Update operations, instead of performing the update directly, post a message to a channel which is then read by an update worker that processes the updates one by one. The update worker can do asynchronous work without interfering with any other language service operations. The update worker only mutably borrows the `CompilationState` briefly to update it.
=> Async updates for the language service

compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs
This updates a few spots where type equality constraints were used in the type checker and had the whole expression span rather than just a component of the expression. This makes it easier to identify specific parts of an expression with type errors, especially for larger expressions like addition of multiple variables.
=> Use more targeted spans for type equality errors

compiler/qsc/src/interpret/stateful.rs, pip/src/interpreter.rs, wasm/src/diagnostic.rs
The name of this error didn't make any sense anymore :) . It's also not clear to the user what they should do to fix it when we run into this error in Python.
Before:
After:
=> Make TargetMismatch error more user-friendly

library/std/intrinsic.qs, library/tests/src/lib.rs, library/tests/src/tests.rs
When simulating with Base profile, auxiliary qubits used during measurement were not being reset before being released. This fixes that by using the measure and resest intrinsic and adds a test case to verify behavior.
=> Fix release of aux qubit in base profile measurement

compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_codegen/src/qir_base/tests.rs
For base profile, we need to "reset" the qubit identifier for qubits that are measured such that later use of the same ID gets a fresh hardware ID. Because the underlying bug was a subtle misuse of the two types (where we have a map from `usize` to `usize`), this change adds a little bit of extra type safety by ensuring that mapped qubits are a new wrapper type `HardwareId`. Added a test case that confirms qubit reuse behaves as expected.
Thanks @cesarzc for figuring this one out!
=> Fix bug in qubit reset on measure logic

compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/re/counts.rs, compiler/qsc/src/interpret/stateful/re/estimates/data.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_frontend/src/compile.rs, compiler/qsc_hir/src/ty.rs
This PR applies the Rust 1.74 clippy lints. These don't get hit in our pipeline now, but they will when we update.
=> Run clippy on `qsc/stateful/re`

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_eval/src/val.rs, compiler/qsc_frontend/src/typeck/tests.rs
This change adds full support for copy-update and assign-update using ranges. With this fix, patterns like the following are now correctly supported:
```qsharp
[0, 1, 2] w/ 1..2 <- [10, 11]
// yields [0, 10, 11]
[0, 1, 2, 3] w/ ...2... <- [10, 11]
// yields [10, 1, 11, 3]
mutable x = [1, 2, 3, 4];
set x w/= 2..-1..0 <- [10, 11];
// x updated in-place to [1, 11, 10, 4]
```
Fixes #933
=> Support Copy-and-Update for Array with Range

compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/resolve/tests.rs
=> Compile/Design-Time Checks for Variable Scopes Don't Work Properly with Qubit Allocation Blocks

.github/workflows/ci.yml
goals:
-  Accomplished by not failing the stage based on any threshold
This PR adds a CI stage to benchmark a feature branch against main. It only works on criterion benches, so we are using it in `compiler/qsc`. I believe this is a good starting point, as that encapsulates all compiler logic.
=> Add performance benchmarks to CI

wasm/src/language_service.rs
VSCode/Monaco expect the documentation member of `SignatureInformation` and `ParamterInformation` to always be defined in order to check the length (see https://github.com/microsoft/vscode/blob/eb55c74a90679ba9471ea942b7cb8e6df2b24fad/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L285-L296). As a result, we should not be serializing `None` values as undefined, but rather convert those to the empty string before sending them as part of the serialized `ISignatureHelp` type.
Fixes #913
=> Use empty string for signature help when no documentation present

pip/qsharp/_native.pyi, pip/src/fs.rs, pip/src/interpreter.rs, pip/tests/test_project.py
Format compilation errors when failing to compile project files provided to `qsharp.init()`.
Before:
After:
=> Format compilation errors from project import in Python

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, library/std/math.qs, library/tests/src/test_math.rs
This change removes division by zero checks for floating point values and returns to previous behavior for Q#. Specifically:
- 0.0 / 0.0 produces NaN
- 1.0 / 0.0 produces inf
- -1.0 / 0.0 produces -inf
To work with infinite values, this also reintroduces `Microsoft.Quantum.Math.IsInfinite` as a counterpart to `IsNaN` in the same namespace.
Fixes #870
=> Remove division by zero check for floating point

language_service/src/lib.rs, language_service/src/state.rs, language_service/src/state/tests.rs, npm/src/language-service/language-service.ts, vscode/src/common.ts, vscode/src/extension.ts, vscode/src/notebook.ts, wasm/src/language_service.rs
Fixes #873
ISSUE 1 (#873):
`close_notebook_document` takes both the notebook URI and a list of cell URIs, which is redundant, since we should already know in the language service which cells belong to the notebook. We still had an assert to verify that these two parameters were being sent consistently - and it turns out they weren't. When the last Q# cell in a notebook is deleted, we send `close_notebook_document` with _no_ Q# cells (instead of the last known list). That tripped the assert.
I'm just removing the redundant `cell_uris` parameter and using the open document map instead.
ISSUE 2 (new panic):
I'm 99.99% sure this is a change in VS Code, since this panic is so trivial to hit. All you have to do is close a notebook. I tried with builds of `qsharp` from September, and I still hit …
=> Fix notebook language service panics

library/std/unstable_arithmetic.qs
Improves T-count for `ReflectAboutInteger` and considers common case `index == 0` as special case.
=> Low T-count for reflection

compiler/qsc_frontend/src/compile.rs, compiler/qsc_frontend/src/compile/preprocess.rs, compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_frontend/src/resolve/tests.rs, library/std/convert.qs, library/std/diagnostics.qs, library/std/intrinsic.qs, library/std/measurement.qs, library/std/random.qs, library/std/re.qs, library/std/unstable_arithmetic_internal.qs, library/std/unstable_table_lookup.qs
Doing my part in the renaming effort.
This PR changes the Q# syntax from `Config(Full)` to `Config(Unrestricted)`
=> Switch syntax from Config(Full) to Config(Unrestricted)

.github/workflows/ci.yml
The memtest task was causing spurious failures during merge group builds because it failed to write back a comment even though it ran successfully (merge group builds do not associate back to a signle issue/PR). This skips the comment step if `github.base_ref` is null, so will still run but not try to write back specific results.
=> Skip running memtest in merge groups

language_service/src/completion.rs, language_service/src/completion/tests.rs
Fixes #994 .
The "where to insert the open statement" logic was totally breaking down for notebooks, which don't typically have namespaces, and may not even have any item declarations. So we can do the simplest possible thing and insert it at the top of a cell.
=> Fix: open statements get inserted in the wrong position in notebooks

vscode/src/debugger/output.ts
Each DumpMachine line was being written as it's own message, causing duplicate lines (such as blank lines) to be collapsed and counted with a grey circle. This gives the impression duplicate DumpMachine state was reported and collapsed. With this change, it's one message.
BEFORE
AFTER
=> Output DumpMachine as one message

compiler/qsc/src/interpret/debug.rs, compiler/qsc/src/interpret/stateful.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_eval/src/debug.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_eval/src/val.rs, compiler/qsc_fir/src/fir.rs
This change formally introduces an FIR `PackageStore` such that it can be later used in runtime capabilities analysis (RCA).
It also refactors the way lookups are performed on an FIR package store in a consolidated way, reducing code duplication and making the lookup functionality available to the RCA implementation.
=> Formally introduce an FIR `PackageStore` struct and consolidate lookups

.github/workflows/ci.yml
With this change, our pipeline only comments about memory usage if there is a diff. If not, we omit the comment but log in the pipeline to confirm that there was no diff. I hope this reduces per-PR noise.
=> Only comment memory benchmark results if there is a difference

compiler/qsc/src/interpret/stateful.rs, compiler/qsc/src/interpret/stateful/tests.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/intrinsic/tests.rs, pip/qsharp/_native.pyi, pip/qsharp/_qsharp.py, pip/src/interpreter.rs, pip/tests/test_interpreter.py, resource_estimator/src/counts.rs, resource_estimator/src/lib.rs
This change removes the shots argument to the `run` API in stateful interpreter now that all callers pass 1. This avoids the need to wrap interpreter results in an additional vector and simplifies calling patterns. All consumers already passed 1 and had a shot loop around the call to `run` or utilized other APIs.
This also removes the need for a `reinit` function on the `Backend` trait, since now a simulator is only used once before being recreated.
=> Remove shots from statful interpreter `run` API

compiler/qsc_frontend/src/lower.rs, compiler/qsc_frontend/src/lower/tests.rs
We missed one instance of "Full" in an error message that needed to change to "Unrestricted" insetad.
=> Fix left behind use of "Full" in error message

compiler/qsc_frontend/src/compile.rs
Rename a couple of runtime capability flags for consistency before they are extensively used in runtime capabilities analysis.
=> Rename a couple of runtime capability flags for consistency

compiler/qsc_frontend/src/typeck/infer.rs, compiler/qsc_frontend/src/typeck/tests.rs
Updated the type-checker to recognize UDT field references that refer to fields named `Start`, `Step`, and `End` without raising a type error.
=> Allow Range Fields on UDTs

compiler/qsc/src/interpret.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/lower.rs, compiler/qsc_fir/src/fir.rs, compiler/qsc_fir/src/mut_visit.rs, compiler/qsc_fir/src/visit.rs
This change removes qubit statements from FIR since those are eliminated by HIR passes.
=> Remove qubit statements from FIR.

build.py, npm/src/log.ts, vscode/src/extension.ts, vscode/src/logging.ts, vscode/test/runTests.mjs, vscode/test/suites/extensionUtils.ts, vscode/test/suites/language-service/language-service.test.ts, vscode/test/suites/language-service/notebook.test.ts, vscode/test/suites/run.ts
This is an attempt at fixing or mitigating #963, but since I can't repro that one reliably, we won't be sure for a while.
* Product change: fix VS Code log formatting.
Before:
After:
Test changes: 
* Explicitly activate the Q# extension before the tests start. This should eliminate issues where the activation itself is taking a long time for whatever reason and timing out the test cases, which have a reasonably conservative timeout of 2s.
* Write Q# logs to the console in the integration tests.
* Disable the ugly verbose vscode / webserver logs by default. They were helpful to debug infrastructure issues but we don't need them at the moment.
=> More predictable init and better logging in VS Code tests

compiler/qsc/src/interpret.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs
This change refactors the interpreter API to unify around some common patterns and reduce places that look like exceptions. Several of the APIs used what appeared to be different patterns for how they invoked the evaluator when it turns out they were all minor, surface differences except for a few differences in input values. Using a wrapper function clarifies where the common patterns are and makes it easier for future updates to reuse them.
=> Refactor common interpreter patterns

.github/workflows/ci.yml
This change updates the logic for the build matrix to skip macOS when building for PRs and enables integration tests. This keeps the contentions and slower macOS runners reserved for merge queue to main.
To make this work nicely with branch protection rules, a "Status Check" task is introduced that depends on previous jobs, only executes on failure of dependencies, and always fails. Branch protection treats this job as required, and then PR build will require only those matrix combinations enabled in that context while merge queues will require the full matrix to run and pass.
=> Skip macOS in PR builds, include integration tests

.github/workflows/ci.yml
`github.rest.issues.createComment({ ... })` is throwing an error when running the memory profile on PRs from forks. We want to treat this failure as warning instead of an error.
=> Ignore failed PR comment when PRs are from forks

compiler/qsc/src/interpret.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, pip/qsharp/__init__.py, pip/qsharp/_native.pyi, pip/qsharp/_qsharp.py, pip/src/interpreter.rs, pip/tests/test_interpreter.py, pip/tests/test_qsharp.py
This adds new Python APIs `qsharp.set_quantum_seed` and `qsharp.set_classical_seed` that allow users to fix the seed and sequence of random quantum measurements and/or random classical numbers generated from simulating Q#.
Fixes #1013
=> Support setting classical and quantum random seeds

compiler/qsc/src/interpret.rs, compiler/qsc_fir/src/validate.rs, compiler/qsc_fir/src/visit.rs
This change updates the `get_*` methods to use an immutable reference to `self` rather than a mutable one.
Note: this helps when implementing callable cycle detection on FIR using the visitor pattern.
=> FIR non-mutable visitor does not need mutable getters

vscode/src/debugger/session.ts
- Old behavior
- Line BP in operation only effects the body functor
- Line BP on line with multiple statements puts BP on every statement in that line
- Inline BP in operation will trigger on body functor for selected statement
- New behavior
- Line BP in operation only effects all functors generated from body with BP
- Line BP on line with multiple statements puts BP on every statement in that line
- Inline BP in operation will trigger on all functors generated from the body BP
=> Enable breakpoints across all functors

vscode/src/azure/providerProperties.ts
We were missing a recently added qpu target in the supported target list.
=> Include new target

.github/workflows/ci.yml
Now that `macos-14` runners are available broadly, we can use those to get the must faster M1 based builds and actually test on arm64 Mac in CI.
See https://github.com/microsoft/qsharp/actions/runs/7721944262 for successful CI run that includes macOS.
=> Use `macos-14` runners

library/std/arrays.qs, library/std/diagnostics.qs, library/std/internal.qs, library/std/math.qs, library/std/re.qs, library/std/unstable_arithmetic.qs
Found and corrected a bunch of typos and misspellings in the doc strings.
=> Fixed a bunch of typos in Q# standard lib documentation

vscode/src/debugger/session.ts
=> Session now exits when there is a runtime failure when running without debugging

vscode/test/suites/run.ts
I accidentally broke VS Code integration test error reporting with #1015. `run()` should raise an error if any tests fail, but it was swallowing the error after writing to console.
This made it so that CI would succeed even when tests failed. I did manually look through the last few days' runs and didn't see any actual failures.
=> Fix error reporting in vscode integration tests

playground/src/main.tsx, vscode/src/completion.ts
https://github.com/microsoft/qsharp/pull/880 added support for locals in completion list. 
What was still missing in the Monaco playground and VS Code extension is mapping to the relevant icon.
Before:
After:
=> use relevant icon for locals completion

vscode/package.json, vscode/src/projectSystem.ts
This seems like what we should be doing anyway, but has the benefit that when using the language service or the debugger in a multi-file project, then everything just works even if the files haven't been saved to disk yet.
Putting up early for review, but in initial testing looked to behave as expected.
=> Prefer open file contents to disk contents

pip/qsharp/_fs.py
Use `utf-8-sig` when opening a file to interpret the BOM if it exists.
Fixes #1099
=> Fix BOM handling in Python

vscode/src/extension.ts
The `OpenedDocument` event includes either `Qsharp` or `JupyterCell` for its document type, but the query was causing all documents to be treated as `Qsharp`. Swapping the ordering so we can correctly distinguish cells for this event.
=> Fix `documenttype` for `OpenedDocument` event

.github/workflows/ci.yml
This change adapts to the recent GitHub default token permissions update by allowing our CI actions the right permissions to write back to PRs.
=> Explicitly allow commenting permissions for CI actions

pip/src/displayable_output.rs, pip/src/displayable_output/tests.rs, pip/src/interpreter.rs
This change uses the vector returned from the internals directly rather than converting into a hashmap so that the state ordering can be preserved for display.
Fixes #1119
Before:
After:
=> Fix state ordering in Python

npm/ux/estimatesOverview.tsx
fixes #1093 and #1094
Still could not delete the very last row in Jupyter but it could be a problem on the AnyWidget side (model.set() for empty content).
=> support single line inputs for RE table in Jupyter

compiler/qsc/src/lib.rs, compiler/qsc/src/location.rs, language_service/src/definition.rs, language_service/src/definition/tests.rs, language_service/src/hover/tests.rs, language_service/src/lib.rs, language_service/src/protocol.rs, language_service/src/qsc_utils.rs, language_service/src/references.rs, language_service/src/references/tests.rs, language_service/src/rename.rs, language_service/src/rename/tests.rs, language_service/src/test_utils.rs, wasm/src/language_service.rs, wasm/src/line_column.rs
A `Location` refers to a span within a specific source file. It's expressed as a source name and `Range`. See: https://github.com/microsoft/vscode/blob/7923151da4b3567636c1346df9e8ba682744bbf3/src/vscode-dts/vscode.d.ts#L6581
It was defined in the language service protocol, but I'm moving it to a more common location in `compiler/qsc` since I need the debugger to use it in #1107.
To summarize this PR and #1038, here's how locations are represented in the compiler vs. higher-level components that interface with VS Code (debugger, language service):
 
| Compiler representation | Line/column representation |
|---|---|
| `u32` offset (into `SourceMap`) | `Position` (into specific source file) |
| `Span` | `Range` |
| (`PackageId`, `Span`) | `Location` |
=> Move the Location struct to a more common place

vscode/src/notebook.ts, vscode/test/suites/extensionUtils.ts, vscode/test/suites/language-service/notebook.test.ts
=> Set notebook cell language back to Python if `%%qsharp` magic isn't there

library/src/lib.rs, library/src/tests.rs, library/src/tests/logical.rs, library/std/logical.qs
Fixes #1096 
The motivation is discussed in that issue as well. I put in the `Microsoft.Quantum.Logical` namespace, but we can move it into a different one if needed.
=> Added support for boolean exclusive disjunction in standard library

compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/resolve/tests.rs, compiler/qsc_hir/src/global.rs
This adds new logic to name resolution to verify that any callable declared as `body intrinsic` has a globally unique name.
This fixes #1130.
=> Check for duplicate intrinsics globally

katas/content/single_qubit_gates/index.md
... here’s an issue with missing text in the SingleQubitGates tutorial (in the ADO, it’s https://dev.azure.com/ms-azurequantum/AzureQuantum/_workitems/edit/12559):
The file https://github.com/microsoft/qsharp/blob/main/katas/content/single_qubit_gates/index.md does not have the sections "Identity" and "Hadamard gate" before the exercise "Prepare Minus" from the original notebook https://github.com/microsoft/QuantumKatas/blob/main/tutorials/SingleQubitGates/SingleQubitGates.ipynb. ...
=> Wi12559 - Restore missing text.

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs
This checks ahead of time if the array we want to update in-place is uniquely referenced and correctly falls back to the previous, unoptimized path that makes a copy.
Fixes #1146
=> Fix panics on In-place update optimization

compiler/qsc_eval/src/lower.rs, compiler/qsc_frontend/src/typeck/convert.rs, compiler/qsc_hir/src/ty.rs, language_service/src/hover/tests.rs
This fixes the issue by adding the original functor set for any functor params to the data structure and updates the custom display used in hover to print the actual functors rather than the param.
Fixes #1148
=> Fix hover type shown for lambda passed to generic function

Cargo.lock, compiler/qsc_codegen/Cargo.toml, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_codegen/src/qir_base/postfix.ll, compiler/qsc_codegen/src/qir_base/tests.rs, compiler/qsc_eval/src/lib.rs
This change adds support for generating QIR with custom intrinsic callables. Any Q# operation or function declared as `body intrinsic` that is not part of the recognized built-in callables will be inserted as a call to an extern function in the QIR declared with the provided arguments and with a `void` return (see limitations below). These functions must be recognized and supported by the consumer of the QIR or it may cause compilation or linking failure further down the pipeline. Note that custom intrinsics will still fail simulation.
This fixes #825.
- A custom intrinsic that returns types other than `Unit` causes a runtime error during code generation with help text that advises the use of `Unit`: 
- Passing complex, memory backed types to custom intrinsics (`BigInt`, arrays, tuples) …
=> Support generating QIR with custom intrinsics

compiler/qsc/benches/eval.rs
This adds a new benchmark to evaluate performance of deeply nested iteration and mutation of arrays.
=> Add new nested iteration benchmark

npm/test/basics.js
This is meant to make it easier for people authoring on new katas.
=> Modify 'getAllKatas works' test to reduce friction when working on new katas

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/lower.rs, compiler/qsc_fir/src/assigner.rs, compiler/qsc_fir/src/fir.rs
This change improves performance by using an `IndexMap` for variable bindings at runtime. This is enabled by introducing a new identifier type in FIR specific to local variables that gets assigned contiguous IDs during lowering.
=> Optimize variable binding/access during runtime

compiler/qsc_eval/src/lib.rs
This error case caused the additional allocation of string, which could be avoided by switching `.ok_or` to `.ok_or_else`, but in practice this error case is no longer possible now that type checking verifies supported functors at compile time.
=> Remove missing spec error case

language_service/src/code_lens.rs, language_service/src/code_lens/tests.rs, language_service/src/compilation.rs, language_service/src/lib.rs, language_service/src/protocol.rs, language_service/src/test_utils.rs, npm/src/language-service/language-service.ts, npm/src/language-service/worker-proxy.ts, vscode/src/codeLens.ts, vscode/src/extension.ts, vscode/test/suites/language-service/language-service.test.ts, wasm/src/language_service.rs
This adds "Run | Histogram | Estimate | Debug" commands above the entrypoint in source files.
=> Show code lens on entrypoints to invoke commands

compiler/qsc_data_structures/src/display.rs, compiler/qsc_data_structures/src/functor.rs, compiler/qsc_data_structures/src/functors.rs, compiler/qsc_data_structures/src/lib.rs, compiler/qsc_eval/src/debug.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/val.rs
This change moves `FunctorApp` to a shared location so it can also be used by runtime capabilities analysis (RCA).
=> Move `FunctorApp` to a shared location

compiler/qsc/src/interpret.rs, compiler/qsc_codegen/src/qir_base.rs, compiler/qsc_fir/src/fir.rs
When we query a package from an FIR package store, we always expect the package to be present in the store. Therefore, there is no need to return an option (we always use `expect` to extract the package reference from the option).
This change modifies the `get` and `get_mut` methods for `fir::PackageStore` such that they return a reference to a package instead of an option.
=> Make FIR package store queries return `&Package` instead of `Option<&Package>`

compiler/qsc_doc_gen/src/generate_docs.rs
Fixes "opeartion" to "operation" in the generated docs' metadata.
=> Fix Typo in Docs Metadata

katas/content/single_qubit_measurements/a_b_basis_measurements/Placeholder.qs, katas/content/single_qubit_measurements/a_b_basis_measurements/Solution.qs, katas/content/single_qubit_measurements/a_b_basis_measurements/Verification.qs, katas/content/single_qubit_measurements/distinguish_0_and_1/Placeholder.qs, katas/content/single_qubit_measurements/distinguish_0_and_1/Solution.qs, katas/content/single_qubit_measurements/distinguish_0_and_1/Verification.qs, katas/content/single_qubit_measurements/distinguish_0_and_1/solution.md, katas/content/single_qubit_measurements/distinguish_orthogonal_states_1/Placeholder.qs, katas/content/single_qubit_measurements/distinguish_orthogonal_states_1/Solution.qs, katas/content/single_qubit_measurements/distinguish_orthogonal_states_1/Verification.qs, katas/content/single_qubit_measurements/distinguish_orthogonal_states_1/index.md, katas/content/single_qubit_measurements/distinguish_orthogonal_states_2/Placeholder.qs, katas/content/single_qubit_measurements/distinguish_orthogonal_states_2/Solution.qs, katas/content/single_qubit_measurements/distinguish_orthogonal_states_2/Verification.qs, katas/content/single_qubit_measurements/distinguish_orthogonal_states_2/solution.md, katas/content/single_qubit_measurements/distinguish_plus_and_minus/Placeholder.qs, katas/content/single_qubit_measurements/distinguish_plus_and_minus/Solution.qs, katas/content/single_qubit_measurements/distinguish_plus_and_minus/Verification.qs, katas/content/single_qubit_measurements/distinguish_plus_and_minus/index.md, katas/content/single_qubit_measurements/distinguish_plus_and_minus/solution.md, katas/content/single_qubit_measurements/implementing_measurement/Example.qs, katas/content/single_qubit_measurements/index.md, katas/content/single_qubit_measurements/measurement_statistics/Example.qs
Mostly making code snippets more compact, formatting, and adding info about MResetZ
=> Clean up Single-Qubit Measurements kata

compiler/qsc_doc_gen/src/generate_docs.rs, compiler/qsc_doc_gen/src/generate_docs/tests.rs
The summary field for the metadata needs to be wrapped in quotes.
=> Doc Gen: Put Summary in Quotes for Metadata

compiler/qsc/src/interpret.rs, compiler/qsc_eval/src/backend.rs, library/src/tests.rs, library/src/tests/intrinsic.rs, library/std/internal.qs
This allows the "unrestricted" configuration to use an optimized `AND` for multi-controlled decomposition that relies on measurement-based adjoint. The existing `PhaseCCX` will still be used for "base" configuration since branching measurement is not allowed there.
Fixes #1137
=> Use optimized AND for decomposition 

resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/system/modeling/fault_tolerance.rs
In some applications, two code parameters cannot simply be compared without taking into account the context of the error correction method and the physical qubit. Therefore, instead of using `Ord` for `ErrorCorrection::Parameter`, I introduce a trait function `ErrorCorrection::code_parameter_cmp`, which compares two code parameters in the context of the error correction itself and the underlying physical qubit.
Further, I simplified the code and made some variable names and comments consistent to not refer to T states in particular, when referring to magic states.
=> Context specific comparison of code parameters in RE

compiler/qsc/src/bin/qsc.rs
I wasted a little time on this error as I could not figure out why the emit was failing for me, so I hope the change makes sense to everyone.
When emitting HIR/QIR fails (e.g. directory permissions or output path is invalid) it is not obvious where it failed because the code swallows the path:
```
Error:   × could not emit QIR
╰─▶ Permission denied (os error 13)
```
or 
```
Error:   × could not emit QIR
╰─▶ No such file or directory (os error 2)
```
With this change the path is also shown:
```
Error:   × could not emit QIR file `./../qir/qir.ll`
╰─▶ No such file or directory (os error 2)
```
This is symmetrical to how the path is already shown for source file errors
```
Error:   × could not read source file `../source/foo.qs`
╰─▶ No such file or directory (os error 2)
```
=> QSC: display the path when emitting HIR/QIR fails

compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/intrinsic/utils.rs
`DumpRegister` output was incorrectly non-deterministic and not ordered because it was coming from a hash map. This fixes that by sorting the reordered labels before returning the vector of results.
=> Fix ordering of output from `DumpRegister`

resource_estimator/src/estimates.rs, resource_estimator/src/estimates/error.rs, resource_estimator/src/estimates/logical_qubit.rs, resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/lib.rs, resource_estimator/src/system/data/report.rs, resource_estimator/src/system/data/result.rs, resource_estimator/src/system/error.rs, resource_estimator/src/system/modeling/fault_tolerance.rs, resource_estimator/src/system/modeling/physical_qubit/tests.rs, resource_estimator/src/system/modeling/tfactory.rs, resource_estimator/src/system/modeling/tfactory/tests.rs, resource_estimator/src/system/optimization/distillation_units_map.rs, resource_estimator/src/system/optimization/distillation_units_map/tests.rs, resource_estimator/src/system/optimization/tfactory_exhaustive.rs, resource_estimator/src/system/tests.rs
This generalizes the `ErrorCorrection` trait to allow encoding multiple logical qubits, thereby enabling the modeling of codes such as LDPC. The change also lead to rename the `LogicalQubit` struct into `LogicalPatch` to account the possibility of multiple logical qubits in the name of the struct.
The system does not change, since all the planar codes modeled in it encode one logical qubit.
=> Allow QEC to encode multiple logical qubits

compiler/qsc_parse/src/lex/raw.rs, compiler/qsc_parse/src/lex/raw/tests.rs
Closes #1179 
Adds extra conditional arguments to check for capital letters in binary, hexadecimal, octal and exp lexing methods.
=> Update lexer to accept captial letters for writing scientific notation

compiler/qsc_passes/src/loop_unification.rs, compiler/qsc_passes/src/loop_unification/tests.rs
During loop unification, new variable expressions are generated into the HIR that have types assigned after type inference. These types need to be correct for later analysis passes. One spot was using the type of the array rather than the hard-coded integer type for the length, creating a type mismatch that could confuse later analysis.
=> Fix generated type in loop unification pass

compiler/qsc_passes/src/replace_qubit_allocation.rs, compiler/qsc_passes/src/replace_qubit_allocation/tests.rs
During the replace qubit allocations pass, calls to qubit allocation operations are generated, but the type of the call expression was always set to `Qubit` regardless of whether the allocation was for a single qubit or multiple qubits.
This change sets the appropriate types for the qubit allocation call expression. `Qubit` for single qubit allocation and `Qubit[]` for multi-qubit allocation.
=> Fix generated type in replace qubit allocation pass

compiler/qsc_frontend/src/typeck/infer.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_hir/src/ty.rs
This relaxes the equality check when unifying two arrow types such that the functors supported by the actual just need to satisfy the expected rather than be exactly equivalent.
Fixes #1241
=> Allow satisfaction checks for functor support

.github/workflows/ci.yml
Now that we have mac-14 runners the performance and reliability seems high enough to start including them in PR builds again. This will help with verifying native code dependencies and build changes that are in flight.
=> Put macOS back into PR builds

compiler/qsc/src/incremental.rs, compiler/qsc/src/interpret.rs, compiler/qsc/src/interpret/tests.rs, compiler/qsc_eval/src/lower.rs, compiler/qsc_frontend/src/incremental.rs, compiler/qsc_passes/src/baseprofck.rs
Fixes #1246
The current base profile result type check was overly broad, because it ran the check on all fragments (not just entry expressions). 
This was because during incremental compilation, entry expressions were added to the AST package as a top-level statement. After that point, the passes could not differentiate between the entry expression and a top-level statement.
We don't _actually_ have to convert the entry expression to a statement - we can just keep the entry expression in the `entry` field in the AST and HIR. So, now, if passes want to apply any special treatment to the entry expression, they have enough information to do so.
=> Make Base Profile result type check specific to entry expressions

compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs
This change updates the type inference logic to have an additional constraint on indexed containers that they must be an array of a new inference type. This is enough to allow further inference to determine the type of the array if items from the array are used in places with inferred types. If any other types support the `HasIndex` class in the future this approach can be revisited.
This fixes an issue where certain code with inferrable types would produce type ambiguous errors, such as [this code](https://microsoft.github.io/qsharp/?code=H4sIAAAAAAAAEz3OMWvDMBAF4F2%2F4oEXe6k6t6R0aMkUiNsOBePhal8TgXVSpBMlhPz3YqX0xu8e785aiwbv5OPCxlqLLas6OSArJeV5teoNXjhPyUV1Qap8HF2GyyB4J87Tgr5BTOGQyEOPpJhI8MUomWdouFXiJ7l6oG8whZnvjJDnHGli7M59IdHi938tF2MA4PlVNJ33wYm2XZUQOdH6CXbkpO3wgDfOZdFhxKUm1llY8Y0NThmbJ3y2 …
=> Update type inference to constrain indexed container as an array

build.py, jupyterlab/qsharp-jupyterlab/__init__.py, jupyterlab/setup.py, pip/qsharp/_fs.py, pip/qsharp/_native.pyi, pip/qsharp/_qsharp.py, pip/qsharp/estimator/__init__.py, pip/qsharp/estimator/_estimator.py, pip/qsharp/utils/_utils.py, pip/tests/test_interpreter.py, pip/tests/test_qsharp.py, samples/estimation/df-chemistry/chemistry.py
```
black .
```
The extensive changes are mostly due to the 2024 updates to [Black](https://black.readthedocs.io/en/stable/change_log.html#highlights).
=> reformat Python files with Black 24.2.0

compiler/qsc/src/interpret/tests.rs, compiler/qsc_eval/src/lower.rs, compiler/qsc_fir/src/assigner.rs, compiler/qsc_hir/src/hir.rs
This fixes the logic on resetting local variable IDs to not lose global scope context, which ensures that variables defined at the global scope before an item defined in the global scope is still valid later in interpreter usage.
Fixes #1250
=> Local variable identifiers are incorrectly overridden in global scope used for fragments

resource_estimator/src/estimates/factory.rs, resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/system/data/report.rs, resource_estimator/src/system/data/result.rs, resource_estimator/src/system/tests.rs
The required logical error rate is not correctly computed for logical patches which have more than one qubit. This PR fixes this. The problem had no impact on our system implementation for resource estimation, since it considers quantum error correction that encodes one logical qubit.
=> Fix required logical qubit error rate for multi-qubit patches

prereqs.py
cmake 3.21 is required to support "-G" "Visual Studio 17 2022", which is needed for mimalloc-sys.
=> Require cmake 3.21 version

vscode/src/extension.ts, vscode/src/format.ts, vscode/src/telemetry.ts, vscode/test/suites/language-service/language-service.test.ts
Enables the feature to format highlighted Q# code, rather than formatting the whole file.
=> Format on Document Range

build.py
This adds the `-v` flag to the pip wheel command in the build script which will help with future diagnosability, expecially in the release pipeline. With this addition, the underlying Rust build for the Python wheel is displayed to console/log so we can confirm which components are being built on which platforms.
=> Use verbose flag when building wheels

jupyterlab/pyproject.toml
It's listed as 'dynamic' in line 27, so adding in line 33 to indicate it should come from the package.json.
=> Add keywords to dynamic fields in pyproject

compiler/qsc_formatter/src/formatter.rs, compiler/qsc_formatter/src/formatter/tests.rs
Added some state to the formatter for the purposes of better handling of delimiters, i.e. `[]`, `()`, `{}`, and type parameter list delimiters `<>`. The formatting of delimited blocks will be determined by whether there is a newline in the whitespace following the open delimiter.
- If there is a newline, then the indentation is increased for the length of the block, and separators, i.e. ',' and ';', require newlines after them, with the closing delimiter having a newline in front of it.
- If there are no newlines, then delimiters have no spacing after the opening and before the closing delimiters, except the brace delimiters which have a singe space instead, and separators require a single space after them.
=> Formatter Indentation and Delimiter Logic

compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/lib.rs, compiler/qsc_rca/tests/qubits.rs
When a qubit is allocated within a dynamic scope, its value kind should be dynamic. This change fixes this and removes the redundant "dynamic qubit allocation" runtime feature.
=> Mark qubit value kind as dynamic when allocated within a dynamic scope

compiler/qsc_formatter/src/formatter/tests.rs, compiler/qsc_parse/src/lex/raw.rs, vscode/src/notebook.ts
This was caused by two different bugs that are addressed in this PR:
- When the input Q# uses `\r\n` line endings, the raw token lexer would only consider the `\n` line ending, resulting in comment tokens with trailing `\r` characters in them.
- In the notebooks, when there were newlines prior to the magic command, the offsets were not mapped correctly.
In order to preserve the magic command in the notebooks from getting removed as leading whitespace in a file (a formatter rule), the magic command is replaced by a comment instead of whitespace.
Fixes #1308
=> Fixes Magic Getting Erased by Format in Notebooks

npm/ux/circuit.tsx, vscode/src/circuit.ts, vscode/src/debugger/session.ts
Fixes issue where the Circuit panel will continue to display the previous circuit, even after it's been updated with a new circuit that fails to render.
Repro:
1. Generate circuit for a valid program, e.g. Entanglement.qs
2. Now generate circuit for a program that doesn't allocate any qubits, e.g. Array.qs
Also a small fix where we force the circuit panel to come to the foreground when invoked through the code lens or at the beginning of a debugging session.
=> Fix issues with circuit panel not refreshing properly

Cargo.lock, compiler/qsc_codegen/src/qir.rs, compiler/qsc_codegen/src/qir/rir_builder.rs, compiler/qsc_codegen/src/qir/tests.rs, compiler/qsc_rir/Cargo.toml, compiler/qsc_rir/src/lib.rs, compiler/qsc_rir/src/rir.rs, compiler/qsc_rir/src/utils.rs
This change upgrades RIR -> QIR to support basic branching on measurement results via `Jump` and `Branch` instructions. This does not include any support for mutable variables.
=> Codegen for basic branching on measurement

npm/ux/circuit.tsx, npm/ux/data.ts, npm/ux/index.ts, vscode/package.json, vscode/src/circuit.ts, vscode/src/debugger/activate.ts, vscode/src/debugger/session.ts, vscode/src/webview/webview.tsx
More UX improvements and an attempt to be more helpful with known error conditions.
=> Remove debug with circuit menu item; more helpful handling for result comparison error

compiler/qsc_eval/src/backend.rs
This change implements defaults that panic for most of the functions in the backend trait. 
**Note on the motivation for this change**: a default backend trait will be used in partial evaluation to validate that no quantum operations are simulated.
=> Implement defaults for all functions in the `Backend` trait

compiler/qsc_codegen/src/lib.rs, compiler/qsc_codegen/src/qir.rs, compiler/qsc_codegen/src/qir/tests.rs, compiler/qsc_codegen/src/rir_passes.rs, compiler/qsc_codegen/src/rir_passes/defer_meas.rs, compiler/qsc_codegen/src/rir_passes/defer_meas/tests.rs, compiler/qsc_codegen/src/rir_passes/unreachable_code_check.rs, compiler/qsc_codegen/src/rir_passes/unreachable_code_check/tests.rs, compiler/qsc_codegen/src/test_utils/rir_builder.rs, compiler/qsc_rir/src/rir.rs
This change introduces two RIR -> RIR passes: the first that defers measurements within a block and a second that is a wrapper on a set of unreachable code checks. 
Deferring of measurements updates the RIR and preserves relative ordering of all instructions, leaving the block in the format of:
1. Operations
2. Measurements and readout
3. Output recording
4. Block terminator
For Base Profile programs where the whole program is a single block, this performs whole program measurement deferral. For programs with more complex control flow, this ensures that measurements appear at the end of the block in a way that could eventually support quantum logic separation.
The unreachable code pass does not modify the RIR, instead acting as a way to verify that RIR is well-formed and panicking on any …
=> RIR defer measurements and unreachable code passes

compiler/qsc/benches/large.rs, compiler/qsc/benches/library.rs
This change updates the benches in a few ways:
- Include core library in library compilation bench
- Don't include core and stdlib in large file compilation so only compilation of the user code is measured.
- Introduce new bench for interpreter compilation of core + std + large file, which includes lowering to FIR in preparation for evalutation.
=> Refactor benches, add interpreter bench

compiler/qsc_data_structures/src/index_map.rs, compiler/qsc_rir/src/builder.rs, compiler/qsc_rir/src/passes.rs, compiler/qsc_rir/src/passes/defer_meas.rs, compiler/qsc_rir/src/passes/reindex_qubits.rs, compiler/qsc_rir/src/passes/reindex_qubits/tests.rs, compiler/qsc_rir/src/rir.rs
This pass reindexes qubits after measurement or reset, ensuring there is no qubit reuse in the program.
=> RIR qubit reindex pass

compiler/qsc_rir/src/passes.rs, compiler/qsc_rir/src/passes/remap_block_ids.rs, compiler/qsc_rir/src/passes/remap_block_ids/tests.rs, compiler/qsc_rir/src/passes/unreachable_code_check/tests.rs, compiler/qsc_rir/src/utils.rs
This introduces a pass on RIR that takes the entry callable and remaps the block IDs such that they are sequentially ordered with a well-known pattern. This enables more efficient checks for later analysis passes.
=> RIR remap block id pass

compiler/qsc_rir/src/passes.rs, compiler/qsc_rir/src/passes/build_dominator_graph.rs, compiler/qsc_rir/src/passes/build_dominator_graph/tests.rs, compiler/qsc_rir/src/utils.rs
This introduces an RIR pass that builds the dominator graph for program, which will be used by later passes for checking validity of SSA and generating required phi nodes.
=> RIR dominator graph pass

compiler/qsc_rca/src/core.rs, compiler/qsc_rca/tests/assigns.rs
=> Fix to RCA panic when assigning call result to tuple

compiler/qsc_rir/src/builder.rs, compiler/qsc_rir/src/passes.rs, compiler/qsc_rir/src/passes/build_dominator_graph.rs, compiler/qsc_rir/src/passes/build_dominator_graph/tests.rs, compiler/qsc_rir/src/passes/ssa_check.rs, compiler/qsc_rir/src/passes/ssa_check/tests.rs, compiler/qsc_rir/src/passes/unreachable_code_check/tests.rs, compiler/qsc_rir/src/rir.rs, compiler/qsc_rir/src/utils.rs
This pass checks that the RIR is in Single Static Assignment (SSA) form. The check verifies that each variable is assigned exactly once before it is used, and that phi nodes are used correctly.
The change also updates how successors are calculated for branch instructions that have constant conditions, and updates the tests that used constant conditions to use dynamic bool values instead.
=> RIR SSA check pass

compiler/qsc_rir/src/builder.rs, compiler/qsc_rir/src/passes/build_dominator_graph/tests.rs, compiler/qsc_rir/src/passes/defer_meas/tests.rs, compiler/qsc_rir/src/passes/remap_block_ids/tests.rs, compiler/qsc_rir/src/passes/ssa_check.rs, compiler/qsc_rir/src/passes/ssa_check/tests.rs, compiler/qsc_rir/src/passes/unreachable_code_check/tests.rs, compiler/qsc_rir/src/rir.rs, compiler/qsc_rir/src/utils.rs
Since branching on literal values is disallowed by dead code checks and should have been simplified by RIR, this change updates `Instruction::Branch` to only have a `Variable` for its condition rather than an operand.
=> Disallow branching on literal in RIR

compiler/qsc_codegen/src/qir.rs, compiler/qsc_rir/src/passes.rs, compiler/qsc_rir/src/passes/remap_block_ids.rs, compiler/qsc_rir/src/passes/remap_block_ids/tests.rs, compiler/qsc_rir/src/passes/ssa_check.rs, compiler/qsc_rir/src/passes/ssa_check/tests.rs, compiler/qsc_rir/src/passes/ssa_transform.rs, compiler/qsc_rir/src/passes/ssa_transform/tests.rs, compiler/qsc_rir/src/rir.rs, compiler/qsc_rir/src/utils.rs
This introduces the transformation pass that removes `Store` instructions in favor of `Phi` instructions and propagates variable values through the program to achieve single static assignment form.
The change also includes wrapper functions `check_and_transform` and `defer_quantum_measurements` at the top level of the passes module to handle invoking the passes in the expected order.
=> RIR SSA transformation pass

katas/content/single_qubit_gates/Common.qs, katas/content/single_qubit_gates/amplitude_change/Placeholder.qs, katas/content/single_qubit_gates/amplitude_change/Solution.qs, katas/content/single_qubit_gates/amplitude_change/Verification.qs, katas/content/single_qubit_gates/amplitude_change/index.md, katas/content/single_qubit_gates/amplitude_change/solution.md, katas/content/single_qubit_gates/basis_change/Placeholder.qs, katas/content/single_qubit_gates/basis_change/Solution.qs, katas/content/single_qubit_gates/basis_change/Verification.qs, katas/content/single_qubit_gates/basis_change/index.md, katas/content/single_qubit_gates/basis_change/solution.md, katas/content/single_qubit_gates/index.md, katas/content/single_qubit_gates/sign_flip/Placeholder.qs, katas/content/single_qubit_gates/sign_flip/Solution.qs, katas/content/single_qubit_gates/sign_flip/Verification.qs, katas/content/single_qubit_gates/sign_flip/index.md, katas/content/single_qubit_gates/sign_flip/solution.md
Add amplitude_change task, basis_change task, sign_flip task, Common.qs file to Single-Qubit Gates kata.
=> Add sign flip, basis change, amplitude change tasks to Single-Qubit Gates kata

vscode/src/extension.ts
This PR enables sending document-updates to a given project documents when its manifest is edited and saved.
https://github.com/microsoft/qsharp/assets/156957451/9d528103-97f3-4a53-858b-0b05b4b2b707
=> Update language service when manifest is saved. (Closes #1284)

compiler/qsc_passes/src/entry_point.rs, compiler/qsc_passes/src/entry_point/tests.rs
Use the span of the entry-point operation name instead of the span of the whole entry-point operation as the span of the entry-point expression.
The purpose of this is to keep the red squiggles focused when an error in the entry-point expression is reported.
=> Make the span of the entry-point expression just the span of name of the entry-point operation

Cargo.lock, Cargo.toml, compiler/qsc_codegen/Cargo.toml, compiler/qsc_codegen/src/lib.rs, compiler/qsc_codegen/src/qsharp.rs, compiler/qsc_codegen/src/qsharp/spec_decls.rs, compiler/qsc_codegen/src/qsharp/test_utils.rs, compiler/qsc_codegen/src/qsharp/tests.rs
This PR uses the formatter and a new code gen function to turn a parsed AST into the equivalent Q#. While the AST is a 1:1 representation of the code, it isn't exactly what is in the code. We don't keep number suffixes, scientific notation, readability separators, etc.
The test compile the sample Q#, generating new Q# from the AST and getting a despanned AST package. It then feeds the new Q# back into the compiler and repeats getting Q# and a despanned AST.
We verify that the Q# generated from the original and the Q# that had been generated from the original, match. This verifies that the original code and the output both generate the same output. This is not enough as they may change the semantics.
We then compare the despanned AST from the original compilation to the despanned AST from …
=> Add Q# code generation from AST.

compiler/qsc/src/interpret/tests.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/management.rs, compiler/qsc_partial_eval/tests/qubits.rs, compiler/qsc_partial_eval/tests/results.rs, pip/tests/test_interpreter.py
This change updates the program generated by partial eval to set the qubit and result counts to non-zero values. This allows later passes to read and possibly update these values so they are correct for QIR codegen.
=> Set qubit and result counts in partial eval output

compiler/qsc/src/interpret/tests.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_partial_eval/src/evaluation_context.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/branching.rs, compiler/qsc_partial_eval/tests/classical_args.rs, compiler/qsc_partial_eval/tests/dynamic_vars.rs, compiler/qsc_partial_eval/tests/intrinsics.rs, compiler/qsc_partial_eval/tests/loops.rs, compiler/qsc_partial_eval/tests/misc.rs, compiler/qsc_partial_eval/tests/output_recording.rs, compiler/qsc_partial_eval/tests/qubits.rs, compiler/qsc_partial_eval/tests/results.rs, compiler/qsc_partial_eval/tests/test_utils.rs, compiler/qsc_passes/src/loop_unification.rs, compiler/qsc_rir/src/builder.rs, compiler/qsc_rir/src/passes/unreachable_code_check.rs, pip/tests/test_interpreter.py
This adds logic to insert output recording calls for recognized types into RIR programs generated by partial evaluation.
=> Partial Evaluation Output Recording support

language_service/src/completion.rs, language_service/src/completion/tests.rs
Fix regression in #1310
Bug: 
Fix:
=> Fix completion auto-open position in notebook cells

README.md, katas/README.md, playground/README.md
Add instructions about building katas locally by building playground
=> Update READMEs to add details on building playground and katas

compiler/qsc_eval/src/state.rs, compiler/qsc_eval/src/state/tests.rs
`get_latex` -> `write_latex_for_term` -> `write_latex_for_real_number` -> `write_latex_for_decimal_number`
https://miniature-telegram-j4vjv94qqv53pv6r-5555.app.github.dev/
Truncating decimal output for state visualization for katas
This flow doesn't impact any other outputs, like one from Python which shows 4 decimal digits accuracy.
=> Truncate decimal to 4 places in alternate state visualization

npm/qsharp/generate_katas_content.js
Fixes #1423 (and addresses JavaScript type-check errors due to newer language features)
If end of file immediately follows a macro, it is parsed successfully.
Note that macros still need to be followed by a newline or end of file. Trailing whitespace or other following content is still invalid.
=> Allow for lack of trailing newline

playground/src/main.tsx, playground/src/tabs.tsx
Small thing, but wanted to change the order of the playground tabs so that "AST" is before "HIR" when reading left-to-right.
Also drops the unused "Logs" tab.
=> Playground Tabs

katas/content/complex_arithmetic/index.md
Currently Polar Coordinates kata has a note which renders below (note the second paragraph LaTeX). This fixes it.
=> Remove stray $ in kata

katas/content/KatasLibrary.qs, katas/content/deutsch_jozsa/msb_oracle/Verification.qs, katas/content/deutsch_jozsa/parity_oracle/Verification.qs, katas/content/multi_qubit_gates/anti_controlled_gate/Verification.qs, katas/content/multi_qubit_gates/compound_gate/Verification.qs, katas/content/multi_qubit_gates/fredkin_gate/Verification.qs, katas/content/multi_qubit_gates/index.md, katas/content/multi_qubit_gates/preparing_bell_state/index.md, katas/content/multi_qubit_gates/toffoli_gate/Verification.qs, katas/content/oracles/bit_pattern_challenge/Verification.qs, katas/content/oracles/bit_pattern_oracle/Verification.qs, katas/content/oracles/kth_bit_oracle/Verification.qs, katas/content/oracles/marking_oracle_as_phase/Verification.qs, katas/content/oracles/marking_oracle_seven/Verification.qs, katas/content/oracles/or_but_kth_oracle/Verification.qs, katas/content/oracles/or_oracle/Verification.qs, katas/content/oracles/phase_oracle_seven/Verification.qs, katas/content/single_qubit_measurements/index.md
This fixes the issue in ShowQuantumStateComparison: if initialState is non-deterministic, "actual state after applying operation" will always be wildly different from "expected state" because initial states will be different.
=> Replace PrepRandomState with deterministic PrepDemoState

katas/content/complex_arithmetic/cartesian_to_polar/solution.md, katas/content/complex_arithmetic/index.md
- Fix a LaTeX error in Cartesian to Polar Conversion solution.
- Fix a mistake in Polar Coordinates.
Hope that helps! 😊
=> Fix typos in Complex Arithmetic kata

compiler/qsc_eval/src/lib.rs, compiler/qsc_fir/src/fir.rs, compiler/qsc_lowerer/src/lib.rs
This adds new execution graph nodes for pushing and popping variable scopes that are used only while debugging (like statement nodes) so that the evaluator can correctly respond to local variable requests during debugging.
Fixes #1436
=> Track nested scopes during debugging

samples/algorithms/BellState.qs
=> Update BellStates: allocate qubits inside the loop and remove ResetAll

compiler/qsc_passes/src/capabilitiesck.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive.rs, compiler/qsc_passes/src/capabilitiesck/tests_base.rs, compiler/qsc_passes/src/capabilitiesck/tests_common.rs, compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/lib.rs
This change adds new runtime feature flags for use of specific types in output from the entry expression/entry point that RCA can annotate a program with. This allows the later check pass to verify that the code will use types in output recording that are supported for the given target. For example, a target that does not support dynamic integers cannot accomodate recoding output with integer values, even if they are static.
=> Include return type of entry point in RCA check

wasm/src/lib.rs
=> Allow generating circuits for operations despite no entrypoint error

compiler/qsc_passes/src/capabilitiesck/tests_adaptive.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive_plus_integers.rs, compiler/qsc_passes/src/capabilitiesck/tests_base.rs, compiler/qsc_passes/src/capabilitiesck/tests_common.rs, compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/lib.rs, compiler/qsc_rca/tests/arrays.rs, compiler/qsc_rca/tests/cycles.rs, compiler/qsc_rca/tests/intrinsics.rs
This change updates the assumptions in RCA to be less restrictive on assuming the dynamic size of arrays. Before, generating the `ValueKind` for arrays would always assume both dynamic content and dynamic size, which could cause failures in checks when, for example, a tuple of static sized arrays is returned from the entry point. Instead, we rely on the propagation of the runtime feature flags to track whether a dynamically sized array is used. This is a precursor to later simplifying the `QuantumProperties` struct by removing `ValueKind` in favor of just tracking dynamic vs static.
=> Update RCA handling of array dynamism

language_service/src/compilation.rs, language_service/src/state/tests.rs
Lints were being generated twice for `qsharp` files. This PR fixes that issue. It also changes the order of the passes, now the linter-passes happen after the fir-passes.
=> Fix duplicated lints

samples/algorithms/Grover.qs
Currently, the function CalculateOptimalIterations in Grover.qs fails for values for `nQubits` larger than 63 (in fact, it computes a wrong value for the case `nQubits == 63`).
This change fixes the computation of iterations for 63 and extends it for larger values.
=> Extend domain for CalculateOptimalIterations in Grover.qs

katas/content/single_qubit_gates/prepare_rotated_state/index.md, katas/content/single_qubit_gates/prepare_rotated_state/solution.md
Noticed a couple of links were out of date.
=> Fix links to documentation in single qubit kata

watch.mjs
```
Error: spawn EINVAL
at ChildProcess.spawn (node:internal/child_process:421:11)
at spawn (node:child_process:761:9)
at runWatcher (file:///C:/Users/manvi/Documents/qsharp/watch.mjs:108:22)
at file:///C:/Users/manvi/Documents/qsharp/watch.mjs:121:1
at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
at async loadESM (node:internal/process/esm_loader:28:7)
at async handleMainPromise (node:internal/modules/run_main:113:12) {
errno: -4071,
code: 'EINVAL',
syscall: 'spawn'
}
```
As per https://github.com/nodejs/node/issues/52554#issuecomment-2060026269, we should set `{shell: true}` because
spawning .cmd files is blocked.
`const npmCmd = isWin ? "npm.cmd" : "npm";`
- Watch is working on Windows after my …
=> [Node Watch] Fix node watch error windows

library/std/internal.qs
This simplifies the implementation of the internal operation `EntangleForJointMeasure` to avoid needing to use the controlled functor and instead just call the underlying single control intrinsics.
=> Optimize `EntangleForJointMeasure`

resource_estimator/src/estimates/error.rs, resource_estimator/src/estimates/factory/dispatch.rs, resource_estimator/src/estimates/factory/empty.rs, resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/system.rs, resource_estimator/src/system/optimization.rs, resource_estimator/src/system/optimization/tfactory_exhaustive.rs, resource_estimator/src/system/tests.rs
Currently, the factory builder API returns a vector of factories for space-time evaluation. However, returning no factory may mean that the algorithm was too fast, and the optimizer will continue to search for some. But there are some cases in which no factory can be found given the input parameters, no matter of the duration of the algorithm.
This PR changes the API to allow to indicate if no magic factories can be computed by returning `Option<Vec<...>>` instead of `Vec<...>`.
=> Handle impossible factories in RE API

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/val.rs, compiler/qsc_partial_eval/src/evaluation_context.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/arrays.rs, compiler/qsc_partial_eval/tests/assigns.rs, compiler/qsc_partial_eval/tests/bindings.rs, compiler/qsc_partial_eval/tests/classical_args.rs, compiler/qsc_partial_eval/tests/loops.rs, compiler/qsc_partial_eval/tests/misc.rs, compiler/qsc_partial_eval/tests/qubits.rs, compiler/qsc_partial_eval/tests/returns.rs
This change adds support in partial evaluation for the following expressions:
- Assignment.
- Array repeat.
- Array in-place concatenation.
- Array in-place update of value at index.
- Array access to value at index.
=> Partial evaluation support for assignment expressions and multiple array related expressions

compiler/qsc_eval/src/lib.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/calls.rs
This adds support for closures with bound local variables in partial evaluation so that they work for QIR codegen. This helps with generating base profile compliant programs with the new QIR codegen.
=> Support closures in partial evaluation

watch.mjs
Previously, katas and samples in playground didnt change as a result of changes in katas and samples directory. Hence I am following a similar pattern to the rust builds. 
Playground gets updated during local development.
@tcNickolas , @minestarks could you please look into this small PR.
=> [Playground][Watch] Reload katas and samples while local development

compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/operators.rs, compiler/qsc_partial_eval/tests/returns.rs
This change implements support in partial evaluation for unary operator expressions (leading positive, leading negative, bitwise not and logical not).
=> Partial evaluation support for unary operator expressions

compiler/qsc_circuit/src/circuit.rs, compiler/qsc_doc_gen/src/display.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_rca/src/common.rs, resource_estimator/src/system/error.rs, resource_estimator/src/system/modeling/tfactory.rs, resource_estimator/src/system/optimization/tfactory_exhaustive.rs, wasm/src/lib.rs
This fixes the warnings that are new or newly detected as of Clippy 1.78. We will follow up with a prereqs, CI, and release pipeline update once the toolchain is available in all build environments.
=> Fix new warnings in Clippy 1.78

playground/src/docs.tsx
Fixes a playground issue with headings in the docs. Needed another line break after the inline HTML.
=> Added newline after inline html

vscode/src/circuit.ts
This issue was found by CodeQL (thanks to @idavis for setting this up and raising the alert). `replace` with a string argument only replaces the first occurrence of `\n`.
=> Fix incomplete string escape in circuit.ts

katas/content/distinguishing_states/zero_one/solution.md, katas/content/distinguishing_unitaries/Common.qs, katas/content/distinguishing_unitaries/i_x/Placeholder.qs, katas/content/distinguishing_unitaries/i_x/Solution.qs, katas/content/distinguishing_unitaries/i_x/Verification.qs, katas/content/distinguishing_unitaries/i_x/index.md, katas/content/distinguishing_unitaries/i_x/solution.md, katas/content/distinguishing_unitaries/index.md, katas/content/index.json
Testing harness doesn't enforce limitation on the number of unitary calls, but I still pass that parameter to simplify implementing this limitation later
=> Distinguishing Unitaries kata: add first task

library/std/arrays.qs, library/std/convert.qs
For targets with adaptive profile plus integer support, the `IntAsBoolArray` function should work with a constant number of bits. However, the presence of a call to `Fact` with an interpolated string causes it to require dynamic string support. Simplifying the assert message avoids this requirement.
=> Avoid dynamic string in `IntAsBoolArray`

playground/README.md, watch.mjs
- Update comments in `watch.mjs` script after https://github.com/microsoft/qsharp/pull/1487
- Change relative path to `python ./build.py` for people on linux. This would be convenient for people who use codespaces :-)
=> [Node Watch] [Playground] Minor update to docs

compiler/qsc_rir/src/passes/ssa_transform.rs, compiler/qsc_rir/src/passes/ssa_transform/tests.rs
This fixes a panic in SSA that results from variable mapping updates not propagating to a block that has a single predecesor. This is corrected by treating that single predecessor block variable map as the update map for the current block during the transformation step.
=> Fix SSA panic due to unpropagated variable mapping

compiler/qsc/src/codegen/tests.rs, compiler/qsc_partial_eval/tests/test_utils.rs, compiler/qsc_rir/src/passes/reindex_qubits.rs, compiler/qsc_rir/src/passes/ssa_transform.rs, compiler/qsc_rir/src/passes/ssa_transform/tests.rs, compiler/qsc_rir/src/passes/type_check.rs, compiler/qsc_rir/src/rir.rs, compiler/qsc_rir/src/utils.rs
This fixes multiple bugs in RIR transformations:
- Updates variable remapping logic during SSA pass to check whether the proposed replacement itself has a pending remap, fixing scenario where mutable variables are mapped to other mutable variables.
- Includes variables created by `Store` instructions in the count for identifying highest variable id to use for inserted phi-nodes, fixing issues where a phi variable may overlap with an existing remapped mutable variable.
- Avoids wrapping subtraction in qubit remapping mass when there are no qubits in the program.
- Fixes type check pass to validate that comparison instruction produces a Boolean value rather than the same value as arguments.
This change adds some new test cases and expands test coverage significatly by running all programs …
=> Fix RIR transform bugs

compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/calls.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive_plus_integers.rs, compiler/qsc_passes/src/capabilitiesck/tests_base.rs, compiler/qsc_rca/src/common.rs, compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/cycle_detection.rs, compiler/qsc_rca/src/errors.rs, compiler/qsc_rca/src/lib.rs, compiler/qsc_rca/tests/callables.rs, compiler/qsc_rca/tests/calls.rs
This change adds full support for analysis of closures for runtime capabilities and calls when the callee expression is known to resolve to a bound closure. This allows analysis to include captured variables as well.
=> Support closures in RCA

compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/calls.rs, compiler/qsc_rca/src/applications.rs, compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/lib.rs, compiler/qsc_rca/src/scaffolding.rs
The check for the dynamism of the return from unresolved callees incorrectly ended up applying to calls where the flag had propagated from another call site, including the entry point callable itself. This change introduces new infra to track the call expression that introduced the flag as opposed to all calls the flag had propagated to, which keeps the desired protection but avoids rejecting other call expressions.
=> Fix for logic based on `CallToUnresolvedCallee` flag

samples/algorithms/BernsteinVazirani.qs, samples/algorithms/BernsteinVaziraniNISQ.qs, samples/algorithms/HiddenShift.qs, samples/algorithms/HiddenShiftNISQ.qs
The Bernstein-Vazirani and Hidden Shift samples both used a pattern that is not well supported by RCA, specifically calling `ForEach(MResetZ, qubits)` to perform measurement on each qubit in an array. Passing a callable that produces a dynamic value makes static analysis very challenging, so instead we can update these to use the equivalent `MResetEachZ` operation. This allows the samples to work well with analysis and produce QIR for both base and adaptive profile.
=> Fix use of `ForEach` in samples for compatibility

compiler/qsc_partial_eval/tests/misc.rs, compiler/qsc_rir/src/passes/remap_block_ids.rs, compiler/qsc_rir/src/passes/ssa_transform.rs, compiler/qsc_rir/src/passes/ssa_transform/tests.rs
This fixes two RIR transformation bugs:
- Avoid revisiting same nodes back to back in node remapping pass, which can cause exponential increase in memory usage for programs with large loops containing nested branching.
- Use variable map for operands in phi node arguments to avoid orphaned variable when that variable comes from a store of another stored variable across branches.
=> Fix RIR transform for large unrolled loops, chained stores across branches

vscode/package.json, vscode/src/config.ts, vscode/src/extension.ts, vscode/src/statusbar.ts
This groups QIR settings together, updates the setting name and description to be a little more helpful, and uses markdown to be able to provide a link to our wiki for QIR.
The new settings appear as below.
=> Tweak the QIR settings

Cargo.lock
This PR should remove the following lines from the build output:
```
warning: mimalloc-sys@0.0.0: xcrun: error: unable to lookup item 'PlatformVersion' from command line tools installation
warning: mimalloc-sys@0.0.0: xcrun: error: unable to lookup item 'PlatformVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```
=> Update cc crate to remove osx build warnings

compiler/qsc_partial_eval/tests/bindings.rs, compiler/qsc_rir/src/passes/ssa_transform.rs
This fixes an issue where a mutable variable A used only in one scope and not across any others is set to a different mutable variable B that spans multiple scopes, including scopes that are not dominated by variable B. Variables like B do not need phi nodes as they are assumed to be unused in later blocks, and any actual usage in later blocks will be caught by the SSA check pass by using the dominator tree.
=> Fix panic when creating unneeded Phi node

compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/misc.rs, compiler/qsc_rir/src/passes/remap_block_ids.rs
This change fixes another issue in block id remapping in RIR that can lead to degenerate performance cases. The corresponding test case is updated to exercise deeper nesting and verify the fix.
This also updates the error string used for dynamic values encountered by partial evaluation based on feedback.
=> Additional RIR block remapping, Error string updates

compiler/qsc/src/interpret/tests.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_fir/src/fir.rs, compiler/qsc_lowerer/src/lib.rs
Changes introduced in #1442 to enable debugger tracking of variable scopes caused a bug if a program used callables with early returns, namely those returns would not pop any added scopes and later execution would read/write the wrong variable states. This fixes the issue by introducing a debug-only return node that triggers a frame leave handling in the environment. This needs to be debug only because it should not be used during partial evaluation.
=> Fix debugger scope handling during early returns

library/std/intrinsic.qs
I updated doc comment for Measure and Exp function.
* Moved text from Remarks to Description as it is specific to the function.
* Simplified formula for probability of getting `Zero` as the outcome of measurement.
* Fixed LaTeX.
=> Fixing LaTeX in the doc comment for Measure and Exp

compiler/qsc/README.md, compiler/qsc/src/bin/qsi.rs
This adds a `--debug` flag to qsi that will make it load the interpreter with debug settings. That will make certain testing easier.
=> Add `--debug` flag to qsi for testing

samples/algorithms/ThreeQubitRepetitionCode.qs
Three Qubit Repetition Code sample suitable for adaptive profile.
Based on https://github.com/microsoft/Quantum/blob/main/samples/azure-quantum/three-qubit-repetition-code/ThreeQubitRepetitionCode.qs
=> Three qubit repetition code sample works in Adaptive Profile

compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/output_recording.rs, compiler/qsc_passes/src/capabilitiesck.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive.rs, compiler/qsc_passes/src/capabilitiesck/tests_base.rs, compiler/qsc_passes/src/entry_point.rs, compiler/qsc_passes/src/entry_point/tests.rs, compiler/qsc_rca/src/lib.rs
This fixes minor issues in error spans used when reporting RCA check errors to avoid duplicate errors being reported for generated entry expressions that come from `@EntryPoint` attributed callables in standalone Q# files.
Fixes #1537.
=> Improve error reporting spans in RCA check

samples/algorithms/CatState.qs, samples/algorithms/GHZ.qs
This updates GHZ state and CAT state sample to work in base profile and adaptive profile.
- Removed check for zero state
- updated comments
- Used library functions MResetEachZ() and Rest()
- Made preparation function specific to GHZ in GHZ sample
=> GHZ and CAT samples work in Adaptive and Base Profiles

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/val.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/arrays.rs, compiler/qsc_partial_eval/tests/assigns.rs, compiler/qsc_partial_eval/tests/returns.rs
This change adds support to partial evaluation for array slicing in index expressions, copy expressions and copy & update expressions.
=> Partial evaluation support for array slicing

npm/qsharp/src/browser.ts, vscode/src/circuit.ts, vscode/src/debugger/activate.ts, vscode/src/diagnostics.ts, vscode/src/qirGeneration.ts, vscode/src/webviewPanel.ts, wasm/src/diagnostic.rs, wasm/src/lib.rs, wasm/src/tests.rs
- Defines a struct `IQSharpError` at the WASM boundary to contain full error information from Q# interpreter error calls. Currently this is only used in QIR generation and circuit visualization, but it can and should eventually be wired up for all `ICompiler` methods that can return errors.
- We create a new diagnostic collection (a set of errors to be shown in the Problems view in VS Code) that shows errors from the last run command. These errors persist in the editor, but can be dismissed by the user or when another command is run.
=> Surface partial evaluation errors in VS Code

pip/qsharp/_qsharp.py, pip/tests-qir/test_qir.py, pip/tests/test_qsharp.py
This change adds an optional `target_name` property to `qsharp.init()` where the user can specify the target and have the profile inferred. Right now it just uses some hard-coded logic to decide between "ionq", "rigetti", or "quantinuum" and anything else is treated as unrecognized with a prompt for the user to specify `target_profile` directly.
=> Support target name in Python, remove Adaptive warnings

compiler/qsc_eval/src/intrinsic/utils.rs
This avoids a panic on empty state that can happen when `DumpRegister` is called on an empty state vector, such as when generating a circuit without any underlying quantum simulation.
=> Avoid panic from `DumpRegister` in circuit display

compiler/qsc/src/interpret.rs, compiler/qsc/src/interpret/tests.rs, compiler/qsc_lowerer/src/lib.rs, compiler/qsc_rca/src/core.rs, pip/tests/test_interpreter.py, samples/notebooks/azure_submission.ipynb
This fixes an issue with incremental compilation where an increment with a failure could still have that FIR present in the package during later compilation, making errors "sticky" instead of associated with just the increment. This achieves it by tracking what the most recently lowered additions to the package were and removing them if there were pass failures like those from RCA check.
=> Drop FIR increment if FIR passes fail

npm/qsharp/src/compiler/compiler.ts, vscode/src/webviewPanel.ts, wasm/src/lib.rs, wasm/src/tests.rs
This updates the call to `run` to that is used by the histogram feature to take the current target profile, such that histograms in the VS Code extension correctly compile the code with the configured target.
=> Respect configured target profile for histogram in VS Code

katas/content/qubit/index.md, katas/content/qubit/learn_single_qubit_state/index.md
Review by the docs team. Checklist includes:
- Contractions
- Voice
- Clarity
- Indicate the level of knowledge in the prerequisites
=> Katas UI strings review - The Qubit

npm/qsharp/src/compiler/compiler.ts, vscode/src/webviewPanel.ts, wasm/src/lib.rs
=> Respect target setting for "Estimate" command

compiler/qsc_rca/src/errors.rs, playground/src/editor.tsx, vscode/src/diagnostics.ts, wasm/src/diagnostic.rs
This change adds support for error Uris by hooking the miette error `.url()` to the VS Code and Monaco `target` field. It also updates the wording on RCA check pass errors to use "configured target profile" instead of "current target" for more clarification. A follow up PR can update the error link(s) to point to more specific documentation pages.
In VS Code, the error links show up as a clickable error code:
In Python/Jupyter, the miette visualization is used which puts clickable links next to the error code:
In Monaco (used in the playground) links work like the VS Code version:
=> Support error Uri, update RCA error strings

compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/val.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/loops.rs
This fixes an issue with mutable variables that are static on a first run through a loop and dynamic afterward when they are used in a unary operation. The unary operation needs to be fully evaluated rather than generated into RIR, much the way static binary operations are.
=> Fix RIR panic on value updated during loop

compiler/qsc_data_structures/src/span.rs, language_service/src/code_lens.rs, language_service/src/completion.rs, language_service/src/name_locator.rs, language_service/src/qsc_utils.rs, language_service/src/signature_help.rs
This PR just moves things around. It moves the `span_contains` and `span_touches` methods in `qsc_utils` to `impl Span { ... }`.
=> Move Span methods in qsc_utils to Span impl

vscode/src/qirGeneration.ts
This change adds an infinite progress notification when we generate QIR for both stand-alone and submit to Azure scenarios. The notification includes a cancel button which will terminate the worker and use updated error messages specific to cancellation or timeout. Now that QIR code generation can be gracefully cancelled, the timeout is updated to be 2 minutes rather than the previous 30 seconds.
This looks like:
=> Add notification with cancel to VS Code for QIR code gen

compiler/qsc_rca/src/errors.rs
This updates the error links for the RCA check pass to use unique anchors per-error to give the user more specific guidance.
=> Use error-specific links for RCA check pass errors

compiler/qsc_passes/src/capabilitiesck/tests_adaptive_plus_integers.rs, compiler/qsc_rca/src/lib.rs
This updates the logic for dynamic `Pauli` variables so that they produce an RCA check error even when integer computations are supported. This is consistent with the fact that they are not supported at codegen, as expected.
=> Treat dynamic `Pauli` as requiring `HigherLevelConstructs`

resource_estimator/src/system/modeling/fault_tolerance.rs
The wrong field is read to calculate the physical number of qubits for a QEC scheme.
=> Read correct field in QEC scheme

compiler/qsc_rca/src/core.rs, compiler/qsc_rca/tests/arrays.rs
This fixes a panic that was introduced in #1571, where if the content being used to update an array was a dynamic, non-array value it would panic when trying to aggreate a default array type into a element type. To make sure the update matches the chosen type, generate the `ValueKind` from the matching expression type. Added unit tests for both array and non-array dynamic update types.
=> Fix panic when updating array with dynamic value

compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/intrinsic/utils.rs
This fixes a bug in the way the wave function was produced for calls to `DumpRegister`, specifically because the calculation needs to use the sum of the squares of the normalization of each amplitude rather than just the sum of the normalization value itself. This ensures the amplitudes output by `DumpRegister` correctly sum to 1.
Output before fix:
Output after fix:
=> Fix normalization math in `DumpRegister`

katas/content/distinguishing_states/a_b/Placeholder.qs, katas/content/distinguishing_states/a_b/Solution.qs, katas/content/distinguishing_states/a_b/Verification.qs, katas/content/distinguishing_states/a_b/index.md, katas/content/distinguishing_states/a_b/solution.md, katas/content/distinguishing_states/four_basis_states/Placeholder.qs, katas/content/distinguishing_states/four_basis_states/Solution.qs, katas/content/distinguishing_states/four_basis_states/Verification.qs, katas/content/distinguishing_states/four_basis_states/index.md, katas/content/distinguishing_states/four_basis_states/solution.md, katas/content/distinguishing_states/index.md, katas/content/distinguishing_states/zerozero_oneone/Placeholder.qs, katas/content/distinguishing_states/zerozero_oneone/Solution.qs, katas/content/distinguishing_states/zerozero_oneone/Verification.qs, katas/content/distinguishing_states/zerozero_oneone/index.md, katas/content/distinguishing_states/zerozero_oneone/solution.md
Migrate tasks 1.4, 1.5 & 1.6 from the Measurements workbook to Distinguishing States Kata.
This resolves a part of the [Issue 1185](https://github.com/microsoft/qsharp/issues/1185).
- Added folders a_b, four_basis_states, zerozero_oneone under distinguishing_states
- Added index, placeholder, solution, and verification files
- Updated index file under distinguishing_states to contain the above exercises
=> Migrate tasks 1.4-1.6 from Measurements to Distinguishing States kata

compiler/qsc_passes/src/entry_point.rs, compiler/qsc_passes/src/entry_point/tests.rs, language_service/src/state/tests.rs, npm/qsharp/test/basics.js, wasm/src/tests.rs
This change updates the entry point logic to assume that in the absence of an explicit `@EntryPoint` attributed callable, a unique `Main` is the entry point.
=> When `@EntryPoint` missing assume `Main` is entry

katas/content/multi_qubit_measurements/examples/MultiQubitProbabilities.qs, katas/content/multi_qubit_measurements/index.md
This includes modifying the state used in the first Analyze exercise to match the state in the second exercise, and changing the code example to solve both exercises.
=> Multi-Qubit Measurements: move code example out of details tag

compiler/qsc_linter/src/linter.rs, compiler/qsc_linter/src/linter/ast.rs, compiler/qsc_linter/src/linter/hir.rs, compiler/qsc_linter/src/lints/hir.rs, compiler/qsc_linter/src/tests.rs, language_service/src/protocol.rs, language_service/src/state.rs, language_service/src/state/tests.rs, playground/src/editor.tsx, vscode/src/extension.ts, wasm/src/language_service.rs
The katas contain a lot of placeholder code like this:
```qsharp
operation ZZMeasurement(qs : Qubit[]) : Int {
// Implement your solution here...
return -1;
}
```
And the "operation can be a function instead" lint, while generally helpful, can distract a learner.
In this PR:
- Add the ability to set the lint configuration per language service instance. (Anything in qsharp.json will still override these settings).
- Make needlessOperation "allow" by default (so that we don't need to make a QCOM change)
- Explicitly set needlessOperation to "warn" everywhere but the katas.
=> Disable needless operation lint for Katas

npm/qsharp/package.json, npm/qsharp/ux/estimatesOverview.tsx, npm/qsharp/ux/qsharp-ux.css, npm/qsharp/ux/saveImage.tsx, npm/qsharp/ux/saveImageUtil.tsx, npm/qsharp/ux/scatterChart.tsx, package-lock.json
Submission for Unitary Hack issue: fixes #1063 
This change adds the ability to save the resource estimates diagram locally as a PNG. For this I added a new dependency called `html2canvas` that takes a DOM and renders it to an image. This currently works only on IPython `qsharp-widgets`, could be extended to the VSCode version. 
Additionally we take into account the color theme within VSCode (which is provided in the stylesheet `qsharp-ux.css`) and this is passed in as the background color for rendering. Tested on (dark/light) Modern VSCode themes.
https://github.com/microsoft/qsharp/assets/3744263/898de6d9-fba4-4fea-b729-a3bb698dc51c
~Current issues:~
- ~This button is placeholder, nicer version: https://github.com/microsoft/vscode-notebook-renderers/pull/118~
- ~Saved imaged is slightly …
=> [Unitary Hack] Save Python qsharp-widgets RE output to PNG

playground/src/editor.tsx
Reverts microsoft/qsharp#1628
See https://github.com/microsoft/qsharp/issues/1577#issuecomment-2172459882
=> Revert "Phantom "entry point not found" error in the Playground"

README.md, allocator/mimalloc-sys/src/lib.rs, compiler/qsc_partial_eval/src/evaluation_context.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_rca/src/common.rs, compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/cycle_detection.rs, prereqs.py, resource_estimator/src/counts.rs
=> Add prereqs check and docs for building on mac

compiler/qsc_frontend/src/compile.rs, compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/tests/implicit_namespace.rs
This change adds some simple logic to clean up unsupported characters from file names before they are used as implicit namespace names. It is by no means exhaustive, but at least takes any `-` replaces them with `_`. This will applied for all files, including unsaved ones, so a file saved to disk as `MyCool-File.qs` would become the namespace `MyCool_File` and VS Code's somewhat quirky names for new unsaved file buffers like `untitled:Untitled-1` becomes `Untitled_1`. This allows skipping explicit namespaces in unsaved new files, fixes #1582.
=> Clean unsupported chars from implicit namespace name

compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/tests/intrinsics.rs, compiler/qsc_rca/tests/intrinsics.rs, library/std/random.qs
Adds new `DrawRandomBool` operation that was inspired by [this](https://learn.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.random.drawrandombool) page on the deprecated QDK. This change has the same documentation and functionality as the linked version.
Fixes #1170.
=> New DrawRandomBool operation

vscode/src/qirGeneration.ts, vscode/src/telemetry.ts
This change adds a new property to the `GenerateQirStart` telemetry event to provide data about the selected target profile.
=> Add target profile to QIR generation telemetry event

samples/estimation/df-chemistry/README.md, samples/estimation/df-chemistry/chemistry.py
This adds a program argument `-p` (long `--paramsfile`) to the Python script of the DF chemistry sample to have the option to load one or multiple RE configurations that are stored as objects or arrays in JSON files. If no such argument is specified, the default configuration is used as before.
This addresses the second bullet point in #1115.
=> Option to load custom RE parameters in DF chemistry sample

compiler/qsc_linter/src/lints/hir.rs, compiler/qsc_linter/src/tests.rs
Closes #1661. The lint wasn't recursing if a `Call` was not an operation, therefore, ignoring the arguments of the `Call`.
=> Fix edge case in unitary-hack lint

.ado/publish.yml, prereqs.py
As per description. This should reduce build times slightly, and avoid the wasm-pack failures on aarch64 where it's not needed anyway.
=> Skip prereqs if already run, and skip wasm checks/install if not needed

.ado/publish.yml
I believe the `pr` entry is acting as an implicit filter preventing triggers on merges to main.
=> Removing pr ado entry

katas/README.md, katas/content/complex_arithmetic/index.md, katas/content/deutsch_algo/index.md, katas/content/deutsch_jozsa/index.md, katas/content/distinguishing_states/index.md, katas/content/distinguishing_unitaries/index.md, katas/content/getting_started/index.md, katas/content/key_distribution/index.md, katas/content/linear_algebra/index.md, katas/content/marking_oracles/index.md, katas/content/multi_qubit_gates/index.md, katas/content/multi_qubit_measurements/index.md, katas/content/multi_qubit_systems/index.md, katas/content/oracles/index.md, katas/content/preparing_states/index.md, katas/content/qec_shor/index.md, katas/content/qubit/index.md, katas/content/random_numbers/index.md, katas/content/single_qubit_gates/index.md, katas/content/single_qubit_measurements/index.md, katas/content/superdense_coding/index.md, katas/content/teleportation/index.md, npm/qsharp/generate_katas_content.js
Link to the issue: https://github.com/microsoft/qsharp/issues/1640
The following changes were done:
1. qsDependencies property is no longer processing (generate_katas_content.js)
2. ../KatasLibrary.qs is included as implicit dependency
3. ./Common.qs is included as implicit dependency if present in current kata
4. All qsDependencies properties are removed from index.md's
5. README.md is updated - reference to qsDependencies is removed
Testing done:
1. "Happy path": Windows cmd build: "python ./build.py --wasm --npm --play" - success
Local playground manual testing - no impact (Chrome and Edge)
2. No impact when qsDependencies are present in index.md
3. No impact when qsDependencies are present and empty in index.md
Question: should Ubuntu build be tested?
=> Fix for "Simplify dependencies handling for exercises in katas" #1640

.github/workflows/ci.yml
This change tweaks the CI workflow to run `--cli` and `--samples` in a separate, parallel set of tasks, and the remainder in the existing "Build and test" task.
=> Run unit and samples tests in parallel

.github/workflows/publish-playground.yml
Skip doing a full build and test for the playground, since merge queues protect main.
=> Optimize playground publish task

compiler/qsc/src/interpret/circuit_tests.rs, compiler/qsc_circuit/src/builder.rs
A Toffoli/CCX in Q# code is currently displayed by the circuit generation code as a controlled-controlled-CNOT instead of a controlled-controlled-X.
I tried to add a test for this, but I'm not sure if I added it in the right place.
Ran `cargo test` and `pytest` (including the integration tests dependent on qir-runner and pyqir)
Also manually tested with this script:
```python
import qsharp
qsharp.eval('''
open Microsoft.Quantum.Arrays;
operation Example() : Result[] {
use q = Qubit[3];
ApplyToEach(X, Most(q));
CCNOT(q[0], q[1], q[2]);
MResetEachZ(q)
}
''')
print(qsharp.circuit('Example()'))
```
which originally printed out:
```
q_0    ── X ──── ● ──── M ─── |0〉 ─ …
```
=> Fix display of CCX in a Circuit

compiler/qsc_formatter/src/formatter.rs, compiler/qsc_formatter/src/formatter/tests.rs
This is one of the changes required for the imports/exports feature work, and this is particularly important for the standard library, which will make extensive use of long export lists and needs to be formatted well.
This PR adds a new context, similar to the existing open/close delim contexts, that is defined by `import` or `export`...`;`. 
If there is a newline after the `import` or `export` keyword, then we format with newlines. Otherwise, puts it all on one line. See the tests for examples.
before:
```qsharp
export
Foo,
Bar,
Baz;
```
after:
```qsharp
export
Foo,
Bar,
Baz;
```
OR, in single-line mode,
```qsharp
export Foo, Bar, Baz;
```
=> support imports and exports in the formatter

Cargo.lock, Cargo.toml
This includes the latest bug fixes and perf improvements.
=> Update to v0.7.4 of sparse simulator

compiler/qsc_frontend/src/typeck/infer.rs, compiler/qsc_frontend/src/typeck/tests.rs
The types listed for the error messages when assigning the wrong type to a struct field during construction were reversed.
This fixes that issue by swapping "actual" and "expected" the types.
=> Reverse types in error message for struct field assign.

vscode/src/programConfig.ts
The additional check for the ".qs" extension in the program config prevented using single file, unsaved buffers with language mode set to Q# in run and debug. Removing this fixes the issue.
=> Allow the running of unsaved files

pip/qsharp/_ipython.py, pip/qsharp/_qsharp.py
This change adds some workarounds that help with accurately reporting timing and avoiding output buffering when running either `%%qsharp` cell magic or `qsharp.eval` (and similar calls) in Python cells.
Fixes #1557
=> Workarounds for IPython cell timing and output buffering

language_service/src/hover.rs, language_service/src/hover/tests.rs
There was an assumption baked into the hover support that locals will always come from a callable scope, but in notebooks they can come from fragments with top-level statements. This avoids the panic by treating the callable name as optional until it is required for display.
=> Fix panic in hover on local variables of notebook cell

vscode/src/debugger/activate.ts
The Run menu options for "Start Debugging" and "Run without Debugging" were not working, in part to how the validation checking for the presence of a launch.json. This reverses the if-statement and drops the else condition to get recognition of single file scenarios without launch.json. Confirmed via manual testing.
=> Enable Run menu in VS Code

compiler/qsc_project/src/project.rs, language_service/src/code_lens.rs, language_service/src/compilation.rs, language_service/src/completion.rs, language_service/src/lib.rs, language_service/src/protocol.rs, language_service/src/state.rs, language_service/src/state/tests.rs, language_service/src/test_utils.rs, pip/qsharp/_qsharp.py, wasm/src/language_service.rs
This updates the compilation logic for the language service when the active document is a notebook to include any specificed project root folder such that dependencies are correctly resolved. This avoids spurious error squiggles on items that come from dependencies and even enables go to definition and hover for those items.
=> Languages Service loads project and dependencies in Notebooks

language_service/src/definition/tests.rs, language_service/src/hover/tests.rs, language_service/src/name_locator.rs, language_service/src/qsc_utils.rs, language_service/src/references.rs, language_service/src/references/tests.rs, language_service/src/rename.rs
Updates the Language Server to allow features to work properly for top-level expressions outside of callables for the notebook experience.
Related to: #1714 
Fixes: #1718
=> Language Server Features for Top-Level Expressions in Notebooks

samples/algorithms/DotProductViaPhaseEstimation.qs, samples/algorithms/QuantumHelloWorld.qs, samples/algorithms/RandomBit.qs, samples/language/ArithmeticOperators.qs, samples/language/Array.qs, samples/language/BigInt.qs, samples/language/BitwiseOperators.qs, samples/language/Bool.qs, samples/language/Comments.qs, samples/language/ComparisonOperators.qs, samples/language/ConditionalBranching.qs, samples/language/CopyAndUpdateOperator.qs, samples/language/Double.qs, samples/language/EntryPoint.qs, samples/language/ForLoops.qs, samples/language/Int.qs, samples/language/LambdaExpression.qs, samples/language/LogicalOperators.qs, samples/language/MultiFileProject/src/Main.qs, samples/language/PartialApplication.qs, samples/language/Range.qs, samples/language/ReturnStatement.qs, samples/language/String.qs, samples/language/Ternary.qs, samples/language/Tuple.qs, samples/language/TypeDeclarations.qs, samples/language/Unit.qs, samples/language/Variables.qs, samples/language/WhileLoops.qs
=> Fix needless operation

jupyterlab/package.json, jupyterlab/yarn.lock
There was some overly strict version locking that was causing the dependabot bump in #1730 to fail to build. This loosens the version restriction and updates to compatible versions of many packages (including 'ws' which should resolve the dependabot issue).
=> Fix version conflict for security bump

pip/qsharp/_http.py
Importing from files that have a BOM fails if `decode("utf-8")` is used, but `decode("utf-8-sig"` will work reliably for both BOM and BOM-less text.
=> Fix BOM handling

compiler/qsc/src/interpret.rs, compiler/qsc_frontend/src/incremental.rs, compiler/qsc_passes/src/entry_point.rs, compiler/qsc_passes/src/entry_point/tests.rs, compiler/qsc_passes/src/lib.rs, language_service/src/state.rs, language_service/src/tests.rs, npm/qsharp/test/basics.js, vscode/src/debugger/session.ts
In most places, we already used the `PackageType::Lib` by default, but not in the language service. With more library authoring expected in the future, this tweaks the user experience to avoid errors for missing entry point until the Q# program as run. As part of these changes, the behavior of the entry point check is updated to always provide feedback for other entry point related errors (like duplicates) but only return an error on missing entry point if the compilation is for an executable.
Of note, this does NOT remove the configuration option for `packageType` in the qsharp.json, which we can do as a follow up if needed.
This does update the error string that pops up when failing to run/debug the Q#. If the program is missing an entry point, a more specific error message is returned: …
=> Use `PackageType::Lib` by default

vscode/src/common.ts
This change updates the logic in `isQsharpDocument` to make sure the language service doesn't generate spurious errors from treating the left-hand side of the diff as a Q# file.
=> Avoid spurious errors in Q# git diffs

compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/resolve/tests.rs
We were using our `Display` for `Ident` impl instead of printing the ident contents in this error msg.
=> print out identifier content instead of Ident [n...m] Blah in error message

pip/qsharp/_qsharp.py
This fixes an issue where the project_root would not get normalized before being output in a Jupyter notebook, preventing the language service from understanding relative paths.
=> Fix issue with relative paths in notebook project root handling

compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_frontend/src/typeck/rules.rs
As the title says, this fixes a panic that was causing the language service to go into a bad state. We were assuming that all paths have type schemes, but that's not the case as they can point to namespaces. This should close #1762. Those failures in #1762 were arising from a compilation update worker crashing (due to the aforementioned panic) while holding a lock to the refcell.
=> fix panic in typeck which was causing language service to go into a bad state

language_service/src/compilation.rs
Simple oversight in not including the dependencies when returning the compilation object for the notebook case.
Fixes #1749
=> Auto-inserted `import` in notebooks should include project aliases

compiler/qsc_frontend/src/compile/tests.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/resolve/tests.rs
Exporting a namespace from within itself is meaningless and should be ignored. This allows resolution to work as expected for the case where the namespace name is unique or where the name actually binds to an item within the namespace with the same name.
=> Ignore export of namespace from within itself

vscode/package.json, vscode/src/createProject.ts
Added a context menu when you right click on qsharp.json in explorer, and a command when you have a qsharp.json open, to populate the list of files in qsharp.json from all the .qs files under the src dir.
https://github.com/user-attachments/assets/12414e0a-b865-4231-a136-8df0c46b1193
=> Add populate files command for qsharp.json

vscode/package.json, vscode/src/createProject.ts
On invocation, a list of available projects to reference from the local workspace and GitHub (the GitHub list to be populated as they become available), or just a template for the user to complete. 
On selection, the changes are made to the qsharp.json for the user to review and save.
After invocation the drop-down appears similar to the below:
=> Add a qsharp.json context menu and palette command to add a project reference

compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/resolve/tests.rs
closes #1773 
See unit tests for an example of what is now allowed/disallowed -- we want to allow re-evaluating imports of the same item under the same name to preserve Jupyter cell UX.
=> Allow re-importing the same symbol if and only if the item id is the same

library/qs_source/src/std/canon.qs
The bits and qubits in this operation are not used as controls, so we shouldn't refer to them as such.
(I got this error message when working on a kata, and it took me longer than it should to figure out that it is not coming from any of the controlled gates.)
=> Fix ApplyPauliFromBitString error message

resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/system/tests.rs
A computation to determine the number of T factories was numerically imprecise leading to results in which the constraint was not satisfied.
The computation has been fixed. Also the chemistry RE benchmark has been updated for which this problem has been discovered in the first place. Corresponding test cases for the chemistry RE benchmark are updated accordingly.
=> Fix bug for max_t_factories constraint

katas/content/solving_graph_coloring/Common.qs, katas/content/solving_graph_coloring/color_equality/Placeholder.qs, katas/content/solving_graph_coloring/color_equality/Solution.qs, katas/content/solving_graph_coloring/color_equality/Verification.qs, katas/content/solving_graph_coloring/color_equality/index.md, katas/content/solving_graph_coloring/color_equality/solution.md, katas/content/solving_graph_coloring/index.md, katas/content/solving_graph_coloring/read_coloring/Placeholder.qs, katas/content/solving_graph_coloring/read_coloring/Solution.qs, katas/content/solving_graph_coloring/read_coloring/Verification.qs, katas/content/solving_graph_coloring/read_coloring/index.md, katas/content/solving_graph_coloring/read_coloring/solution.md, katas/content/solving_graph_coloring/vertex_coloring/Placeholder.qs, katas/content/solving_graph_coloring/vertex_coloring/Solution.qs, katas/content/solving_graph_coloring/vertex_coloring/Verification.qs, katas/content/solving_graph_coloring/vertex_coloring/index.md, katas/content/solving_graph_coloring/vertex_coloring/solution.md, katas/content/solving_graph_coloring/vertex_coloring_classical/Placeholder.qs, katas/content/solving_graph_coloring/vertex_coloring_classical/Solution.qs, katas/content/solving_graph_coloring/vertex_coloring_classical/Verification.qs, katas/content/solving_graph_coloring/vertex_coloring_classical/index.md, katas/content/solving_graph_coloring/vertex_coloring_classical/solution.md
I skipped the register initialization task from the original kata, since it was not used in the complete solution, and merged two other intro tasks into their similar, more challenging variants to reduce the total number of tasks.
The next PR will finish the kata, adding part 2 "weak coloring problem" and the e2e demo of Grover's algorithm.
=> Create Graph Coloring kata, part 1: vertex coloring problem

compiler/qsc_project/src/lib.rs, compiler/qsc_project/src/project.rs, language_service/src/state.rs
This is an incremental improvement for viewing GitHub sources that avoids treating them as open documents since they are read-only buffers. In the future, we can do the work to associate them with the existing compilation taht contains those sources so that things like hover and goto-def work, but for now those code paths are user-code specific and need some reworking to handle navigation in a compile unit for a dependency.
=> Avoid errors in read-only GitHub sources

pip/tests/test_interpreter.py
=> Fix unit tests on test_interperter doing `startswith(...) != -1`

katas/content/index.json, katas/content/multi_qubit_systems/index.md, katas/content/solving_graph_coloring/Common.qs, katas/content/solving_graph_coloring/examples/SolvingGraphColoringWithGroverDemo.qs, katas/content/solving_graph_coloring/index.md, katas/content/solving_graph_coloring/vertex_coloring_classical/index.md, katas/content/solving_graph_coloring/weak_coloring/Placeholder.qs, katas/content/solving_graph_coloring/weak_coloring/Solution.qs, katas/content/solving_graph_coloring/weak_coloring/Verification.qs, katas/content/solving_graph_coloring/weak_coloring/index.md, katas/content/solving_graph_coloring/weak_coloring/solution.md, katas/content/solving_graph_coloring/weak_coloring_classical/Placeholder.qs, katas/content/solving_graph_coloring/weak_coloring_classical/Solution.qs, katas/content/solving_graph_coloring/weak_coloring_classical/Verification.qs, katas/content/solving_graph_coloring/weak_coloring_classical/index.md, katas/content/solving_graph_coloring/weak_coloring_classical/solution.md, katas/content/solving_graph_coloring/weak_coloring_one_vertex/Placeholder.qs, katas/content/solving_graph_coloring/weak_coloring_one_vertex/Solution.qs, katas/content/solving_graph_coloring/weak_coloring_one_vertex/Verification.qs, katas/content/solving_graph_coloring/weak_coloring_one_vertex/index.md, katas/content/solving_graph_coloring/weak_coloring_one_vertex/solution.md
This finishes the migration and publishes the kata
=> Migrate Graph Coloring kata, part 2

compiler/qsc/src/packages/tests.rs, compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/tests/implicit_namespace.rs, language_service/src/state/tests.rs
Fixes an issue where implicit namespace parsing would not recover after incomplete items. This is fixed by adding the end-of-file character as a recovery token.
Fixes #1794
=> Implicit Namespace Parsing Recovery

compiler/qsc_ast/src/ast.rs, compiler/qsc_ast/src/visit.rs, compiler/qsc_doc_gen/src/display.rs, compiler/qsc_frontend/src/lower.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/typeck/check.rs, compiler/qsc_frontend/src/typeck/convert.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_hir/src/hir.rs, compiler/qsc_linter/src/linter/ast.rs, compiler/qsc_linter/src/lints/ast.rs, compiler/qsc_parse/src/item.rs, language_service/src/name_locator.rs, language_service/src/references.rs
PR #1805 changed all instances of `for elt in container.iter()` where container was a `&Box<[...]>` to `for elt in &**container`, which is equivalent, to be able to update our build and release pipelines to rust 1.80, you can see the full explanation there.
This is a subsequent PR that changes:
- All instances of `for elt in &**container` to `for elt in container`.
- All instances of `for elt in &*container` to `for elt in &container`.
These changes are due to rust 1.80 implementing `Iterator` for `Box<[...]>` and clippy enforcing a new style of iteration.
=> Update rust version to 1.80 second step

library/std/src/intrinsic.qs
What the Remarks section looked like before:
What the Remarks section looks like now:
Fixes #1429
=> Fixed some broken latex in the Measure doc

katas/content/multi_qubit_measurements/state_modification/Verification.qs
Doing Reset on the first qubit before checking the state of the second qubit can lead to empty solution being judged as correct (with low probability). We have to check the state of the second qubit first and only then reset the first one.
=> Fix test for multi_qubit_measurements/state_modification

compiler/qsc_parse/src/expr.rs, compiler/qsc_parse/src/expr/tests.rs, compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/lib.rs, compiler/qsc_parse/src/prim.rs, compiler/qsc_parse/src/prim/tests.rs, compiler/qsc_parse/src/scan.rs, compiler/qsc_parse/src/stmt.rs, compiler/qsc_parse/src/ty.rs
Given the problems users have faced with non-parenthesized for loop iterators ([like this one](https://stackoverflow.com/questions/78592805/q-sharp-syntax-error-in-quantum-hhl-algorithm)), we wanted to provide some help text for the user in this situation.
Instead of just patching in a fix for precisely this situation, I wanted to use `miette`'s great functionality for composable errors. So, with this change, can now compose any parse error with help text.
I also manually implemented `Debug` for `Error` to omit the help text if it isn't present. This is primarily so this PR doesn't add `None` to every single parser expect test which tests errors. (Happy to revert this and update the tests if desired, but I really don't like spraying the diff with 1k lines of expect-test changes that just …
=> Allow the parser to add contextual help text to errors; Add contextual help text for parenthesized for loops

compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/resolve/tests.rs
=> Enforce globally unique names for callables declared as `SimulatableIntrinsic`

katas/content/phase_estimation/eigenvalues_s/Placeholder.qs, katas/content/phase_estimation/eigenvalues_s/Solution.qs, katas/content/phase_estimation/eigenvalues_s/Verification.qs, katas/content/phase_estimation/eigenvalues_s/index.md, katas/content/phase_estimation/eigenvalues_s/solution.md, katas/content/phase_estimation/eigenvectors_x/Placeholder.qs, katas/content/phase_estimation/eigenvectors_x/Solution.qs, katas/content/phase_estimation/eigenvectors_x/Verification.qs, katas/content/phase_estimation/eigenvectors_x/index.md, katas/content/phase_estimation/eigenvectors_x/solution.md, katas/content/phase_estimation/index.md, katas/content/phase_estimation/state_eigenvector/Placeholder.qs, katas/content/phase_estimation/state_eigenvector/Solution.qs, katas/content/phase_estimation/state_eigenvector/Verification.qs, katas/content/phase_estimation/state_eigenvector/index.md, katas/content/phase_estimation/state_eigenvector/solution.md
* First two exercises match the last two exercises from classic Linear Algebra kata, and follow a similar approach for migrating it to Q#, replacing Python code with a hardcoded exercise
* Third exercise is 1.3 from classic PhaseEstimation kata, rewritten to work with Boolean checks rather than assertions.
Part 2 will include exercises 2.1 and 1.4 from classic PhaseEstimation kata and new (to katas) QPE algorithm theory and demo of its success probability
=> Start migration of Phase Estimation kata

noisy_simulator/src/operation.rs, noisy_simulator/src/operation/tests.rs
When initializing an `Operation`, the first thing we do is transposing the matrices, `nalgebra` panics internally when transposing non-square matrices. This PR moves the transposition operation after the dimensions check to gracefully handle that case and adds a unit test to check for this in the future.
Notes:
1. This bug was introduced in the performance improvement PR.
2. It doesn't affect well-formed programs; it just affects programs using ill-formed Kraus operators.
=> Fix `noisy_simulator` panic when initializing with non-square Kraus matrices

compiler/qsc_frontend/src/typeck/infer.rs, compiler/qsc_frontend/src/typeck/tests.rs
This change fixes a subtle bug in type inference where nested generic callables could finish satisfying constraints without fully resolving one of the generic types. By setting up an equality constraint when binding the inference type it forces the solver to come back to the inference type later and ensure it is resolved. This also required a fix to the type substituion recursion limit check to ensure we don't end up trying to repeatedly unify infinite types.
=> Fix type inference for nested generics

samples/language/ReturnStatement.qs
I did not see this in the samples, and to me it makes sense to have it together with other "return" samples. 
It's quite a significant feature (especially to programmers used to Python 😄)
=> Added a sample function with an implicit return

vscode/src/azure/providerProperties.ts
This change does two things:
- Simplify the way we determine whether a target supports QIR.
- Add a target to the exclusion list in preparation for the next release.
=> Simplify targets logic and prepare exclusion list for next release

pip/qsharp/_qsharp.py, pip/tests/test_qsharp.py
=> Add API to convert StateDump to a dense array of amplitudes

compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, library/src/tests/diagnostics.rs, library/std/src/diagnostics.qs
This introduces qubit count tracking APIs to the Diagnostics namespace that allow Q# code to get counts for how many unique qubits are used during a section of execution. This is useful in katas and auto-grading scenarios to verify that exercise restrictions are being appropriately followed.
Fixes #1155
=> Support qubit count tracking within Q#

vscode/qsharp.schema.json
The schema file was not updated when new lints were added as a part of the newtype/struct rework. This PR updates the schema.
=> Update `qsharp.json.schema` to include latest lints

compiler/qsc_frontend/src/closure.rs, compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_linter/src/tests.rs, compiler/qsc_passes/src/spec_gen/tests.rs
This change gets rid of the default span on lifted lambda names by setting it to the entire lamba. This ends up working well with error and lints that try to underline the lambda, which previously could end up highlighting the first character (sometimes of the wrong file).
Before:
After:
=> Fix spans for lifted lambda idents

compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs
In addition to fixing while-expr, this applies the same fix to for-loop, repeat-loop, and within-block, including unit tests for the desired type inference behavior.
Fixes #1251
=> Blocks in while-expr should enforce `Unit` type

pip/qsharp/noisy_simulator/_noisy_simulator.pyi
Fixes some type hints in the python wrapper for the noisy simulators.
=> Fix type hints in python wrapper for noisy simulator.

playground/src/editor.tsx, playground/src/kata.tsx
Add the edit/run for kata examples.
This PR closes https://github.com/microsoft/qsharp/issues/591
Monaco editor model should have a unique URI (with few exceptions). So, either kata lesson ID or kata exercise ID is provided to the model. The Editor.tsx implementation is replacing "kataExercise" parameter with "kataSection" that contains both lesson.id and exercise.id.
The function parameter "key" is not in use and was removed.
=> Add edit/run for kata examples - issue 591

compiler/qsc_data_structures/src/index_map.rs, compiler/qsc_frontend/src/compile.rs, language_service/src/code_lens/tests.rs, language_service/src/completion.rs, language_service/src/completion/tests.rs, language_service/src/definition/tests.rs, language_service/src/hover/tests.rs, language_service/src/references/tests.rs, language_service/src/rename/tests.rs, language_service/src/signature_help/tests.rs, language_service/src/test_utils.rs
Closes #1860
Currently, we have a separate code path for generating completions for core callables. This code path just hard-codes the callables to
not include any auto-generated imports. This may have been necessary at some point, but it no longer is and it is preventing us from generating
the correct auto-imports for `QIR.Runtime`. We now have a function that generates completions from a package and is aware of if imports are
needed or not, so I just went ahead and used that instead of special casing `Core`.
This PR:
- Uses the standard completion codepath to generate completions for `Core`
- Adds the ability to unit test completions with the real stdlib, not just the fake stdlib
- Adds tests to ensure auto-imports are generated for items that are not already in scope (e.g. …
=> generate auto imports for core callables

vscode/src/common.ts
Much like git diffs with scheme `git`, viewing files surfaced from GitHub Pull Requests that come from a branch not currently checked out produces spurious errors since they are not real files on disk and have extra data in their filenames. This uses the same strategy as in #1754 to avoid them by not loading things with the custom `pr` URI scheme.
=> Skip errors on files with `pr` URI scheme

.github/workflows/bench-reports.yml, .github/workflows/memory_profile.yml, bench.sh, build.py
The benchmark comments have generally been pretty noisy and I think unpopular, especially when iterating on one open PR.
This PR removes the current benchmark commenting functionality and instead runs a once-weekly (Monday morning at midnight) benchmark on `main` and saves the results as JSON. These results can then be easily interpreted by a separate tool that I'm putting together. This will help us catch any performance regressions or trends, but in a once-weekly retrospective report of all merges into main, instead of every single commit. 
The key thing here is that after this PR goes in, we will have a mechanism to retrospect over performance data without having it commented on every commit of every PR.
=> Remove benchmarking comment bot; Run benches weekly and save results as an artifact

vscode/src/debugger/output.ts
Skips prepending "Result: " and json stringify-ing the response from evaluation, since it is already a string.
Error before:
Error after:
Success before:
Success after:
Fixes #1871
=> Simplify display of evaluation results in VS Code

library/signed/src/Comparison.qs
I forgot to export this as a part of the API in the initial PR (#1841). This is needed in the Fixed Point library (#1838).
=> Include CompareGTSI in the Signed math API

Cargo.lock, Cargo.toml, compiler/qsc/Cargo.toml, compiler/qsc_frontend/src/error.rs, pip/Cargo.toml, resource_estimator/Cargo.toml
Closes #1887
Thanks @billti for finding the new `fancy-no-syscall` feature [introduced to `miette` in February](https://github.com/zkat/miette/pull/349). As a result of that change, we can now update to the latest version of `miette` without breaking our WASM builds. Yay!
=> update miette to v7.2.0

Cargo.lock, Cargo.toml, pip/src/fs.rs, pip/src/interpreter.rs, pip/src/noisy_simulator.rs
v0.21 -> 0.22
- no implicit `None` for trailing options, we now explicitly declare it via a macro
- explicit `eq, eq_int` annotations (question: why did we manually implement richcmp before?)
v0.20 -> 0.21
- new `Bound` API with borrowing done in Rust instead of implicitly
- removal of `py` argument in `PyDict::from_sequence`
closes #1886
=> Update pyo3 from v0.20 to v0.22

compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/lib.rs, compiler/qsc_rca/src/tests.rs, compiler/qsc_rca/src/tests/assigns.rs
This change fixes a panic that happens during Runtime Capabilities Analysis (RCA).
The panic happens when the bound value of a tuple, in which at least one element is an array, is updated and the originally bound value is dynamic.
=> Fix to RCA panic when original tuple binding is dynamic

resource_estimator/src/estimates.rs, resource_estimator/src/estimates/error_correction.rs, resource_estimator/src/system.rs, resource_estimator/src/system/modeling/fault_tolerance.rs, resource_estimator/src/system/modeling/fault_tolerance/tests.rs, resource_estimator/src/system/modeling/physical_qubit/tests.rs, resource_estimator/src/system/modeling/tfactory/tests.rs, resource_estimator/src/system/optimization/distillation_units_map/tests.rs, resource_estimator/src/system/optimization/tfactory_exhaustive/tests.rs, resource_estimator/src/system/tests.rs
Provides a generic version for an error correction code that has a code distance, threshold, and exponential error suppression. The system version (with surface code and Floquet code as defaults, and customizable via formula strings) is now implemented based on the generic version. The generic version can also be used in other projects via extensibility API.
=> Generic code with code distance and threshold

resource_estimator/src/system/modeling/physical_qubit.rs, resource_estimator/src/system/modeling/tfactory.rs
To compute the cycle time in physical T factories, we should use the T gate time qubit parameter instead of the measurement time. This change does not affect any experiments with our default models, since they are using the same time for both metrics.
=> Use T gate time for physical factories

resource_estimator/src/estimates.rs, resource_estimator/src/estimates/layout.rs, resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/estimates/physical_estimation/result.rs, resource_estimator/src/system.rs, resource_estimator/src/system/data/report.rs, resource_estimator/src/system/data/result.rs, resource_estimator/src/system/tests.rs
This change allows to serialize the logical post-layout overhead in the resource estimation result provided by the resource estimation API. Note that this was already possible in the system API that has a custom result for the VS Code and Python integration.
The change also simplified the type of the resource estimation result, which now is not any longer generic over the post-layout overhead trait.
=> Serialize logical post-layout overhead in resource estimation result

compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_partial_eval/src/lib.rs, library/src/tests/canon.rs, library/std/src/canon.qs
This change adds one layer of indirection in the library implementation of `Relabel` so that the operation can be adjointable. The adjoint is just a switch of the qubit arrays such that `Adjoint Relabel(current, updated)` is the same as `Relabel(updated, current)`.
=> Support Adjoint of `Relabel`

build.py, compiler/qsc_qasm3/src/compile.rs, compiler/qsc_qasm3/src/lib.rs, compiler/qsc_qasm3/src/tests.rs, compiler/qsc_qasm3/src/tests/declaration.rs, compiler/qsc_qasm3/src/tests/output.rs, compiler/qsc_qasm3/src/tests/sample_circuits/bell_pair.rs, compiler/qsc_qasm3/src/tests/sample_circuits/rgqft_multiplier.rs, compiler/qsc_qasm3/src/tests/statement/include.rs, compiler/qsc_qasm3/src/tests/statement/reset.rs, pip/pyproject.toml, pip/qsharp/_native.pyi, pip/qsharp/interop/qiskit/__init__.py, pip/qsharp/interop/qiskit/backends/backend_base.py, pip/qsharp/interop/qiskit/backends/qsharp_backend.py, pip/qsharp/interop/qiskit/backends/re_backend.py, pip/src/interop.rs, pip/src/interpreter.rs, pip/tests-integration/interop_qiskit/test_qir.py, pip/tests-integration/interop_qiskit/test_qsharp.py, pip/tests-integration/interop_qiskit/test_re.py, pip/tests-integration/interop_qiskit/test_run_sim.py
- Qiskit dep version set in lock step with aqp
- output semantics can be configured on the backends needed for QIR generation. Program type exported as well.
- Program type is separated from name of operation.
- Updating to use walrus operator to simplify logic (supported by Python 3.8+).
- Fixed doc comments
- Fixed Q# code generation for debugging
- RE now uses `compile_qasm_enriching_errors` so that entry points with input vars are rejected.
=> Bug fixes found during bash

compiler/qsc_eval/src/state.rs, compiler/qsc_eval/src/state/tests.rs
* Updated general code so that 0 is recognized in Cartesian form. Also propagated parameter to render 1 explicitly out of inner functions.
* Added function write_latex_for_complex_number for rendering a standalone complex number. It differs from write_latex_for_term in handling of special cases such as 0, 1, -1.
* Changed get_matrix_latex to call this new function. This reduced a number of special cases, so I removed them from get_latex_for_simple_term. Eventually all these special cases should go away.
* Added tests for write_latex_for_complex_number. Also added test for get_matrix_latex to check that rendering hasn't changed in the process.
* The following can still be improved in general case:
* i could be used directly in a fraction. Example: $\frac{1}{2}i$ could be rendered as …
=> Added write_latex_for_complex_number

vscode/package.json
Fix small typo that currently appears in Welcome page for the VS Code extension:
=> Fix typo in vscode extension's package.json

playground/src/editor.tsx
In some cases where the user is typing fast, diagnostic updates (a.k.a. error squiggles) will get dropped. This can happen when the current document version is greater than the version that the diagnostics event pertains to.
I'm removing the version check since it was overkill anyway. As long as the diagnostics updates are received in order, the state should remain consistent.
Repro for future reference:
Interaction between the editor and the language service. Correct behavior:
- user types `Foo` in the editor, document version is updated to 1
- `updateDocument` command with contents `Foo` version=1
- `diagnostics` event with a type error version=1
- user types `(` in the editor, document version is updated to 2
- `updateDocument` command with contents `Foo()`  version=2
- **`diagnostics` …
=> Playground: Fix error squiggle updates getting dropped

resource_estimator/src/system.rs
The type is used by the function `load_protocol_from_specification` which is already public.
=> Add ProtocolSpecification to API

npm/qsharp/ux/circuit.tsx, widgets/src/qsharp_widgets/__init__.py
This change fixes a few quirks of the `Circuit` widget, specifically:
- if the width of the widget is greater than the width of the cell output area, scroll bars are added, and
- setting a custom zoom level by changing the value in the zoom control disables the resize handling so that VS Code doesn't incorrectly trigger a recalculation of the default zoom and undo the manual change.
Confirmed with manual testing that window resizing in VS Code circuit display is still hadled properly.
=> Update circuits widget sizing behavior

compiler/qsc/src/interpret/circuit_tests.rs, compiler/qsc_circuit/src/builder.rs
The logic for returning the count of measurements incorrectly reported every qubit as being measured only once no matter how many times it was measured. This was breaking circuit display for non-base profile programs.
=> Fix bug preventing display of circuits where same qubit measured more than once

jupyterlab/yarn.lock
#1895 was failing for some reason. This updates all the dependencies in the yarn.lock to compatible versions to pick up the latest fixes.
Tested locally and seems to be fine. (Well, as fine as it was before the updates).
=> Update yarn dependencies

library/Registry.md
A basic document that serves the purpose of a package registry, listing all packages we are aware of.
Most information about the package should be on the package page itself, so here we can just list titles, summaries, and links.
=> add Q# package registry document

resource_estimator/examples/basic_logical_counts.rs, resource_estimator/src/estimates.rs, resource_estimator/src/estimates/error_budget.rs, resource_estimator/src/estimates/layout.rs, resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/estimates/physical_estimation/estimate_frontier.rs, resource_estimator/src/estimates/physical_estimation/estimate_without_restrictions.rs, resource_estimator/src/estimates/physical_estimation/result.rs, resource_estimator/src/system.rs, resource_estimator/src/system/data/logical_counts.rs, resource_estimator/src/system/tests.rs
Resource estimation takes as input an error budget. This is a triplet of budget contribution to logical errors, rotation synthesis errors, and magic state distillation errors. The user can either specify each of these three values separately or provide a total value that is uniformly distributed among the three parts. So far, RE does not modify these provided values.
This PR implements a pruning strategy for the error budget that will decrease the budget for logical errors and rotation synthesis errors (without affecting the estimation), while increasing the budget for magic state distillation errors in order to reduce the resources required for factories.
For logical errors, we can reduce the budget by finding the largest value that still leads to the same code parameter (e.g., code …
=> Error budget pruning strategy in resource estimator core

library/fixed_point/qsharp.json, library/signed/qsharp.json
I was just importing FixedPoint and noticed it doesn't work due to a local path dependency. This fixes that, but also updates the refs for other libraries to latest.
Aside:  I can't believe this got checked in with an absolute path on my PC. That's a big L on my part.
=> Use all github dependencies in published libraries

widgets/js/index.tsx
This resolves the issue where when displaying the EstimateDetails widget sometimes there would be an error about the markdown renderer not being set.
=> Set the markdown renderer on load

language_service/src/completion.rs
I upgraded locally and clippy was mad about this line, so I applied the fix.
=> Minor lint fix for Rust 1.81

compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/tests/branching.rs
RCA can categorize an expression as dynamic even if it is in fact purely classical. This can happen in cases where a data structure such an array, tuple or UDT contains a mix of static and dynamic values. In such instances, RCA identifies all the contents of the data structure as dynamic even if some values are static. This causes partial evaluation to generate branch instructions on constant conditions under certain circumstances. This change fixes this issue.
=> Fix to partial evaluation generating branch instructions on constant conditions

vscode/src/debugger/session.ts, wasm/src/debug_service.rs
Instead of showing a single bit zero state, this change makes the debugger quantum state view show a message when no qubits are allocated on the system:
Fixes #1922
=> Show no quantum state when debugging code with no qubits

compiler/qsc_ast/src/ast.rs, compiler/qsc_ast/src/mut_visit.rs, compiler/qsc_ast/src/visit.rs, compiler/qsc_codegen/src/qsharp.rs, compiler/qsc_frontend/src/lower.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_parse/src/completion/word_kinds.rs, compiler/qsc_parse/src/expr.rs, compiler/qsc_parse/src/expr/tests.rs, language_service/src/completion.rs, language_service/src/completion/fields.rs, language_service/src/completion/path_context.rs, language_service/src/completion/tests.rs, language_service/src/name_locator.rs, language_service/src/protocol.rs, language_service/src/references.rs, playground/src/main.tsx, vscode/src/completion.ts, wasm/src/language_service.rs
Builds on #1947 .
Enables:
1. Field access completions, for example:
```qsharp
let x = Complex(1.0, 2.0);
x.| 
```
At the cursor location indicated by `|`, completions should include `Real` since it's a field of `Complex`.
2. Field assignment completions, for example:
```qsharp
struct Foo {
bar: Int
}
new Foo { | }
```
Here, completions should include `Bar`.
=> UDT field completions

compiler/qsc_circuit/src/builder.rs, compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/backend/noise_tests.rs, compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/noise.rs, resource_estimator/src/counts.rs
Added support for parametric Pauli noise to sparce simulator. (px, py, pz) can be provided. Sparse simulator will apply X, Y or Z gates after each gate and before each measurement with corresponding probability.
- This allows for simulation with parametric Pauli noise: bit flip, phase flip, depolarizing, etc.
- For two-qubit gates noise is applied to each qubit.
- Allocation and service functions do not apply noise. Idle (Identity) gate is also noiseless.
- Reset applies noise.
- Added tests.
- Released qubits are no longer checked to be in zero state by consumers of the backend via calling qubit_is_zero. Instead, qubit_release returns Boolean. True indicates, that the release was valid - the qubit was in a zero state in a noiseless simulation. It will always be true in noisy simulations …
=> Added Pauli noise support to sparse simulator

vscode/src/telemetry.ts, vscode/src/webviewPanel.ts
This adds telemetry even when noisy simulation is used in vscode plugin.
=> Telementry event for noisy simulation

compiler/qsc_doc_gen/src/display.rs, compiler/qsc_doc_gen/src/generate_docs.rs, compiler/qsc_fir/src/fir.rs, compiler/qsc_fir/src/ty.rs, compiler/qsc_frontend/src/lower.rs, compiler/qsc_hir/src/hir.rs, compiler/qsc_hir/src/ty.rs, compiler/qsc_lowerer/src/lib.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/cyclic_callables.rs
This PR unifies the implementations of custom measurements and custom resets. It does two things:
- Removes the `CallableKind::Measurement` variant from HIR and FIR.
- Uses the `Attr::Measurement` to identify that a callable is a measurement.
=> Unify implementations of custom measurements and custom resets

compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_parse/src/expr.rs, compiler/qsc_parse/src/item.rs, compiler/qsc_parse/src/item/tests.rs, compiler/qsc_parse/src/prim.rs, compiler/qsc_parse/src/prim/tests.rs, compiler/qsc_parse/src/stmt.rs, compiler/qsc_parse/src/stmt/tests.rs, compiler/qsc_parse/src/ty.rs, language_service/src/completion/tests.rs
1. Callable signatures tolerate a lot more broken syntax now. This allows us to complete type parameters correctly in broken syntax that we commonly see when the user is in the middle of typing:
```qsharp
operation Test<'T>() : () => |
```
```qsharp
operation Test<'T>(x: |)
```
```qsharp
operation Test<'T>() : |
```
```qsharp
operation Test<'T>(x: Std.|) : Unit {}
```
2. Error recovery in notebook cells if a statement can't be parsed. Fixes #1960 and allows completions to work in scenarios like this:
```qsharp
%%qsharp
function Foo() : Unit {}
let x = |  // expect Foo in the list
```
=> More parser error recovery, unlocking completions in more locations

compiler/qsc/src/interpret/tests.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/output.rs, compiler/qsc_eval/src/state.rs, npm/qsharp/src/compiler/common.ts, npm/qsharp/src/compiler/compiler.ts, npm/qsharp/src/compiler/events.ts, npm/qsharp/src/debug-service/debug-service.ts, pip/src/displayable_output.rs, samples_test/src/tests/language.rs, vscode/src/debugger/output.ts, wasm/src/lib.rs
This change updates the display of quantum state when no qubits are allocated to show a message rather than the same output as one qubit in the zero state. This matches the updated debugger behavior. Note that I've tried to ensure this is NOT a breaking change for consumers of the WASM/npm package by extending the data type rather than changing the behavior or contents of existing fields, and verifyied this by leaving the dev playground unchanged and confirming it preserved the old behavior there (playground will be updated in a follow up PR and is tracked by a separate issue).
Fixes #1961
=> `DumpMachine` output in Python and console should be empty with no qubits allocated

playground/src/results.tsx, playground/src/state.tsx
=> `DumpMachine` in playground should display message when no qubits are allocated

language_service/src/completion.rs, language_service/src/completion/ast_context.rs, language_service/src/completion/fields.rs, language_service/src/completion/tests.rs
Disable completions inside attribute arguments, despite what the parser says, since we support either hardcoded values or nothing at all.
examples:
```qsharp
@Config( | ) 
operation Foo() : Unit {}
```
```qsharp
@EntryPoint( | ) 
operation Foo() : Unit {}
```
no completions at this locations.
=> Disable completions in attribute arguments

Cargo.toml
One pattern I use a lot in Rust is `Default::default()` to construct a default instance of a type. However, pedantic clippy settings state that this is unclear. I personally dislike this setting, and actually find `Default::default()` more usable and consistent.
Consistency wise, there's no reason (IMO) for clippy to single out the `Default` trait. We access other trait methods in this way, and clippy has no such rule against other traits. For example, `Into::into()`, or `Display::to_string()`. 
Style wise -- the point of using a language with type inference is that you only have to specify the type _once_, and then subsequent lines of code do not need to redeclare (or "stutter") the type. I will frequently update an underlying data structure, e.g. switching from `HashMap` to `BTreeMap`, …
=> Allow `Default::default()` pattern

language_service/src/completion.rs, language_service/src/completion/tests.rs
Suppress completions inside comments like
```qsharp
import Foo;
// Hello there |
import Bar;
```
=> No completions in comments

Cargo.toml
This PR allows another lint that is on in the *pedantic* profile but not in the default profile.
One pattern I've always used, and enjoyed, is matching across enum variants. This is excessively verbose, typically:
```rust
match my_enum {
ClassConstraint::Exp { .. } => (),
ClassConstraint::Num => (),
ClassConstraint::Eq => ()
}
```
I find that this is too noisy, so I typically would write:
```rust
use ClassConstraint::*;
match my_enum {
Exp { .. } => (), 
Num => (),
Eq => ()
}
```
As this lint is not on by default, this is not a problem in most Rust codebases, only those that enable the `pedantic` clippy profile.
This lint provides a code action to expand the `*` import into an import of all of the variants. I don't like this as much, as it means you still end up stuttering all of the enum …
=> (clippy) Allow enum variant imports

samples/samples.mjs
This just adds the existing Three Qubit Repetition Code sample to the playground (both the VS Code playground and the developer playground).
=> Add three qubit repetition sample to playground

pip/qsharp/_qsharp.py
This change fixes an issue where the workaround introduced in #1712 for timing in Jupyter cells could cause some environments (notably VS Code) to exceed the 500 item limit on displays and prevent other output from being shown.
=> Avoid flooding iPython display

compiler/qsc_eval/src/tests.rs
It used to be that we avoided noise in the evaluator tests during libraries edits by avoiding having spans from the stdlib show up in there, but newer tests include calls to `Std.Intrinsic.I` that need spans updated every time something alphabetically above that operation changes in the stdlib. This change updates the expect call on failure to only verify the error and not the stack frames, as call stacks are already verified in other tests and don't need to be checked here.
=> Skip checking stack frames in evaluator expect tests

compiler/qsc_rca/src/core.rs, compiler/qsc_rca/src/tests/calls.rs
This change fixes an RCA panic that occurs when a tuple input pattern maps to a non-tuple expression.
=> Fix to RCA panic when mapping a tuple input pattern to a non-tuple expression

compiler/qsc/src/interpret/circuit_tests.rs, compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_eval/src/val.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/management.rs, compiler/qsc_partial_eval/src/tests/intrinsics.rs, library/src/tests/diagnostics.rs, library/std/src/Std/Diagnostics.qs, resource_estimator/src/counts.rs
Added ConfigurePauliNoise and ApplyIdleNoise to Diagnostric namespace to control noise from Q# program.
=> Noise settings available in Q#

library/std/src/Std/Diagnostics.qs
The matrix was wrong in the doc comment, in that it was showing H as diagonal and shouldn't be.
=> Fix doc comment on `DumpOperation`

samples/algorithms/BernsteinVazirani.qs, samples/algorithms/BernsteinVaziraniNISQ.qs, samples/algorithms/BitFlipCode.qs, samples/algorithms/CatState.qs, samples/algorithms/DeutschJozsa.qs, samples/algorithms/DeutschJozsaNISQ.qs, samples/algorithms/DotProductViaPhaseEstimation.qs, samples/algorithms/GHZ.qs, samples/algorithms/Grover.qs, samples/algorithms/HiddenShift.qs, samples/algorithms/HiddenShiftNISQ.qs, samples/algorithms/JointMeasurement.qs, samples/algorithms/Measurement.qs, samples/algorithms/PhaseFlipCode.qs, samples/algorithms/QRNG.qs, samples/algorithms/QRNGNISQ.qs, samples/algorithms/Shor.qs, samples/algorithms/SuperdenseCoding.qs, samples/algorithms/Teleportation.qs, samples/estimation/Dynamics.qs, samples/language/Specializations.qs
Removes unnecessary `@EntryPoint()` attributes in the Q# samples.
Addresses #1688
=> Remove unnecessary EntryPoint attributes in the samples

compiler/qsc_formatter/src/formatter.rs, library/signed/src/Operations.qs, library/std/src/Std/Canon.qs, library/std/src/Std/InternalHelpers.qs, library/unstable/src/TableLookup.qs
Noticed a minor issue in the formatter where we weren't treating doc comments as comments.
=> Indentation fix in doc comment formatting

compiler/qsc_ast/src/ast.rs, compiler/qsc_doc_gen/src/display.rs, compiler/qsc_fir/src/ty.rs, compiler/qsc_formatter/src/formatter.rs, compiler/qsc_frontend/src/typeck.rs, compiler/qsc_frontend/src/typeck/convert.rs, compiler/qsc_frontend/src/typeck/infer.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_frontend/src/typeck/tests/bounded_polymorphism.rs, compiler/qsc_hir/src/ty.rs, compiler/qsc_lowerer/src/lib.rs, compiler/qsc_parse/src/item/tests.rs, compiler/qsc_parse/src/ty.rs, compiler/qsc_parse/src/ty/tests.rs, language_service/src/completion.rs, language_service/src/references.rs, playground/src/main.tsx, samples/language/ClassConstraints.qs, vscode/src/completion.ts
This work was somewhat substantial so I wanted to pull it out of #2007 for separate review, since that one's already approved.
=> Break `Num` into `Mul`, `Sub`, `Div`, `Mod`, and `Signed` classes

katas/content/complex_arithmetic/polar_multiplication/Solution.qs, katas/content/complex_arithmetic/polar_multiplication/index.md
More accurate solution for [Polar Multiplication Kata](https://github.com/microsoft/qsharp/blob/main/katas/content/complex_arithmetic/polar_multiplication/index.md)
=> More accurate solution to kata

compiler/qsc_circuit/src/builder.rs, compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_eval/src/lib.rs, compiler/qsc_eval/src/tests.rs, compiler/qsc_eval/src/val.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/management.rs, compiler/qsc_partial_eval/src/tests/operators.rs, compiler/qsc_partial_eval/src/tests/qubits.rs, resource_estimator/src/counts.rs
This change adds some basic qubit live-ness tracking to the simulator, achieved by changing the `Value::Qubit` variant to a weak pointer to the qubit and having the execution environment own and track the `Rc` that owns the qubit. This provides a few benefits:
- Fixes a panic when a qubit is passed to the simulator after it has been released.
- Adds graceful error handling to treat use-after-release as a runtime error.
- Adds a specific error for "double release" of a qubit if it is being manually managed.
- Updates the display of the qubit type to show the qubit ID when it is live and `Qubit<released>` when it is not, enabling easier debugging of qubit lifetimes.
Of note, local perf testing showing no impact on performance (thanks, Rust zero-cost abstractions!), though it stands to …
=> Track qubit live-ness during simulation

library/qtest/qsharp.json, library/qtest/src/Functions.qs, library/qtest/src/Main.qs, library/qtest/src/Operations.qs, library/qtest/src/Tests.qs, library/qtest/src/Util.qs, library/signed/qsharp.json, library/signed/src/Tests.qs
This PR introduces Qtest, a library for running Q# unit tests. It includes two namespaces: `Functions` for testing functions and `Operations` for testing operations. `Operations` also allows for qubit state preparation before tests.
To demonstrate, I converted `MeasureSignedIntTests()` in `signed/src/Tests.qs` to use Qtest. [The result is fewer lines of code](https://github.com/microsoft/qsharp/pull/2013/files#diff-fa6f0fda29e55d52d8254ab813dcda39094b02928370e841ea741c526e3d5338L16) and clearer test intentions. Additionally, all tests run before reporting any failures, unlike the current behavior which stops at the first failure.
I haven't converted all existing Q# tests yet, as that's beyond this PR's scope. This PR aims to validate the API's utility before proceeding with further …
=> Add `Qtest` library that uses class constraints

vscode/src/completion.ts, vscode/test/suites/language-service/language-service.test.ts
Fixing the behavior that regressed in #1947 when I was attempting to limit samples to empty documents only.
=> Include samples in completions when the document is empty

.github/workflows/publish-playground.yml
Since we are using `upload-pages-artifact@v3` we must use v4 of the deploy task (see https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0)
=> Use `deploy-pages@v4`

library/fixed_point/qsharp.json, library/fixed_point/src/Operations.qs, library/signed/qsharp.json, library/signed/src/Comparison.qs, library/signed/src/Operations.qs
Now that the `Unstable` library has been deprecated and its contents ported to the standard library, we no longer need these external project dependencies.
Closes #2027
=> Remove Unstable dependency; replace with stabilized stdlib version in library code

build.py, pip/qsharp/interop/qiskit/backends/backend_base.py, pip/qsharp/interop/qiskit/backends/qirtarget.py, pip/tests-integration/interop_qiskit/test_gate_correctness.py, pip/tests-integration/interop_qiskit/test_gateset_qasm.py, pip/tests-integration/interop_qiskit/test_re.py, pip/tests-integration/test_requirements.txt
Qiskit v1.3 changed the behavior of `num_qubits` on the `Target` class in way that broke our `QirTarget` usage, since we expect to default to `None` but the new logic ignores the `num_qubits` parameter to `__init__` and always defaults to zero qubits, failing later calls to transpilation. By shadowing the parent class property in `QirTarget` we can continue returning `None` and trigger the right behavior in transpilation while preserving a setter for use with v1.2.
Note: I tested locally with both v1.2.4 and v1.3.0 integration tests to confirm the behavior is as expected.
Fixes #2047
=> Fix Qiskit interop with v1.3

samples/estimation/df-chemistry/chemistry.py
This configuration was added in #1700, but it has a wrong error budget that is not compatible with the other configuration and the sample. I removed it again for clarity.
=> Remove configuration in DF chemistry sample

Cargo.lock, Cargo.toml, compiler/qsc_eval/Cargo.toml, compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/val.rs, library/src/tests.rs, library/src/tests/intrinsic.rs, library/std/src/Std/Intrinsic.qs
This adds a new library function `ApplyUnitary` that given a matrix of complex numbers will apply that matrix to the given qubits. This requires a new version of the simulator that exposes the functionality publicly.
Starting as draft to wait for https://github.com/qir-alliance/qir-runner/pull/208
=> Support `ApplyUnitary` in simulation

compiler/qsc_frontend/src/lower.rs, compiler/qsc_hir/src/hir.rs, language_service/src/definition.rs, language_service/src/hover.rs, language_service/src/hover/tests.rs, language_service/src/name_locator.rs, language_service/src/references.rs, language_service/src/rename.rs
Adds hover descriptions to built-in attributes in the Q# language server.
Closes #1994
=> Add Hover Descriptions to Attributes

compiler/qsc_frontend/src/closure.rs, compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_passes/src/spec_gen/tests.rs
It's come up a few times that having an easy way to differentiate lambdas would be helpful, and this change updates the name the we use for auto-generated items from lambdas to use a name that can't normally be created in Q# so we know for a fact it won't overlap with any other items.
=> Use `<lambda>` for auto-generated name

vscode/src/azure/providerProperties.ts
This change updates the logic we use to decide if a target supports QIR submission in the extension. Previously it was an allow list which required any new targets or providers to be explicitly added. Instead, this uses a deny list style so that new providers and targets are allowed to submit either base or adaptive without requiring updates to the QDK. Then we can coordinate with new partners on what targets should be lit up for which purposes.
=> Switch QIR Target checking from allow list to deny list

compiler/qsc_linter/src/linter.rs, compiler/qsc_linter/src/linter/ast.rs, compiler/qsc_linter/src/lints/ast.rs, compiler/qsc_linter/src/lints/hir.rs, compiler/qsc_linter/src/tests.rs, compiler/qsc_parse/src/expr.rs, compiler/qsc_parse/src/expr/tests.rs, samples/algorithms/MajoranaQubits/src/Main.qs, vscode/qsharp.schema.json
Makes the `set` keyword optional for assignment expressions. Adds a lint and code action to deprecate the use of the `set` keyword. The lint level is set to "Allow".
Closes #1496
=> Deprecate `set` Keyword

vscode/src/azure/workspaceActions.ts, vscode/src/notebookTemplate.ts
This is the sample notebook you can create from the command palette (which is very handy to avoid having to download/copy one to get started).
It was a little out of date. This has some minor improvements.
=> Update sample notebook

vscode/src/azure/commands.ts, vscode/src/createProject.ts, vscode/src/diagnostics.ts, vscode/src/memfs.ts, vscode/src/notebook.ts, vscode/src/qirGeneration.ts, vscode/src/statusbar.ts, vscode/src/webviewPanel.ts, vscode/test/suites/debugger/debugger.test.ts
This was a drive-by update from my work in #2059. Just wanted it in a separate PR to keep the noise down.
It seems to have triggered some `prettier` fixes too.
=> use common extension ID instead of hardcoded one

compiler/qsc_eval/src/intrinsic.rs, library/src/tests/canon.rs
When relabeling qubits arrays with odd lengths 5 or greater, the final case in the match statement triggered with a bug that caused the mappings tracked for swaps to be updated incorrectly, resulting in the wrong qubit labels being swapped. This fixes the bug, updates some variable names and comments for clarity, and adds new test cases to verify the expected behavior. It also fixes a minor test bug in a related test that was verifying the wrong state.
Fixes #2077
=> Fix `Relabel` for odd size arrays

pip/qsharp/telemetry.py
Failure to send telemetry should not be reported as an error. This changes those log messages to `info` level. (Only `warning` or higher logs by default if not explicitly configured).
Fixes #2081
=> Don't log errors from telemetry

library/std/src/Std/Measurement.qs
Moved important remarks into summary as only summary is visible in most cases. Removed description when it was a simple rewording of the summary.
For example, MeasureInteger resets its arguments, but it was not clear from the name or summary.
=> Updated doc comments on measurement operations

vscode/syntaxes/qsharp.tmLanguage.json
Supports syntax highlighting for:
- function definitions
- function calls
- numbers
- variables
See issue https://github.com/microsoft/qsharp/issues/1950.
The change for function calls also applies to operation definitions and to attributes (see bigger example below).
The change for variables also applies to attributes and to imports.
I might be nice to make attributes and imports get their own designated rules. I can do them as part of this PR, but I think it might be best to do as a followup issue - because I believe this PR is actually already an improvement for them.
Simple example for the change (from the original issue description):
And a bigger example:
=> Syntax highlighting for functions, variables and numbers

library/src/tests/intrinsic.rs, library/std/src/Std/Intrinsic.qs
This fixes a bug in the decomposition for `Exp` that would cause a runtime failure if an array of more than two qubits was used and a single `PauliI` was passed in the Pauli array. The decomposition ignores `PauliI` by calling the `RemovePauliI` helper function, but then incorrectly uses the original arrays when rather than the filtered arrays in the rest of the operation. This adds a test to confirm the fix (without the fix the test triggers a runtime failure in `MapPauli`).
=> Fix `Exp` on qubit arrays larger than 2 with single `PauliI`

package-lock.json, package.json
This upgrade removes [the deprecation warnings](https://github.com/microsoft/qsharp/actions/runs/12552878778/job/34999478342#step:9:148) that come up during the `npm install` step.
Current:
```
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
added 494 packages, and audited 498 packages in 4s
86 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
With eslint 9.17.0:
```
$ npm install
added 498 packages, and audited 502 packages in 4s
87 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
=> Upgrade to `eslint@9.17.0` to remove deprecated dependency

compiler/qsc/src/codegen/tests.rs, compiler/qsc_partial_eval/src/evaluation_context.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/tests/assigns.rs, compiler/qsc_partial_eval/src/tests/bindings.rs, compiler/qsc_partial_eval/src/tests/calls.rs, compiler/qsc_partial_eval/src/tests/dynamic_vars.rs, compiler/qsc_partial_eval/src/tests/intrinsics.rs, compiler/qsc_partial_eval/src/tests/misc.rs, compiler/qsc_partial_eval/src/tests/operators.rs, compiler/qsc_rir/src/passes/ssa_transform.rs, compiler/qsc_rir/src/passes/ssa_transform/tests.rs, pip/tests-integration/resources/output/Adaptive_RI/SuperdenseCoding.ll, pip/tests-integration/resources/output/Adaptive_RI/ThreeQubitRepetitionCode.ll
This fixes the bug by having partial evaluation more explicitly track different variable mappings to literals across branches and recombining those mappings that match (ie: are constant) when all branches are done. This also includes partial eval and RIR SSA pass fixes to correctly support immutable and mutable copies of dynamic variables. New test cases for several combinations of constant folding at partial eval are included, as well as a new test case confirming RIR SSA fix.
Fixes #2087
=> Mutable variables in dynamic branches prevent full constant folding in partial evaluation

compiler/qsc_eval/src/intrinsic.rs
This simplifies the relabeling logic to collapse the four match cases down into one for easier readibility. It avoids trying to optimize special cases for qubits that may not have been mapped and treats all labels as having an intial mapping to themselves.
Based on feedback from @DmitryVasilevsky in https://github.com/microsoft/qsharp/pull/2082#discussion_r1899442453
=> Simplify `Relabel` logic

samples_test/src/tests.rs, samples_test/src/tests/algorithms.rs, samples_test/src/tests/language.rs
1. Added clarification comment why we need two expected strings in sample testing.
2. Made general comment a normal comment rather than doc comment - otherwise it was bound to the first constant in the file.
=> Added comments to sample tests

library/qtest/src/Functions.qs, library/qtest/src/Operations.qs, library/qtest/src/Tests.qs
I believe this should address the ideas @Manvi-Agrawal proposed in #2026. What do you think Manvi?
Closes #2026
=> Add `TestMatrix` functionality to qtest

npm/qsharp/ux/qsharp-ux.css, playground/src/docs.tsx, playground/src/editor.tsx, playground/src/main.tsx, playground/src/results.tsx, playground/src/tabs.tsx
Some adjustments to the CSS so that the playground elements shrink and grow in a more intuitive way.
- So far I've tested on Edge (Windows) and Safari (Mac). I haven't tested on Firefox.
- I wasn't sure how to refactor the CSS to leave it better than I found it. I'm happy to make more changes, please give me feedback about how I can improve the code organization.
=> Improve playground layout

samples/algorithms/SimpleVQE.qs, samples_test/src/tests/algorithms.rs
This PR adds simple self-contained example of a Variational Quantum Eigensolver (VQE).
This example includes:
1. Simple classical optimization to find minimum of a multi-variable function in order to find the approximation to the minimum eigenvalue of a Hamiltonian.
2. Finding Hamiltonian expectation value as a weighted sum of terms.
3. Finding one term expectation value by performing multiple shots of preparing ansatz state and measuring it.
4. Ansatz state preparation similar to the circuit in the published paper "Ground-state energy estimation of the water molecule on a trapped ion quantum computer" (https://arxiv.org/abs/1902.10171)
To keep this sample simple and self-contained Hamiltonian is artificial (doesn't correspond to any actual chemistry problem). Also, this sample doesn't …
=> Added simple VQE sample

samples/estimation/df-chemistry/chemistry.py
Scipy does not work on Windows ARM64 currently (see https://github.com/scipy/scipy/issues/21562) which is a platform we support.
This is the only sample that uses scipy, so removing that usage for the equivalent numpy usage.
CC @msoeken and @aarthims
=> Remove scipy

Cargo.lock, Cargo.toml
This pulls in some updates to the simulator, including updating to newer dependencies and a fix for https://github.com/qir-alliance/qir-runner/issues/211
=> Update to latest simulator

.github/workflows/ci.yml
Current runtime is ~13min under normal circumstances. Extending timeout to 30min which should be generous enough.
(At the time that this current 15min timeout was added, integration tests took 5 minutes to run).
=> Increase integration test timeout to 30m

npm/qsharp/ux/qsharp-ux.css, widgets/js/index.tsx
(See related issues https://github.com/microsoft/vscode-jupyter/issues/7161 and https://github.com/microsoft/vscode-jupyter/issues/9403 for more background)
Our CSS override to address the widget theming issue wasn't working somtimes, which was very frustrating, as in Dark Mode our widgets would often appear as they should in light mode.
The reason is that the order in which the style sheets get injected is non-deterministic, and as the 'problematic' CSS rule and the override to fix it have the same specificity, it would be 'last one wins'. Sometimes our style-sheet is last and it works...
And sometimes the IPyWidgets 'force it to white' rule is last so the issue persists...
The unfortunate best _hack_ I could come up with is to programmatically ensure the override CSS rule is always last …
=> Fix widgets sometimes rendering in light theme when VS Code is in a dark theme

library/src/tests/resources/src/add_le.qs, library/std/src/Std/Arithmetic.qs, library/std/src/Std/ArithmeticUtils.qs
Updated LookAheadDKRSAddLE to accept carry-in.
Updated tests.
Resolves https://github.com/microsoft/qsharp/issues/2101
=> LookAheadDKRSAddLE now accepts carry-in

npm/qsharp/src/workers/browser.ts
This warning comes from [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen/blob/c35cc9369d5e0dc418986f7811a0dd702fb33ef9/crates/cli-support/src/js/mod.rs#L981) and shows up in the JS console every time we load the playground / VS Code . 
Just updating the code to use the signature they want us to use.
=> fix deprecation warning for `initSync()`

compiler/qsc_linter/src/lints/hir.rs, compiler/qsc_linter/src/tests.rs, samples/estimation/df-chemistry/src/DoubleFactorizedChemistry.qs, samples/estimation/df-chemistry/src/Prepare.qs
This PR adds a lint for double equality and inequality.
It also updates the DF Chemistry sample to perform a correct `NAN` check.
=> Add lint for double (in)equality

library/std/src/Std/Arithmetic.qs, library/std/src/Std/ArithmeticUtils.qs, library/std/src/Std/TableLookup.qs, samples/algorithms/Shor.qs, samples_test/src/tests/algorithms.rs
We used to have custom implementation for AND before we added it to the standard library. Now that we have it in std, this PR removes custom ApplyAndAssuming0Target and replaces it with AND. This standard implementation is via PhaseCCX, and has the same T-count of 4, T-depth of 2, but uses fewer gates overall.
Previous custom implementation:
Implementation from the standard library:
This new implementation results in different sequence of gates in Shor's sample, which, in turn, changes its behavior on the specific test we have for it. As randomness is removed from tests, that scenario results in guessing factorization, which isn't great. So this PR changes the default sample for Shor.
=> Replaced custom ApplyAndAssuming0Target with AND from std

library/fixed_point/src/Main.qs, library/rotations/src/Main.qs
Works around #1955 in the libraries we publish by reexporting the items under an alias. This change should make no difference to the intended public API of the library.
=> Work around reexport issue in libraries

compiler/qsc_doc_gen/src/generate_docs.rs, compiler/qsc_doc_gen/src/generate_docs/tests.rs, library/std/src/Std/Math.qs, library/std/src/Std/Measurement.qs
We no longer want to escape the pipe character in the metadata fields, but still want to escape it when composing the index.md files.
=> DocGen Tool: Don't escape pipe character in metadata

Cargo.lock, compiler/qsc_linter/Cargo.toml, compiler/qsc_linter/src/linter.rs, compiler/qsc_linter/src/linter/ast.rs, compiler/qsc_linter/src/linter/hir.rs, compiler/qsc_linter/src/tests.rs
This PR deduplicates lints in the `run_lints` function, which is the entry point to the linter, to avoid having repeated lints in operations that have multiple specializations.
=> Deduplicate lints to avoid having repeated lints in operations that have multiple specializations

vscode/src/circuit.ts, vscode/src/debugger/session.ts, vscode/src/documentation.ts, vscode/src/webview/webview.tsx, vscode/src/webviewPanel.ts
Instead of always consuming the last Q# webview tab, open a new webview tab when activated with a new operation. Activation with the same operation will still consume/update the last webview for that operation. Works on circuit and histogram panels.
=> Multiple Webview Tabs

library/qtest/src/Tests.qs
I think that this got clobbered in a merge conflict. This fixes up the Q# code that runs tests within qtest's test suite for itself.x
=> Fix incorrect syntax in qtest tests

compiler/qsc/src/interpret/circuit_tests.rs, compiler/qsc_circuit/src/circuit.rs, compiler/qsc_circuit/src/circuit/tests.rs
See issue https://github.com/microsoft/qsharp/issues/1476.
I tried to keep the logic as close as possible to the original, because I wanted to keep it easy to review it in relation to the old logic.
The main change here is that instead of having the `ObjectsByColumn` of every Row be a `FxHashMap<usize, String>` which contains the 7-width-wide strings, it's now a `FxHashMap<usize, CircuitObject>`, where `CircuitObject` is an enum that supports every circuit object except for than blanks and wires (because those are inserted later on, on-the-go).
Using this enum allows us to calculate the required `ColumnWidthsByColumn` (a `FxHashMap<usize, usize>`) right before calling `row.fmt` - so we know what width the `CircuitObjects` need to be when converted into strings.
In the example from the …
=> Long gate in ASCII art circuits - lengthen column width when necessary

compiler/qsc_frontend/src/compile/tests/multiple_packages.rs, compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/typeck/convert.rs
=> Fix UDT re-exports

compiler/qsc_project/src/project.rs, pip/qsharp/_qsharp.py
Fixing regression described in https://github.com/microsoft/qsharp/pull/2109#issuecomment-2629169244
=> fix `qsharp.init(project_root='.')`

compiler/qsc_partial_eval/src/evaluation_context.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/tests/qubits.rs
This adds a check at codegen time if a qubit relabel is occurring in an adaptive conditional. This will ensure we don't generate QIR with incorrect qubit IDs. The change ties the error to the dynamic qubit capability because if/when we support dynamic qubits we'll need to update relabel to become an intrinsic that is supported by backends to do a runtime relabel of qubit identifiers.
Fixes #2152
=> `Relabel` in adaptive conditional block should be disallowed

compiler/qsc_frontend/src/compile/tests/multiple_packages.rs, compiler/qsc_frontend/src/resolve.rs
Closes #2146
I also found another unrelated bug while working on this, which I filed here: #2153
=> add UDT to list of terms when processing reexport

library/fixed_point/qsharp.json, library/signed/qsharp.json, vscode/src/registry.json
Also changing the 'stable' reference to point to a tag. (We should probably auto-bump 'stable' to be the latest release tag for each release - I'll add a task for that.
Chemistry wasn't in v1.13, so just pointing that to main for now, and will add a 'stable' tag for next release.
=> Update registry for chemistry

language_service/src/state.rs, language_service/src/state/tests.rs
Small fix to #1787 while staying true to the intention of that change.
We want to _hide_ errors from GitHub sources that are open in the editor, but aren't associated with a project. They're essentially orphans. For example, you may have closed the original project that referenced those GitHub sources, but left the GitHub source open in the editor.
But we want to _show_ errors from GitHub sources if they're part of a normal project. Errors from dependencies are helpful.
=> LS: Hide errors from github sources only when they're not associated with a real project

.devcontainer/devcontainer.json
This updates the repo's devcontainer to use a base image with a newer Ubuntu version making it more compatible out of the box with our build tooling requirements and installable published packages.
=> Update devcontainer to Ubuntu noble base image

compiler/qsc_frontend/src/typeck/tests.rs, library/fixed_point/src/Facts.qs, library/fixed_point/src/Main.qs, library/fixed_point/src/Measurement.qs, library/fixed_point/src/Operations.qs, library/fixed_point/src/Polynomial.qs, library/fixed_point/src/Reciprocal.qs, library/fixed_point/src/Tests.qs
=> Annotate conditional compilation for fixed_point so it compiles in all profiles

library/src/tests/table_lookup.rs, library/std/src/Std/TableLookup.qs
When selecting a single bit string the number of address bits is 0, and we run into a problem splitting the address register in the optimized Unlookup implementation. This case is now handled without measurement based uncomputation.
=> Fix bug in Unselect operation when selecting a single bit string

compiler/qsc_circuit/src/operations.rs, compiler/qsc_circuit/src/operations/tests.rs, language_service/src/code_lens.rs, language_service/src/code_lens/tests.rs, language_service/src/protocol.rs, npm/qsharp/src/compiler/compiler.ts, vscode/src/debugger/activate.ts, vscode/src/language-service/codeLens.ts, vscode/src/webviewPanel.ts, vscode/test/suites/language-service/language-service.test.ts, wasm/src/language_service.rs, wasm/src/lib.rs
This change adds support for code lenses on any callable that qualifies for them instead of just the entry point. In practice, this means any function or operation that doesn't take arguments can be used as the starting place for a run, debug, estimate, histogram, or (in the case of operations) circuit. This is paticularly helpful for unit tests identifed by the `@Test()` attribute, as it lets them be run or debug outside of the test infra with a single click.
=> Support code lenses on more callables

vscode/src/webviewPanel.ts
The feature in #2174 mistakenly broke Circuit codelenses (late refactoring caused it to always run the entry point instead of the associated operation).
Fixes #2189
=> Fix Circuit codelens

compiler/qsc_frontend/src/lower/tests.rs, compiler/qsc_frontend/src/typeck/rules.rs, compiler/qsc_frontend/src/typeck/tests.rs, compiler/qsc_rca/src/tests/lambdas.rs
This fixes a quirk leftover from the fixes in #649 and #793. Those introduced and then updated a conditional that avoided unifying certain types during type checking, but it turns out it was always safe to unconditionally unify the types once #649 introduced the explicit return type tracking. With this fix, the lifted lambda callables with explicit returns have the correct output type instead of always being `Unit` and RCA is able to use that type information as expected, avoiding the panic.
Fixes #2186
=> Fix RCA panic on lambda with explicit return

vscode/src/debugger/activate.ts
The change in #2174 broke the Run/Debug UI buttons, as it turns out they pass extra parameters that the code used to ignore and were now being treated as string input. This adds some runtime type checking to protect against that.
When invoked via code lens, the command receives the entry expression as expected with the updates:
When invoked via the command palette, the entry expression is undefined, which makes sense because it is a new paramter that was never meant to be passed in that scenario:
But when invoked via the UI "Run" button, the new paramter receives an object that presumably describes the UI element:
This unexpected input was later treated as a string, passed over the FFI into Rust, and then triggered an out-of-bounds memory read.
=> Fix Run and Debug buttons

katas/content/complex_arithmetic/powers_of_i/index.md
A user reported that _i (i^n)_ reads like _i * (i^n)_. I tend to agree.
=> Katas: Clarify i (i^n)

compiler/qsc/src/interpret/circuit_tests.rs, compiler/qsc_circuit/src/circuit.rs, compiler/qsc_circuit/src/circuit/tests.rs
This PR has a proposed fix for issue https://github.com/microsoft/qsharp/issues/2184, but it mainly includes refactoring of the circuit-art code based on comments from PR https://github.com/microsoft/qsharp/pull/2126.
The only real functionality change in this code is that multi-target gates get extra lines that behave in the same way as measurement lines, in order to better convey the qubits involved.
For example, a circuit like this one:
```
use q0 = Qubit();
use q1 = Qubit();
Rxx(1.0, q0, q1);
use q2 = Qubit();
use q3 = Qubit();
Rxx(1.0, q2, q3);
```
instead of rendering as
```
q_0    ─ rxx(1.0000) ─
q_1    ─ rxx(1.0000) ─
q_2    ─ rxx(1.0000) ─
q_3    ─ rxx(1.0000) ─
```
will instead render as 
```
q_0    ─ rxx(1.0000) ─
┆
q_1    ─ rxx(1.0000) ─
q_2    ─ rxx(1.0000) ─
┆
q_3    ─ …
```
=> Multi-target gate circuit art improvement

vscode/test/suites/debugger/debugger.test.ts
Reverts microsoft/qsharp#2164
VS Code reverted the change that caused this test failure in the first place.
=> Revert "disable failing vscode test"

library/chemistry/qsharp.json, library/chemistry/src/JordanWigner/Convenience.qs, library/chemistry/src/JordanWigner/ConvenienceVQE.qs, library/chemistry/src/JordanWigner/JordanWignerBlockEncoding.qs, library/chemistry/src/JordanWigner/JordanWignerClusterOperatorEvolutionSet.qs, library/chemistry/src/JordanWigner/JordanWignerEvolutionSet.qs, library/chemistry/src/JordanWigner/JordanWignerOptimizedBlockEncoding.qs, library/chemistry/src/JordanWigner/JordanWignerVQE.qs, library/chemistry/src/JordanWigner/OptimizedBEOperator.qs, library/chemistry/src/JordanWigner/StatePreparation.qs, library/chemistry/src/JordanWigner/Utils.qs, library/chemistry/src/Tests.qs, library/chemistry/src/Utils.qs
This change updates chemistry library:
- Removes old sysntax such as a! and [x, size=5]
- Reduced use of w/= where possible
- Makes long argument lists more readable
- Fixes error in comments
- Updates pairs of double representing a complex number to use complex type
- Adds a few unit tests
No renames yet.
=> Chemistry lib: readablility, lints, syntax, tests

vscode/test/suites/language-service/language-service.test.ts
VS Code integration tests started failing intermittently on Windows. Other platforms have been passing fine.
In my local runs, I can see the tests failing about 1/4 times.
This seems to be due to an existing, known, timing issue in the tests.
Somehow some recent change made this delay worse, but I can't track down what exactly.
Increasing this delay from 50ms to 100ms made the tests pass on my local machine 20 times in a row... which I consider improvement enough.
Sad.
=> Mitigate VS Code language service integration tests flakiness

pip/qsharp/estimator/_estimator.py, resource_estimator/src/estimates/error_correction.rs, resource_estimator/src/estimates/error_correction/code_with_threshold_and_distance.rs, resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/estimates/physical_estimation/estimate_frontier.rs, resource_estimator/src/estimates/physical_estimation/estimate_without_restrictions.rs, resource_estimator/src/system/modeling/fault_tolerance.rs, resource_estimator/src/system/modeling/fault_tolerance/tests.rs, resource_estimator/src/system/test_report.json
This PR extends the formula template for QEC logical error rate formulas from:
$$ a \left(\frac{p}{p_{\mathrm{th}}}\right)^{\frac{d+1}{2}} $$
to
$$ a d^k \left(\frac{p}{p_{\mathrm{th}}}\right)^{\frac{d+1}{2}} $$
where $k$ is the new distance coefficient power discussed in [arXiv:2411.10406, Section III.B, page 25](https://arxiv.org/pdf/2411.10406#page=25).
For $k = 0$, the default, the formula remains unchanged compared to the current one. However, changing $k$ to other values allows to model a different error correction behavior, as motivated by the paper.
The parameter is called `distance_coefficient_power` or `distanceCoefficientPower` in the JSON parameter. It is also added to the Python RE parameter utility structure (together with `max_code_distance` which was absent so far).
=> Distance coefficient power parameter in QEC scheme

compiler/qsc_qasm3/src/parser/expr.rs, compiler/qsc_qasm3/src/parser/expr/tests.rs, compiler/qsc_qasm3/src/parser/stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests.rs, compiler/qsc_qasm3/src/parser/stmt/tests/expr_stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/invalid_stmts.rs
Previously assignments and binary assignments were valid in any part of the expression tree. This PR makes Assign and AssignOp valid only in expression statements.
=> Make Assign and AssignOp valid only in expression statements

compiler/qsc_qasm3/src/ast.rs, compiler/qsc_qasm3/src/parser/error.rs, compiler/qsc_qasm3/src/parser/expr.rs, compiler/qsc_qasm3/src/parser/expr/tests.rs, compiler/qsc_qasm3/src/parser/stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/alias.rs, compiler/qsc_qasm3/src/parser/stmt/tests/expr_stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/for_loops.rs, compiler/qsc_qasm3/src/parser/stmt/tests/gate_call.rs, compiler/qsc_qasm3/src/parser/stmt/tests/if_stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/while_loops.rs, compiler/qsc_qasm3/src/semantic/ast.rs, compiler/qsc_qasm3/src/semantic/lowerer.rs
This PR turns assignment into a StmtKind (it was a ExprKind before).
=> Make assignment a StmtKind

build.py
This change suggests running specific command 'npm run prettier:fix' to fix prettier errors if the formatting check fails. Could be hard to figure out what to run by just looking at 'Run Prettier with --write to fix' message.
=> Specific suggestion what to run if formatting check fails

katas/content/qubit/index.md
Indeed, atan2(y, x) is present in many languages. We also have ArcTan2(y, x) in Q#, and it takes y as the first argument as expected. The text describes an example of a phase of a complex number $\frac{1 - i}{2}$. Here x=1/2 and y=-1/2. Previous text had these coefficients switched. Now it is fixed.
Also changed wording from "the phase of |0>" to "the phase of |0> amplitude", which seems to be a better wording as the paragraph talks about phases of complex numbers.
=> Fixed coefficients in qubit kata explanation.

compiler/qsc/src/interpret/tests.rs, compiler/qsc_frontend/src/resolve.rs
This fixes an issue where items from the Main.qs in a project would not be visible with the explicit `Main` namespace. When the dependency has no alias we should skip the special handling that elides the `Main` so that items are accessible as expected (and as documented in [Running the Programs](https://learn.microsoft.com/en-us/azure/quantum/how-to-work-with-qsharp-projects?tabs=tabid-qsharp%2Ctabid-notebook-run#running-the-programs))
Fixes #2207
=> Fix name resolution from a project's Main.qs

compiler/qsc_qasm3/src/parser/ast.rs, compiler/qsc_qasm3/src/parser/stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/for_loops.rs, compiler/qsc_qasm3/src/parser/stmt/tests/if_stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/invalid_stmts/branch.rs, compiler/qsc_qasm3/src/parser/stmt/tests/invalid_stmts/loops.rs, compiler/qsc_qasm3/src/parser/stmt/tests/while_loops.rs
If/else blocks, while, and for loops in QASM introduce new scopes only when their body enclosed by curly braces. To make lowering easier, this PR changes their bodies from `List<Stmt>` to `Stmt`. In the body enclosed in curly braces case, the Stmt will be of kind Block.
=> Make control flow stmts use Stmt instead of List<Stmt> for their bodies.

compiler/qsc_qasm3/src/parser/ast.rs, compiler/qsc_qasm3/src/parser/mut_visit.rs, compiler/qsc_qasm3/src/parser/stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/for_loops.rs, compiler/qsc_qasm3/src/semantic/ast.rs, compiler/qsc_qasm3/src/semantic/error.rs, compiler/qsc_qasm3/src/semantic/lowerer.rs, compiler/qsc_qasm3/src/semantic/tests/statements/box_stmt.rs, compiler/qsc_qasm3/src/semantic/tests/statements/for_stmt.rs, compiler/qsc_qasm3/src/semantic/tests/statements/if_stmt.rs, compiler/qsc_qasm3/src/semantic/tests/statements/switch_stmt.rs, compiler/qsc_qasm3/src/semantic/tests/statements/while_stmt.rs
This PR:
1. Aliases super::ast to semantic.
2. Fixes The bodies of if, for, and while to be `Stmt` instead of `List<Stmt>`.
3. Lowers the if, for, while, and switch stmts.
4. Refactors the pattern used to handle lowering of optional items by introducing the `short_circuit_opt_item!` macro.
=> Lower control flow stmts in QASM3 parser

vscode/src/copilot/webview/copilot.css
Fix the copilot panel not rendering correctly on Mac or Linux. I tested this on all 3 platforms, and in the Firefox browser (which was the last platform/browser to have quirks with `system-ui` that I could find details on).
=> Change default font to system-ui

samples/algorithms/BellState.qs, samples/algorithms/BernsteinVazirani.qs, samples/algorithms/DeutschJozsa.qs, samples/algorithms/DotProductViaPhaseEstimation.qs, samples/algorithms/HiddenShift.qs, samples/algorithms/QRNG.qs, samples/algorithms/Shor.qs, samples/algorithms/Teleportation.qs, samples/algorithms/ThreeQubitRepetitionCode.qs, samples/estimation/ShorRE.qs, samples/language/Range.qs, samples/language/RepeatUntilLoops.qs, samples/language/Variables.qs, samples/language/WhileLoops.qs, samples_test/src/tests/language.rs
The language samples still stated:
> // Mutable variables can be mutated with the `set` keyword
Technically this is true, but since `set` is now [deprecated](https://github.com/microsoft/qsharp/pull/2062) I removed it from all the samples.
=> Removed usage of deprecated set keyword from the samples

compiler/qsc/src/interpret.rs, compiler/qsc/src/interpret/circuit_tests.rs, compiler/qsc/src/interpret/tests.rs, compiler/qsc_circuit/src/builder.rs, compiler/qsc_circuit/src/builder/tests.rs, compiler/qsc_circuit/src/circuit.rs, library/std/src/Std/Intrinsic.qs, pip/tests-integration/test_base_qir.py
This change simplifies the decomposition of `M` and `Measure` in the stdlib to no longer conditionally compile to different versions based on qubit reuse capability, instead offloading that to QIR processing, which already has similar logic.
One effect of this is simulation and circuit generation will match user expectation and patterns in the Q# code rather than more closely showing what occurs on hardware.
=> Decompose measurement in QIR Base profile processing

package-lock.json, package.json, vscode/src/copilot/webview/copilot.css, vscode/src/copilot/webview/copilot.tsx, vscode/src/copilot/webview/types.d.ts
This adds a button to copy to clipboard to the top right of code blocks, e.g.
=> Added copy button to code blocks in copilot

vscode/src/copilot/webview/copilot.css, vscode/src/copilot/webview/copilot.tsx
Used the VS Code loading spinner when busy
https://github.com/user-attachments/assets/6c5c2dc4-7dbc-4eb4-8419-37df56878034
Also fixed the spacing at the bottom of this histogram:
Before
After
Also added the 'bash' language in code highlighting, as sometimes commands or plain text try to use this language (and the console was showing warnings if it wasn't registered).
=> Add spinner and fix histogram spacing

npm/qsharp/ux/histogram.tsx
Require the ctrl key + scroll gesture to zoom in on the histogram, which is a common combo. This stops the histogram from "stealing" the mouse when scrolling in a notebook or in copilot pane and blocking the scroll action.
Pinch-to-zoom on a trackpad is already wheel+ctrl, so that is unaffected.
Testing in VS Code Histogram pane, Notebooks, and in new Copilot pane.
=> Require ctrl key to zoom histogram

compiler/qsc_qasm3/src/ast_builder.rs, compiler/qsc_qasm3/src/compile.rs, compiler/qsc_qasm3/src/compiler.rs, compiler/qsc_qasm3/src/parser/ast.rs, compiler/qsc_qasm3/src/parser/mut_visit.rs, compiler/qsc_qasm3/src/parser/stmt.rs, compiler/qsc_qasm3/src/parser/stmt/tests/gphase.rs, compiler/qsc_qasm3/src/semantic/ast.rs, compiler/qsc_qasm3/src/semantic/error.rs, compiler/qsc_qasm3/src/semantic/lowerer.rs, compiler/qsc_qasm3/src/semantic/types.rs, compiler/qsc_qasm3/src/tests/declaration.rs, compiler/qsc_qasm3/src/tests/declaration/def.rs, compiler/qsc_qasm3/src/tests/expression.rs, compiler/qsc_qasm3/src/tests/expression/function_call.rs, compiler/qsc_qasm3/src/tests/expression/ident.rs, compiler/qsc_qasm3/src/tests/statement/gate_call.rs
This PR completes the lowering and compilation for:
It also does some partial work to make the compiler infallible, by returning `ExprKind::Err` instead of None when compiling expressions.
=> Compile gphase, gatedef, and control flow statements

library/chemistry/src/Tests.qs
This is a minor change to the chemistry library's test imports that avoids a name resolution error when the QIR Profile is set to something other than "Unrestricted." The library still does not compile outside of Unrestricted, but now at least RCA feedback on the library implementation itself is visible.
=> Update chemistry test imports

compiler/qsc_frontend/src/typeck/convert.rs, language_service/src/completion/ast_context.rs
Remove unnecessary conversion picked up by the latest Clippy in convert.rs
Switch to use .is_none_or instead of .map_or in ast_context.rs.
Fixes #2256
=> Fix two issues that cause the latest Clippy to fail the build.

katas/content/multi_qubit_systems/examples/MultiQubitSystems.qs
Multi-qubit systems Kata had incorrect normalizing coefficient of 0.5 in the explanatory message. Updated to include correct coefficient 1/sqrt(2).
=> Fixed message to display correct normalizing coefficient

playground/src/editor.tsx
I added `automaticLayout` to the monaco editor object props. This fix #2231
=> fix(#2231) layout monaco editor

vscode/src/common.ts, vscode/src/language-service/testExplorer.ts
This PR fixes two issues.
Firstly, Q# code used in chat contexts was showing up in the Test Explorer as additional documents (and possibly other locations). It seems to use a few schemes all starting with 'chat', so excluding those.
Secondly, the location given for failing tests was often wrong, and falling back to the first 'related' location span when we're also using that for the document uri anyway resolves that issue. (And seems like the correct thing to do anyway).
=> Fix Test Explorer issues

compiler/qsc_qasm3/src/parser/error.rs, compiler/qsc_qasm3/src/semantic/ast/const_eval.rs, compiler/qsc_qasm3/src/tests/statement/const_eval.rs
=> Fix bug in const evaluator

vscode/src/circuitEditor.ts
This avoid the delay when switching away from the circuit editor and then back while it reloads the UX.
=> Retain circuit editor when hidden

npm/qsharp/ux/circuit-vis/circuitManipulation.ts, npm/qsharp/ux/circuit-vis/events.ts
In circuit editing, when moving a control onto a target or vise-versa, the control and target should swap positions.
This also fixes an issue with copy-moving controls. The behavior is now that it will create a new control for the same operation and possibly move the operation horizontally in the circuit.
=> Swap Control and Target

compiler/qsc_qasm/src/stdlib/QasmStd/src/QasmStd/Angle.qs, library/src/tests/math.rs, library/std/src/Std/Math.qs
* Added RoundHalfAwayFromZero to standard library.
* Simplified Round (which is actually rounding half towards zero)
* Updated comments and added reference to Wikipedia
* Added tests
* Changed QasmStd to use this new function instead of separate implementation
=> Added RoundHalfAwayFromZero to standard library

compiler/qsc_qasm/src/stdlib/QasmStd/src/QasmStd/Angle.qs, library/src/tests/convert.rs, library/std/src/Std/Convert.qs
Added BigIntAsInt, which converts BigInt to Int if it fits. I saw bool array workaround used for this a few times - I think it's about time to include this conversion directly. Added code without using intrinsics.
=> Added BigIntAsInt to Std.Convert

compiler/qsc/src/interpret/circuit_tests.rs, compiler/qsc_circuit/src/builder.rs
The rotation gates created by the circuit builder were getting lower-case names: `rx`, `rxx` for example. These are inconsistent with the other gate names like `H` and `X`. It is also inconsistent with the Q# equivalent operations `Rx(theta, q)`.
This PR changes the output of the circuit builder to have upper-case names for the rotation gates, making them consistent with the other gate names and the Q# operations.
=> Capitalize the Rotation gate names in trace circuits

npm/qsharp/ux/circuit.tsx
Change the Learn More link to point to the editor wiki when using the editor.
=> Change Editor "Learn More" Link

compiler/qsc_circuit/src/circuit_to_qsharp.rs, compiler/qsc_circuit/src/circuit_to_qsharp/tests.rs, npm/qsharp/ux/circuit-vis/panel.ts
Removes |1> gate from toolbox and qsharp gen.
Also fixes lint about making the circuit a function when empty.
=> Removes |1> Gate from Circuit Editor

compiler/qsc_qasm/src/semantic/const_eval.rs, compiler/qsc_qasm/src/semantic/types.rs, compiler/qsc_qasm/src/tests/declaration/def.rs, compiler/qsc_qasm/src/tests/declaration/gate.rs, compiler/qsc_qasm/src/tests/fuzz.rs, compiler/qsc_qasm/src/tests/statement/const_eval.rs
Fixes #2313. The issue was caused by an assertion in the const evaluator. The fix is surfacing the error to the user instead of panicking. I also made sure the check is exhaustive, since it was missing some cases.
=> Fix qasm const evaluator panic

compiler/qsc_circuit/src/circuit_to_qsharp.rs, npm/qsharp/ux/circuit-vis/contextMenu.ts, npm/qsharp/ux/circuit-vis/events.ts
- Enables the use of the "Enter" key to affirm input and the "Escape" key to cancel input in argument prompt.
- Enables the use of the "Enter" key to confirm and the "Escape" key to cancel on remove-qubit confirmation prompt.
- Automatically replaces "pi" with the symbol "π" in user input for arguments for better readability.
=> Support Enter and Escape Keys with Prompts

npm/qsharp/ux/qsharp-circuit.css
The context menu CSS was incorrectly placed under the qs-circuit-panel class. The context menu is an overlay and so doesn't live under the circuit panel. This fixes the issue.
=> Fix CSS for Circuit Editor Context Menu

katas/content/preparing_states/three_states_two_qubits/Placeholder.qs, katas/content/preparing_states/three_states_two_qubits/SolutionB.qs, katas/content/preparing_states/wstate_power_of_two/Placeholder.qs, katas/content/teleportation/reconstruct_message/solution.md, katas/content/teleportation/reconstruct_message_psi_plus/index.md
Addressed community feedback.
* In kata "Preparing Quantum States", lesson "Three Two-Qubit Basis States" removed Adj+Ctl from placeholder and solution.
* In kata "Preparing Quantum States", lesson "W State on Power of Two Number of Qubits" added Adj+Ctl to placeholer and solution.
* In kata "Teleportation", lesson "Reconstruct Message (Bob's Task)", updated text and labels of cases to fix an ordering mistake and make it clearer.
* In kata "Teleportation",  lesson "Reconstruct Message with |Ψ⁺⟩", fixed copy-paste error.
Thanks for reporting!
=> Addressed Kata feedback

vscode/src/webviewPanel.ts
As it was, it would constantly rearrange the panels when you re-run a histogram etc. even if it was already visible and you'd laid out the panels to your liking.
=> Avoid changing layout if the panel is already visible

samples/algorithms/Ising/Simple1dIsingOrder1.qs, samples/algorithms/Ising/Simple2dIsingOrder1.qs, samples/algorithms/Ising/Simple2dIsingOrder2.qs
Made requested updated to Ising sample.
* Renamed `col` to j in 1D Ising sample. `col` doesn't make much sense in 1D. Variable remained `col` in 2D along with the `row`.
* Renamed step time to time step and called corresponding variable dt.
=> Made requested fixes to Ising samples

compiler/qsc_circuit/src/builder.rs, compiler/qsc_circuit/src/circuit_to_qsharp.rs, compiler/qsc_circuit/src/circuit_to_qsharp/tests.rs, compiler/qsc_eval/src/backend.rs, compiler/qsc_eval/src/intrinsic.rs, compiler/qsc_eval/src/intrinsic/tests.rs, compiler/qsc_partial_eval/src/tests/intrinsics.rs, compiler/qsc_qasm/src/stdlib/QasmStd/src/QasmStd/Intrinsic.qs, compiler/qsc_rca/src/tests/intrinsics.rs, library/src/tests/intrinsic.rs, library/std/src/QIR/Intrinsic.qs, library/std/src/Std/Intrinsic.qs, pip/qsharp/interop/qiskit/backends/qirtarget.py, pip/tests-integration/interop_qiskit/test_gateset_qasm.py, pip/tests-integration/test_base_qir.py, resource_estimator/src/counts.rs
This adds full support for an intrinsic `SX` gate by including it in the "canonical" gate set used by the QDK. This includes support across QIR generation, circuits, resource estimation, and Qiskit interop.
=> Support intrinsic `SX` gate

compiler/qsc_qasm/src/semantic/const_eval.rs, compiler/qsc_qasm/src/semantic/lowerer.rs, compiler/qsc_qasm/src/tests/declaration/def.rs, compiler/qsc_qasm/src/tests/declaration/gate.rs, compiler/qsc_qasm/src/tests/fuzz.rs, compiler/qsc_qasm/src/tests/statement/const_eval.rs
This PR fixes #2332 and #2348. It handles the division by zero case in the const evaluator for `int`, `float`, and `angle` types; and the modulo by zero case for the `int` type.
=> Handle division by zero error in const evaluator

compiler/qsc/src/interpret/tests.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/tests/intrinsics.rs
This change updates the handling for intrinsic generation such that any of the supported dynamic types for QIR generation (specifically `Bool`, `Int`, and `Double` in the matching profiles) can be returned from intrinsic callables. These were already correctly handled and analyzed from Runtime Capabilities Analysis, so all that was missing was support during partial evaluation and RIR generation.
=> Support return values from custom intrinsics

.github/copilot-instructions.md
Adding a starter `copilot-instructions.md` to make GitHub Copilot work better with our repo.
We can continue to evolve this based on whatever comes up through usage.
=> Add copilot-instructions.md for our repo

compiler/qsc/src/interpret/tests.rs, compiler/qsc_hir/src/ty.rs, compiler/qsc_passes/src/spec_gen/adj_gen.rs
=> Fix panic when getting value from `FunctorSet`

language_service/src/compilation.rs, language_service/src/state/tests.rs, vscode/src/language-service/activate.ts
Addresses #2263 by updating the known Q# test cases when the QIR profile changes.
=> Re-scan files on QIR profile change

compiler/qsc_partial_eval/src/evaluation_context.rs, compiler/qsc_partial_eval/src/lib.rs, compiler/qsc_partial_eval/src/tests/branching.rs, compiler/qsc_partial_eval/src/tests/returns.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive_plus_integers.rs, compiler/qsc_passes/src/capabilitiesck/tests_adaptive_plus_integers_and_floats.rs, compiler/qsc_rca/src/lib.rs
This change avoids the panic in early returns by blocking them in RCA and providing the user with compile-time feedback before failing during QIR generation. It also includes updates to partial evaluation to ensure that the panicking case is now treated as a unimplemented graceful failure, since we don't have proper support for it.
Since QIR generation for programs with early return have never properly been handled, this doesn't take any functionality away but rather ensures earlier indication of the unsupported patterns at compile time. I filed #2387 to cover the additional work needed to fully support dynamic explicit returns.
Fixes #2290
=> Fix panic in QIR generation when conditional branches use early return

npm/qsharp/ux/circuit.tsx, npm/qsharp/ux/qsharp-circuit.css
Nests the circuit-specific classes under the `qs-circuit` class, which is universal to the circuit widget, instead of the `qs-circuit-panel` class, which is exclusive to the vscode panel. This fixes an issue where CSS classes were not being applied in the jupyter notebook scenario.
=> Fix bug with Circuit CSS not being applied to notebooks

compiler/qsc_codegen/src/qsharp.rs, compiler/qsc_qasm/src/semantic/error.rs, compiler/qsc_qasm/src/semantic/lowerer.rs, compiler/qsc_qasm/src/semantic/tests/decls.rs, compiler/qsc_qasm/src/semantic/tests/decls/qubit.rs, compiler/qsc_qasm/src/semantic/tests/expression/indexing.rs, compiler/qsc_qasm/src/tests.rs, compiler/qsc_qasm/src/tests/fuzz.rs, language_service/src/compilation.rs, language_service/src/lib.rs, language_service/src/state.rs, language_service/src/state/tests.rs, language_service/src/tests.rs, npm/qsharp/src/compiler/compiler.ts, npm/qsharp/src/language-service/language-service.ts, npm/qsharp/test/basics.js, playground/src/editor.tsx, vscode/package.json, vscode/src/debugger/activate.ts, vscode/src/diagnostics.ts, vscode/src/extension.ts, vscode/src/language-service/activate.ts, vscode/src/programConfig.ts, wasm/src/language_service.rs
Fixes:
- Qubits must be declared globally.
- No longer using file ext for type, language id is passed into LS
- Cleaning up debugger
- Adding missing `await`s in TS
- QIR profile errors now show in openqasm docs
- Clearing command errors should work again.
Fixes #2366
Fixes #2368
Fixes #2379
Fixes #2391 
Fixes #2392
=> Bug bashing fixes for qasm support

vscode/src/azure/commands.ts, vscode/src/azure/networkRequests.ts, vscode/src/azure/treeView.ts, vscode/src/azure/workspaceActions.ts, vscode/src/copilot/azqTools.ts, vscode/src/gh-copilot/tools.ts
For targets coming online, the providerId is not necessarily the first part of the target string up to the first ".". Thus, saving the providerId along with the target (which is easier than having each child node store a reference to it's parent also)
=> Don't use the start of the target as the provider id

vscode/src/notebook.ts
Removing overriding the cell language base on openqasm magic until we can get it merged upstream in vscode-jupyter like we did for %%qsharp. Since openqasm isn't recognized it marks the cell unable to run
=> Remove cell language override

compiler/qsc_eval/src/lib.rs, compiler/qsc_fir/src/fir.rs, compiler/qsc_lowerer/src/lib.rs, vscode/src/debugger/session.ts, wasm/src/debug_service.rs
This change updates the behavior of `fail` expressions during debugging such that they trigger a new kind of `StepResultId` that propagates up into the extension and will cause a debug session to stop just before the failure is processed.
https://github.com/user-attachments/assets/30d11954-d9b4-460d-8a7a-ef5dfdb1b2f6
=> Break on `fail` during debugging

compiler/qsc_qasm/src/ast_builder.rs, compiler/qsc_qasm/src/compiler.rs, compiler/qsc_qasm/src/semantic/tests/statements.rs, compiler/qsc_qasm/src/semantic/tests/statements/reset_stmt.rs, compiler/qsc_qasm/src/tests/statement/reset.rs
Implements broadcast for resetting qubits. Any qubit registers are passed to `ResetAll` so that we don't have to generate many reset calls in the AST.
=> Add reset broadcast

compiler/qsc_qasm/src/ast_builder.rs, compiler/qsc_qasm/src/compiler.rs, compiler/qsc_qasm/src/tests/fuzz.rs
=> bitstring processing is more efficient

Cargo.toml, compiler/qsc/Cargo.toml, pip/Cargo.toml, pip/src/interpreter.rs, resource_estimator/Cargo.toml, wasm/Cargo.toml
This change updates the way we pull features for miette such that the wasm crate preserves the ASCII-based "fancy-no-syscall" behavior needed for broader extension/web compatibility, while allowing the native pip crate to use full "fancy" and have colors and symbols for improved readability.
Before:
After:
Existing behavior (and reduced dependencies) preserved in VS Code:
Fixes #1898
=> Restore fancy error reporting in Python

npm/qsharp/ux/qsharp-circuit.css
Made some suggested changes to the color schemes of some of the details in the Circuit Editor:
- The disabled "OK" button now uses the same colors as other buttons and just uses an opacity to indicate its unavailability.
- The default color for button boarders is now transparent so if a theme doesn't define a border color, boarders do not appear.
- The argument on gates will remain underlined and have the "clickable" cursor on hover, but the color will not be hyperlink blue as that did not mesh well with certain themes. The color is now the same as the regular text color.
=> Updates some of the CSS colors for Circuits

compiler/qsc/src/interpret/tests.rs, compiler/qsc_linter/src/lint_groups.rs, compiler/qsc_linter/src/lints/ast.rs, compiler/qsc_linter/src/tests.rs, compiler/qsc_passes/src/common.rs, compiler/qsc_passes/src/index_assignment.rs, compiler/qsc_passes/src/index_assignment/tests.rs, compiler/qsc_passes/src/lib.rs, compiler/qsc_passes/src/loop_unification.rs, vscode/qsharp.schema.json
This PR supports array syntax as described in #2378.
```qsharp
arr[0][1][2] = 3
```
gets transformed in the HIR to
```qsharp
arr w/= 0 <- (arr[0] w/ 1 <- (arr[0][1] w/ 2 <- 3))
```
This allows user to not have to use the `w/=` syntax to update arrays. This also supports range expressions for the index. It is also careful to make sure the index expressions are only evaluated once and in order.
This PR also adds lints for discouraging the use of `w/=` and `w/` syntax, with a code action for the `w/=` to convert it to the new syntax here. Both of those lints are set to `Allow` by default, but can be changed to `Warn` in the future.
This also supports compound assignment operators, so you can do `arr[0][1][2] += 3` and it will be converted to the new syntax.
=> Support Array Update Syntax

library/std/src/Std/Diagnostics.qs
=> DumpOperation doesn't need its argument to have an adjoint

compiler/qsc_doc_gen/src/generate_docs.rs, compiler/qsc_doc_gen/src/generate_docs/tests.rs
As requested by the doc team, they now have a script that will add the `ms.topic` field with a value that they determine, so we shouldn't generate `ms.topic` fields.
=> Drop `ms.topic` Metadata Field for all Non-Index Doc Files

samples_test/build.rs, samples_test/src/tests.rs, samples_test/src/tests/OpenQASM.rs
This change adds auto-generated Rust unit tests for executing each of the files in samples/OpenQASM/*.qasm. Like with the other sampels tests, the expect entries corresponding to newly introduced samples should be added manually while the test infra in the OpenQASM_generated.rs file is created at build time.
=> Add unit tests for OpenQASM samples

compiler/qsc_qasm/src/semantic/tests/expression/binary/arithmetic_conversions.rs, compiler/qsc_qasm/src/semantic/types.rs, compiler/qsc_qasm/src/tests/statement/const_eval.rs
This PR fixes an issue in casting where the following code was treated as an error. 
```
int x = 5;
int y = 2 * x;
```
The issue was that `2` is a constant, and the casting system wasn't allowing `x`, of type `int`, which isn't a constant to be cast to the type of `2`, which is `const int`. The fix consists in allowing the type of the binary expression as a whole to be demoted to a non-const type.
=> Allow implicit cast to non-const in binary exprs.

vscode/src/circuit.ts, vscode/src/copilot/azqTools.ts, vscode/src/estimate.ts, vscode/src/gh-copilot/qsharpTools.ts, vscode/src/language-service/activate.ts, vscode/src/language-service/completion.ts, vscode/src/language-service/format.ts, vscode/src/programConfig.ts, vscode/src/qirGeneration.ts, vscode/src/telemetry.ts, vscode/src/webviewPanel.ts
This adds a `documentType` property to relevant telemetry events to differentiate between the various language types we now support.
=> Add documentType to telemetry events

compiler/qsc_frontend/src/resolve.rs, compiler/qsc_frontend/src/resolve/tests.rs, compiler/qsc_frontend/src/typeck/tests.rs
This fixes a long hidden bug where using explicit types in a for loop (technically supported because the loop binding variable is parsed as a pattern just like bindings for let-stmts and callable params) would cause the type for the binding to be unknown and propagate as an error type through the code.
=> Fix explicit types in for loops

compiler/qsc_rir/src/passes/ssa_transform.rs, compiler/qsc_rir/src/passes/ssa_transform/tests.rs
This fixes a bug reported by @cesarzc where a program that used a dynamic value that remains unchanged across predecessor branches can result in incorrect SSA transform.
=> Fix SSA Pass panic when propagating dynamic values through multiple branches

compiler/qsc_qasm/src/semantic/lowerer.rs, compiler/qsc_qasm/src/tests/declaration/def.rs, compiler/qsc_qasm/src/tests/declaration/gate.rs, compiler/qsc_qasm/src/tests/statement/const_eval.rs
The following program was failing to compile because the `1` on the lhs of the `<<` expression was being lowered as an `int`, and the qasm spec does not define bit shifts for ints. The fix consists in lowering the literal as a `uint` instead, which is allowed by the spec.
```
const int a = 1 << 5;
def const_evaluation_context() {
int b = a;
}
```
=> Fix bit shifts with bit literals on lhs

compiler/qsc_eval/src/tests.rs, compiler/qsc_lowerer/src/lib.rs
Assignments are expressions that should result in unit, but they don't push unit into the exec graph, which can cause problems if those expressions have their results bound to some other variable or expression.
=> Fix panic due to missing `Unit` value from assignment

vscode/syntaxes/openqasm.tmLanguage.json
The keyword `gate` isn't being highlighted in .qasm files. This PR adds `gate` to the list of keywords in the `openqasm.tmLanguage.json` file to ensure that it is properly highlighted.
=> Add `gate` to qasm tmLanguage file

vscode/src/memfs.ts
Added OpenQASM samples into the VSCode Playground
- OpenQASM samples added to "Samples (OpenQASM)" folder
- Existing folder with Q# samples is renamed to "Samples (Q#)"
=> Added OpenQASM samples into the VSCode Playground

resource_estimator/src/estimates/error.rs, resource_estimator/src/estimates/error_correction.rs, resource_estimator/src/estimates/factory.rs, resource_estimator/src/estimates/factory/dispatch.rs, resource_estimator/src/estimates/factory/empty.rs, resource_estimator/src/estimates/factory/round_based.rs, resource_estimator/src/estimates/layout.rs, resource_estimator/src/estimates/physical_estimation.rs, resource_estimator/src/estimates/physical_estimation/estimate_frontier.rs, resource_estimator/src/estimates/physical_estimation/estimate_without_restrictions.rs, resource_estimator/src/estimates/physical_estimation/result.rs, resource_estimator/src/system/data/logical_counts.rs, resource_estimator/src/system/optimization/code_distance_iterators.rs, resource_estimator/src/system/optimization/tfactory_exhaustive.rs, resource_estimator/src/system/tests.rs
This changes return types for methods in the `Overhead` and `FactoryBuilder` trait from `T` to `Result<T, resource_estimator::estimates::Error>`.
No implementation of this `Overhead` and `FactoryBuilder` trait returns an error; therefore, the behavior of RE for the default system architecture does not change. However, when implementing the traits to extend the resource estimator, the new signature allows more flexibility and allows users of the implementation to see errors.
=> Allow to catch and propagate errors in all resource estimation models

npm/qsharp/src/workers/common.ts, vscode/src/gh-copilot/tools.ts
This way we can keep an eye on how various use cases and instructions files affect the token budget for our tools.
While this number doesn't give us true visibility into the internals of Copilot, like the global token budget, it may at least act as a rough indicator of how much context we're eating up.
Some numbers I gathered to help paint a picture:
- We seem to get about ~43000 tokens in our budget for each tool call. Every message in the conversation history seems to reduce this budget, but not by much - by about 2
- When we include our Q# instructions file in the context, the token budget seems to decrease about ~500 tokens
- Claude talks more than GPT 4.1, thereby reducing our budget slightly 🙄 
- A typical short output, like the circuit from a Bell state program) takes up ~200 …
=> Log token budget and usage for Copilot tools

version.py
Simple utility to make bumping the version before release easy. Just run with something like `./version.py --set 1.18.1` to bump in all the necessary places.
=> Add --set option to version.py

.github/workflows/fuzz.yml
Now that the fuzzer consistently runs on any merge to main that edits the compiler (#498), we don't really need the scheduled runs.
=> Remove scheduled fuzzer runs

samples/algorithms/Grover.qs
Updated comments in the Grover search sample to clarify what we are searching for. In this particular case we are looking for the marked state |01010⟩. I still think we should keep this sample simple by looking for a specific state represented by a hard-coded operation rather than somehow providing arbitrary marked state as a parameter.
=> Clarified search goal in the Grover sample comments

compiler/qsc_frontend/src/compile.rs, compiler/qsc_frontend/src/compile/preprocess.rs, compiler/qsc_frontend/src/compile/preprocess/tests.rs, compiler/qsc_project/src/project.rs
This adds a de-spanning pass to the compiler to remove the spans for the contents of operations defined via circuit files. The operation declarations themselves retain their spans to support LS features, but the statements in the body of the operations are de-spanned. This prevents the debugger from stepping into the circuit files.
=> Prevent Stepping into Circuit Files during Debug

resource_estimator/src/estimates/error_correction.rs, resource_estimator/src/estimates/physical_estimation.rs
This adds an EC trait function to provide the possibility to adjust the code parameter after it has been computed. This is required for special EC functionality through the extensibility API. The default implementation of the trait function returns the original code parameter and the EC implementation inside the QDK does not change that function.
=> Add EC trait function to adjust code parameter after selection

samples/algorithms/PhaseEstimation.qs, samples_test/src/tests/algorithms.rs
This is a more complex quantum phase estimation sample. It is not suitable for base profile.
=> Quantum Phase estimation sample via ApplyQPE

resource_estimator/src/estimates/error.rs, resource_estimator/src/estimates/physical_estimation.rs
Resolves [security alert 390](https://github.com/microsoft/qsharp/security/code-scanning/390) by returning an error, when the logical depth scaling factor is less than 1.0.
=> Implement error handling for invalid logical depth scaling

compiler/qsc_project/src/openqasm.rs, compiler/qsc_qasm/src/parser.rs, compiler/qsc_qasm/src/semantic/error.rs, compiler/qsc_qasm/src/semantic/lowerer.rs, compiler/qsc_qasm/src/semantic/symbols.rs, compiler/qsc_qasm/src/tests/statement/gate_call.rs
This PR adds promotion of OpenQASM 2.0 programs into OpenQASM 3.0 with some caveats
- Global phase is not adjusted so any OpenQASM 2.0 programs will have OpenQASM 3.0 global phase
- Opaque gates are not parsed. Any OpenQASM 2.0 programs with them will have parser errors. This concept was not migrated to OpenQASM 3.0
- OpenQASM 2.0 programs can import `"qelib1.inc"` and trying to import `"stdgates.inc"` will give an error.
=> Adding support for QASM 2.0 in the OpenQASM compiler

compiler/qsc_qasm/src/semantic/lowerer.rs, compiler/qsc_qasm/src/semantic/tests.rs, compiler/qsc_qasm/src/semantic/tests/lowerer_errors.rs, compiler/qsc_qasm/src/tests/statement/gate_call.rs, compiler/qsc_qasm/src/tests/statement/implicit_modified_gate_call.rs, compiler/qsc_qasm/src/tests/statement/modified_gate_call.rs, library/std/src/Std/OpenQASM/Intrinsic.qs, vscode/test/suites/debugger/openqasm.test.ts
In the original implementation of the OpenQASM compiler, gates with implicit modifiers needed to be specially handled by redefining them as their unmodiefied variants and collecting the modifier. For example, `ch` would be converted to `h` with a `ctrl(1)` modifier and would be used to build up the gate call with the additional explicit modifiers.
With the introduction of the `Std.OpenQASM` library, we can now call those gates directly without needing to decompose them. This also cleans up error messages as any errors would have been associated with the unmodified gate name prior.
=> Remove implicit modifier handling during OpenQASM lowering

source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/angle.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/bit.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/bool.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/complex.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/creg.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/duration.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/float.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/int.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/uint.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_angle.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_bit.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_bool.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_complex.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_duration.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_float.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_int.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/explicit_cast_from_uint.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/implicit_cast_from_bitarray.rs, source/compiler/qsc_qasm/src/tests/expression/explicit_cast_from_duration.rs
The span in the get_default_value() function in lowerer.rs wasn't being used. This PR fixes that.
=> Fix default value span

source/compiler/qsc/src/interpret.rs, source/compiler/qsc_eval/src/lib.rs, source/npm/qsharp/src/debug-service/debug-service.ts, source/vscode/src/debugger/session.ts, source/vscode/test/suites/debugger/openqasm.test.ts, source/vscode/test/suites/debugger/qsharp.test.ts, source/vscode/test/suites/debugger/test-workspace/self-contained.qasm, source/vscode/test/suites/debugger/test-workspace/src/foo.qs, source/vscode/test/suites/debugger/tracker.ts, source/wasm/src/debug_service.rs
Fixes #2494 
This PR modifies the debugger behavior to show local variables for the selected stack frame when debugging.
=> Show local variables of selected frame when debugging.

library/std/src/Std/Diagnostics.qs, source/compiler/qsc_fir/src/fir.rs, source/compiler/qsc_lowerer/src/lib.rs, source/compiler/qsc_partial_eval/src/lib.rs, source/compiler/qsc_partial_eval/src/tests/calls.rs, source/compiler/qsc_partial_eval/src/tests/intrinsics.rs, source/compiler/qsc_passes/src/capabilitiesck.rs, source/compiler/qsc_rca/src/core.rs, source/compiler/qsc_rca/src/tests/callables.rs
This change creates a special exception for callables annoted with `@Test` in Runtime Capabilities Analysis, making it easier to write and run unit tests with profiles other than "Unrestricted." As part of this change, the `CheckZero`, `CheckAllZero`, and `CheckOperationsAreEqual` callables are no longer marked as `@Config(Unrestricted)` so that they can be used from tests. Any calls into these will trigger updated codegen error cases. In addition, calls into `@Test` callables also trigger a new codegen-time error.
Fixes #2504
=> Allow unrestricted capabilities in `@Test` callables

library/src/lib.rs, library/std/qsharp.json, library/std/src/Std/OpenQASM/Builtin.qs, source/compiler/qsc_qasm/src/ast_builder.rs, source/compiler/qsc_qasm/src/compiler.rs, source/compiler/qsc_qasm/src/semantic/ast.rs, source/compiler/qsc_qasm/src/semantic/const_eval.rs, source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/semantic/tests.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/builtin_functions.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/builtin_functions/sizeof.rs, source/compiler/qsc_qasm/src/semantic/types.rs, source/compiler/qsc_qasm/src/semantic/types/tests.rs, source/compiler/qsc_qasm/src/tests/expression.rs, source/compiler/qsc_qasm/src/tests/expression/builtin_functions.rs, source/compiler/qsc_qasm/src/tests/expression/builtin_functions/sizeof_array.rs, source/compiler/qsc_qasm/src/tests/expression/builtin_functions/sizeof_dyn_array_ref.rs, source/compiler/qsc_qasm/src/tests/expression/builtin_functions/sizeof_static_array_ref.rs, source/compiler/qsc_qasm/src/tests/expression/implicit_cast_from_array.rs, source/compiler/qsc_qasm/src/types.rs
This PR adds support for the `sizeof` builtin to OpenQASM. As part of the necessary things to make `sizeof` work in all supported cases, it also adds support for `readonly array[_, ...]` input types in subroutines.
=> Add sizeof bultin to qasm

source/vscode/src/common.ts
Following in the footsteps of #1754 and #1867, this ignores files with the `review` scheme to avoid spurious language service errors on the left-hand side of a diff when reviewing a PR locally checked out with the GitHub Pull Requests extension.
=> Skip errors on files with `review` URI scheme

source/compiler/qsc_qasm/src/ast_builder.rs, source/compiler/qsc_qasm/src/compiler.rs, source/compiler/qsc_qasm/src/parser/ast.rs, source/compiler/qsc_qasm/src/parser/scan.rs, source/compiler/qsc_qasm/src/parser/stmt.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/annotation.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/extern_decl.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/for_loops.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/if_stmt.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/quantum_decl.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/while_loops.rs, source/compiler/qsc_qasm/src/semantic/ast.rs, source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/tests/expression/function_call.rs, source/compiler/qsc_qasm/src/tests/output.rs, source/compiler/qsc_qasm/src/tests/statement/annotation.rs, source/compiler/qsc_qasm/src/tests/statement/gate_call.rs, source/pip/tests-integration/interop_qiskit/resources/custom_intrinsics.inc
This PR fixes annotation parsing and renames existing annotations to comply better with namespaced intent from the spec. The old annotation names have been preserved for backwards compatibility but should be removed in the future.
- `@SimulatableIntrinsic` is now `@qdk.qir.intrinsic`
- `@Config` is now `@qdk.qir.profile`
=> Annotations should now be parsed correctly

source/compiler/qsc_qasm/src/ast_builder.rs, source/compiler/qsc_qasm/src/compiler.rs, source/compiler/qsc_qasm/src/parser/ast.rs, source/compiler/qsc_qasm/src/parser/scan.rs, source/compiler/qsc_qasm/src/parser/stmt.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/cal.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/defcal.rs, source/compiler/qsc_qasm/src/parser/stmt/tests/invalid_stmts/cal.rs, source/compiler/qsc_qasm/src/semantic/ast.rs, source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/semantic/resources/openqasm_compiler_errors_test.qasm, source/compiler/qsc_qasm/src/semantic/resources/openqasm_lowerer_errors_test.qasm, source/compiler/qsc_qasm/src/semantic/tests.rs, source/compiler/qsc_qasm/src/semantic/tests/compiler_errors.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/builtin_functions/sizeof.rs, source/compiler/qsc_qasm/src/semantic/tests/lowerer_errors.rs, source/compiler/qsc_qasm/src/semantic/tests/statements/box_stmt.rs, source/compiler/qsc_qasm/src/semantic/tests/statements/break_stmt.rs, source/compiler/qsc_qasm/src/semantic/tests/statements/continue_stmt.rs, source/compiler/qsc_qasm/src/types.rs
This PR moves errors from the lowerer to the compiler for errors that are strictly associated with the QDK's unsupported OpenQASM features. As as side effect:
- Unified parsed string handling in `Arc`'s
- Removed dead code
- Added `cal` and `defcal` bodies to parsed and semantic ASTs
- Moved Unsupported errors from lowerer to compiler
There is one bit that is a little annoying. When fixing the function/callable/def type to track the args and return type, we now have a scenario where the symbol doesn't have the correct type information. Before, we pulled the return type from the def stmt instead of the symbol. Now, we pull the return type from the symbol ty, but in cases where this shadowing happens, we set the ty to `Err` since we don't have the correct type. We can either put the return …
=> Separate lowerer and compiler errors

source/vscode/src/azure/workspaceActions.ts
Switch the default job output format to v2 when submitting jobs from VS Code.
This matches the Python behavior introduced in https://github.com/microsoft/azure-quantum-python/pull/617/files#diff-48e91f4c7742aff9a2787763a2e97e5b3c56552787ca499b4bc45d6b0815d8c0
=> Switch the default reporting format to v2

source/language_service/src/completion/tests.rs, source/language_service/src/completion/tests/class_completions.rs, source/language_service/src/completion/tests/openqasm.rs
In anticipation of some bugfixes I'm making in this area, I wanted to clean up the unit tests a bit, so that the upcoming PR is less headache-inducing.
Changing how we format the expected output in completions tests. This way:
- They're more readable
- There's less churn when sort texts change due to unrelated changes, (e.g. [this PR](https://github.com/microsoft/qsharp/pull/2345/files#diff-474255c7ce3b4fd2763734186079ae268564b2bc4f9377c266de1ed6e8f9df65)). _Relative_ order is still validated, but the exact sort text (e.g. "`0300DumpMachine`") is not.
=> Update expect formatting in unit tests to be more readable

source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/tests/assignment.rs
There was casting bug when trying to do
```
angle[8] a;
a <<= 1;
```
The issue was that assign-op expressions like `a <<= 1;` should be lowered as
```a = cast_to_type_of_lhs(a << 1);```
But they were being lowered as
```a = a << cast_to_type_of_lhs(1);```
=> Fix lowering of OpenQASM assign-op statements

source/pip/qsharp/_qsharp.py, source/pip/qsharp/openqasm/_run.py, source/pip/qsharp/telemetry_events.py
This adds two Booleans to show whether `qsharp.run` or `qsharp.openqasm.run` were invoked with noise and/or qubit loss. The bools show up in the custom data along with the bucketized shot count.
=> Add noise telemetry to `qsharp.run`

source/compiler/qsc/src/qasm.rs, source/compiler/qsc_qasm/src/compiler.rs, source/compiler/qsc_qasm/src/compiler/error.rs, source/compiler/qsc_qasm/src/lib.rs, source/compiler/qsc_qasm/src/tests.rs, source/compiler/qsc_qasm/src/tests/declaration.rs, source/compiler/qsc_qasm/src/tests/expression/function_call.rs, source/compiler/qsc_qasm/src/tests/fuzz.rs, source/compiler/qsc_qasm/src/tests/output.rs, source/compiler/qsc_qasm/src/tests/statement/gate_call.rs, source/compiler/qsc_qasm/src/tests/statement/pragma.rs, source/compiler/qsc_qasm/src/tests/statement/pragma/box.rs, source/compiler/qsc_qasm/src/tests/statement/pragma/profile.rs, source/compiler/qsc_qasm/src/tests/statement/reset.rs, source/fuzz/fuzz_targets/qasm.rs, source/language_service/src/compilation.rs, source/language_service/src/completion/tests/openqasm.rs, source/language_service/src/state.rs, source/pip/src/interop.rs, source/pip/src/interpreter.rs, source/samples_test/src/tests.rs, source/wasm/src/debug_service.rs, source/wasm/src/lib.rs, source/wasm/src/project_system.rs
Adds the `#pragma qdk.qir.profile` pragma to our QASM compiler. This pragma is used to specify the profile to compile the QASM file with, i.e. `#pragma qdk.qir.profile Base` to have the file compile with the `Base` profile. QASM files are always compiled with the profile specified by their source with this pragma. If no pragma is provided, the compilation will default to `Unrestricted`.
The PR is built on top of and relies on #2591
=> QASM Profile Pragma

source/npm/qsharp/src/browser.ts, source/npm/qsharp/src/compiler/compiler.ts, source/npm/qsharp/src/project.ts, source/playground/src/editor.tsx
Profile selection in the playground will now default to adaptive_rif for qir gen.
It will also properly search the user code for a profile specification via the EntryPoint argument.
=> Playground Profile Selection

source/vscode/test/suites/debugger/openqasm.test.ts, source/vscode/test/suites/debugger/qsharp.test.ts, source/vscode/test/suites/debugger/tracker.ts
Fixed a race condition in the Q# and OpenQASM debugger integration tests that was causing intermittent test failures.
**Problem:**
- Tests were racing with VS Code's automatic debugger state requests
- When the debugger paused, both the test code and VS Code would send `scopes` and `variables` requests
- Depending on timing, tests could receive responses to VS Code's requests instead of their own
- This resulted in reading variables from the wrong stack frame and assertion failures
**Changes:**
- **Modified test logic**: Tests now wait for debugger pause state before making their own requests
- **Improved request tracking**: Added `waitUntilResponse()` method to track specific command responses
- **Dynamic variable references**: Tests now dynamically retrieve variable references from …
=> Fix race condition in VS Code debugger integration tests

source/compiler/qsc_qasm/src/parser/expr.rs, source/compiler/qsc_qasm/src/parser/prgm.rs, source/compiler/qsc_qasm/src/tests/statement.rs, source/compiler/qsc_qasm/src/tests/statement/version.rs
The `OPENQASM` statement parser would accept arbitrary expressions as valid versions. This PR changes that behavior to push an error in the non-valid cases.
=> Fix parsing of OPENQASM version statement

source/compiler/qsc/src/lib.rs, source/compiler/qsc_frontend/src/compile.rs, source/compiler/qsc_frontend/src/incremental.rs, source/compiler/qsc_frontend/src/resolve.rs, source/compiler/qsc_frontend/src/resolve/tests.rs, source/language_service/src/compilation.rs, source/language_service/src/completion.rs, source/language_service/src/completion/global_items.rs, source/language_service/src/completion/locals.rs, source/language_service/src/completion/qsharp.rs, source/language_service/src/completion/tests.rs, source/language_service/src/test_utils.rs
This pull request refactors the completion logic for imports and exports to be more robust and accurate.
The completion provider in the language service (`global_items.rs`) has been rewritten to leverage the `GlobalScope` and `Locals` structs already available from the resolver. This allows completions to use the same "view" as the name resolution code, rather than trying to recreate it by manually analyzing imports, enumerating items, etc. All of that work has already been done by the resolver.
The previous implementation for completions had difficulty handling more complex import and export scenarios, such as items re-exported from dependencies or items under aliased namespaces. This could lead to incomplete or incorrect suggestions. The new approach provides a more solid foundation, …
=>  Fix completions for import and exports

source/compiler/qsc_qasm/src/compiler.rs, source/compiler/qsc_qasm/src/semantic/error.rs, source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/semantic/resources/openqasm_lowerer_errors_test.qasm, source/compiler/qsc_qasm/src/semantic/tests/decls.rs, source/compiler/qsc_qasm/src/semantic/tests/decls/alias.rs, source/compiler/qsc_qasm/src/semantic/tests/lowerer_errors.rs, source/compiler/qsc_qasm/src/tests/assignment/alias.rs
This PR sets up the main uses of [alias statements](https://openqasm.com/language/types.html#aliasing) for qubit registers. 
- Lowers aliasing of qubit and bitarray registers
- Compilation (to Q# ast) fails when used with bitarray registers. This is a known limitation until we decide we want to dig into it. The naive implementation requires reference variables. We can do qubits as they are virtual ids
- Validates type information in lowering raising semantic errors if the aliases aren't type sound.
- There is a stub test case for when we support index sets as part of aliasing
=> Add support for qubit alias decls

source/language_service/src/definition.rs, source/language_service/src/definition/tests.rs, source/language_service/src/hover.rs, source/language_service/src/name_locator.rs, source/language_service/src/references.rs, source/language_service/src/references/tests.rs, source/language_service/src/rename.rs, source/language_service/src/rename/tests.rs
Adds Go To Definition, Hover, Go To References, Rename support for import/export declarations. Also, for References and Rename, results when these commands are invoked on any items, now include any import/export declarations.
- Go To Definition on any imports/exports, and any usages of those imports/exports, resolve back to the original item.
- Hover shows hover info of original item.
- Go To References finds references to an item including any imports, exports, and usages across packages, including any aliased usages.
- Rename renames the declaration and usages, as long as they match the alias that the cursor is on.
=> Definition, References, Hover, Rename for import/export decls

source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/semantic/tests/expression/implicit_cast_from_float.rs, source/compiler/qsc_qasm/src/semantic/types.rs
Existing Qiskit code compiles to qasm that adds and subtracts floats and angles, which isn't spec compliant. This PR allows those operations to make Qiskit work.
=> Support `+` an `-` bin-ops for float and angle to make existing Qiskit code work

source/vscode/src/config.ts
Silly mistake - this setting name doesn't match what's declared in package.json at https://github.com/microsoft/qsharp/blob/47e1c8e20d1e1887ca82548da240ed25d2141130/source/vscode/package.json#L148
=> Fix config key for upload supplemental data

source/compiler/qsc_qasm/src/semantic/lowerer.rs, source/compiler/qsc_qasm/src/semantic/types/tests.rs, source/compiler/qsc_qasm/src/tests/expression/indexed.rs, source/compiler/qsc_qasm/src/tests/fuzz.rs
We were trying to detect if a step in a const range was zero by manually inspecting the `step` expression before being const evaluated. This only works if the `step` expr is the `0` literal, but it won't work if it is a const-expression evaluating to zero. This PR changes that logic to check the `step` value after being const-evaluated.
Fixes #2702
=> [OpenQASM]: Properly detect zero step in const ranges

library/src/tests/resources/src/select.qs, library/src/tests/table_lookup.rs, library/std/src/Std/TableLookup.qs
This check-in improves implementation of adjoin variant of Select operation (Unlookup operation). Previously it was based on May [2019 paper by Craig Gidney](https://arxiv.org/abs/1905.07682), and this proposed implementation is based on [2025 paper by Craig Gidney](https://arxiv.org/abs/2505.15917).
The implementation of Unlookup is measurement-based with phase correction via Phase Lookup operation described in the aforementioned paper. Phase Lookup is implemented by splitting address register and computing power products for both halves. Then the necessary phase corrections are applied and power products are uncomputed.
This implementation uses fast Boolean Mobius transform instead of matrix multiplication as in the paper to convert classical data from truth table representation to …
=> Improved adjoint Select implementation
