- .ado/publish.yml
A fix for the previous PR #424.
> Disable PR build triggering.

- Cargo.lock
> Fixing proc-macro2 version bug for nightly builds.

- library/std/canon.qs
- library/tests/src/tests.rs
Ported ApplyControlledOnBitString and added a test.
> Added ApplyControlledOnBitString

- compiler/qsc_passes/src/spec_gen.rs
- compiler/qsc_passes/src/spec_gen/tests.rs
> Generate node ID for `controlled adjoint`

- npm/src/browser.ts
- vscode/src/extension.ts
Fix wasm logging initialization and correct log levels.
> Fix WASM logging for VS Code language service

- samples/language/RepeatUntilLoops.qs
Fixes the Repeat-Until Loop sample.
Part of Issue #554
> Fix Repeat-Until Loop Sample

- katas/content/multi_qubit_measurements/index.md
- katas/content/multi_qubit_systems/index.md
- katas/content/oracles/index.md
- katas/content/qubit/index.md
- katas/content/random_numbers/index.md
- katas/content/single_qubit_gates/index.md
- katas/content/single_qubit_measurements/index.md
All tutorials now include overview with the list of covered subjects and the list of prerequisites. I.e. the following sections:
**This tutorial covers the following topics**
**What you should know to start working on this tutorial**
(Didn't touch Multi-Qubit gates to avoid conflicts)
> Unified tutorial overviews to include TOC and prerequisites

- compiler/qsc/src/lib.rs
- compiler/qsc_eval/src/output.rs
- npm/src/debug-service/debug-service.ts
- pip/src/displayable_output.rs
- vscode/src/debugger/session.ts
- wasm/src/debug_service.rs
This is a first cut. Follow up PRs can make the list view load with paging.
> Adding quantum state to variables view.

- build.py
Adhere to the same patterns that build.py already has.
> Separate building samples from running tests

- compiler/qsc_eval/src/tests.rs
- compiler/qsc_frontend/src/resolve.rs
> Copy and Update Assign with UDT Field doesn't recognize Field Name

- compiler/qsc_parse/src/item.rs
> Doc-comments confuse `%%qsharp` cells

- compiler/qsc/src/interpret/debug/tests.rs
- compiler/qsc_eval/src/tests.rs
- compiler/qsc_frontend/src/compile.rs
- compiler/qsc_frontend/src/compile/tests.rs
- compiler/qsc_parse/src/expr.rs
- compiler/qsc_parse/src/lib.rs
- compiler/qsc_passes/src/baseprofck/tests.rs
- compiler/qsc_passes/src/borrowck/tests.rs
Fixes errors at EOF getting mapped to the wrong source file (#610)
Bonus discovery: Fix entry expression parsing
> Fixes reporting of errors at the end of a source file

- compiler/qsc_frontend/src/typeck/rules.rs
- compiler/qsc_frontend/src/typeck/tests.rs
> Type Checking does not ensure Integer Argument for Bitwise NOT

- compiler/qsc_frontend/src/resolve.rs
- compiler/qsc_frontend/src/resolve/tests.rs
This change adds logic to avoid shadowing bindings within the same pattern, as well as bindings between a callable declaration and a controlled specialization.
Fixes #665
> Parameters Should Not Shadow Earlier Parameters in the Same Signature

- version.py
It simplifies the script somewhat too.
It does mean you'll need to ensure you set the BUILD_NUMBER variable when running the pipeline.
> Fix versioning to match https://github.com/microsoft/qsharp/issues/8

- vscode/package.json
- vscode/src/azure/commands.ts
- vscode/src/azure/providerProperties.ts
- vscode/src/azure/treeView.ts
- vscode/src/azure/workspaceActions.ts
- vscode/src/extension.ts
Show all targets and providers (if not explicitly excluded), and only allow job submission on QIR-supporting targets, and downloads for jobs with results.
> Better target filtering and command handling

- compiler/qsc/src/interpret/stateful.rs
- compiler/qsc_frontend/src/compile/preprocess.rs
- compiler/qsc_frontend/src/incremental.rs
- compiler/qsc_frontend/src/incremental/tests.rs
- compiler/qsc_frontend/src/resolve.rs
> `@Config` attributes not processed in incremental compiler

- compiler/qsc/src/interpret/stateful/tests.rs
- compiler/qsc_codegen/src/qir_base.rs
- compiler/qsc_codegen/src/qir_base/tests.rs
- pip/tests-qir/test_qir.py
This reverts commit 192368ca666ac37f8e97dc3a73e3e8efbff1da3f.
> Revert "Fixes a bug in single output recording (#692)"

- compiler/qsc/src/interpret/stateful/tests.rs
- compiler/qsc_frontend/src/compile.rs
> Renaming library files to have unique names

- version.py
- vscode/README-DEV.md
- vscode/README.md
- vscode/package.json
- vscode/src/extension.ts
> Update README and wording for extension

- package-lock.json
- package.json
- vscode/package.json
- vscode/src/telemetry.ts
The service is responding 200s and successfully ingesting! 
- switch to new key for telemetry ingestion
- upgrade `extension-telemetry` package to latest version
> switch aikey to devdiv ingestion key

- vscode/src/azure/commands.ts
- vscode/src/azure/networkRequests.ts
Fixes #690 
I left some commented out code for now in-case there's a 'more correct' check that just requires some tweaks, but will remove if one doesn't come up. (We'll remove all of this one the service API changes are in anyway).
> Early CORS warning

- vscode/src/qirGeneration.ts
> Show warning when QIR base profile is not set when submitting a job

- vscode/src/azure/treeView.ts
> Remove cost estimate from tooltip

- vscode/src/azure/commands.ts
This change updates the text document language used when opening downloaded job results to json. This enables syntax highlighting and formatting.
> Update language for job results

- katas/README.md
Acknowledge previous work and include a link to the previous repo.
Closes #552
> Added kata acknowledgement section

- vscode/src/azure/treeView.ts
> Show correct queue time

- samples/language/Specializations.qs
- samples/language/WithinApply.qs
This sample builds by default, but not if being built as an executable. This PR fixes that.
> Fix "Within Apply" and "Specializations" Sample for Exe Build

- vscode/src/azure/workspaceActions.ts
Fixes #727 
Also, fixed an issue where GUID generation was dropping chars (if a random byte was less than < 0x10).
> Fix repeated auth prompts and GUID generation

- vscode/src/azure/providerProperties.ts
> Update targets that support QIR

- package-lock.json
Flagged as 'high' during latest ADO pipeline run.
> Fix high pri dependency issue

- jupyterlab/yarn.lock
Supersedes #770, upgrading all dependencies instead of just postcss. Dependabot's change was causing build errors for some reason.
> Upgrade dependencies in jupyterlab/yarn.lock

- Cargo.toml
This change effects builds done in release mode only.
| Config | Build Time | wasm size | VSIX size | 
|--------|-----------|------------|-----------|
|Baseline| 10.33s | 1_956_260 | 1.43MB         |
| LTO = "fat" | 10.06s | 1_956_260 | |
|codegen-units = 1 | 9.22s | 1_689_371 | |
|codegen-units + lto | 9.25s | 1_686_366 | 1.38 MB |
```console
Teleport evaluation     time:   [88.789 µs 88.850 µs 88.919 µs]
Deutsch-Jozsa evaluation
time:   [22.011 ms 22.036 ms 22.066 ms]
Large file parity evaluation
time:   [34.175 ms 34.223 ms 34.278 ms]
Large input file        time:   [18.054 ms 18.113 ms 18.176 ms]
Standard library        time:   [7.6885 ms 7.7009 ms 7.7146 ms]
```
```console
Teleport evaluation     time:   [71.244 µs 71.294 µs 71.356 µs]
change: [-20.064% -19.844% -19.639%] (p = 0.00 < …
```
> Optimizing release builds with LTO and codegen-units updates

- compiler/qsc_frontend/src/compile/tests.rs
- compiler/qsc_frontend/src/typeck/infer.rs
- compiler/qsc_hir/src/hir.rs
> Typechecking doesn't support UDTs that reference other UDTs in the standard library

- Cargo.lock
- compiler/qsc/src/interpret/stateful/tests.rs
- compiler/qsc_codegen/Cargo.toml
- compiler/qsc_codegen/src/qir_base.rs
- compiler/qsc_codegen/src/qir_base/postfix.ll
- compiler/qsc_codegen/src/qir_base/tests.rs
- compiler/qsc_data_structures/src/index_map.rs
- library/std/intrinsic.qs
- pip/tests-qir/test_qir.py
This change updates base profile QIR codegen to conform to the specification by following additional requirements as outlined in #802.
Fixes #802.
> Conform to QIR Base Profile Spec

- compiler/qsc_eval/src/intrinsic.rs
- compiler/qsc_eval/src/intrinsic/tests.rs
- compiler/qsc_eval/src/lib.rs
> Add rotation angle validation in qsc_eval intrinsic functions

- samples/algorithms/DeutschJozsa.qs
- samples/algorithms/DeutschJozsaNISQ.qs
- samples/algorithms/QRNG.qs
- samples/algorithms/QRNGNISQ.qs
I changed `ranndom` to `random` in both files.
> Fix a typo in two samples

- package-lock.json
- package.json
Moving to 10.19.3 as it has my picture on it. (For a reason - it fixes the issue I hit when developing the widgets, https://github.com/preactjs/preact/pull/4219).
> Bump Preact

- vscode/src/statusbar.ts
> Updating UI and tooltip for target profile selection.

- compiler/qsc_passes/src/spec_gen.rs
- compiler/qsc_passes/src/spec_gen/tests.rs
> Design-Time Errors for Incorrect Functor Generators

- compiler/qsc/src/interpret/stateful.rs
- vscode/src/webviewPanel.ts
- wasm/src/lib.rs
- wasm/src/tests.rs
> Error from Qubit Released in Non-Zero State Causes Leak

- samples/algorithms/BellState.qs
- samples/algorithms/DeutschJozsaNISQ.qs
- samples/algorithms/QRNGNISQ.qs
> Update hardware samples to prefer `MResetZ` and `MResetEachZ`

- language_service/src/compilation.rs
Repro:
1. Have a folder with `qsharp.json`, `foo.qs` and `bar.qs`
2. In `foo.qs` (name matters because alphabetical order matters for this repro)
```qsharp
namespace Foo {
}
```
3. Open `foo.qs` which should be an empty file
4. Start typing `n` to bring up completion list, watch output log:
```
2024-01-02 15:21:16.319 [error] Failed to map all utf8 indexes. Remaining indexes are: 21
2024-01-02 15:21:16.320 [error] Failed to map all utf8 indexes. Remaining indexes are: 21
2024-01-02 15:21:16.320 [error] Failed to map all utf8 indexes. Remaining indexes are: 21
2024-01-02 15:21:16.320 [error] Failed to map all utf8 indexes. Remaining indexes are: 21
2024-01-02 15:21:16.320 [error] Failed to map all utf8 indexes. Remaining indexes are: 21
......etc......
```
The problem comes from the fact …
> Fix garbage offsets in completion list

- npm/src/language-service/language-service.ts
Just changing the severity of the log since we can actually hit this in practice.
Repro:
1. Create a new untitled file.
2. Change the language to Q#.
3. Type some bad Q# into the file to make errors show up.
4. Save the file to disk as `foo.qs`.
5. Observe the Output window for an error log.
The reason for this error is that the rename gets handled as a pair of events: `update_document`, under the new name, followed by `close_document` under the old name. The first event causes all the diagnostics to get republished, including the ones associated with the old name (this is where we log the error). The second event clears the diagnostics associated with the old name. Then all is good.
> Diagnostics event for closed document is not really an error

- Cargo.lock
I did not regenerate our lockfile after removing a Cargo.toml dependency, my bad. This PR contains the lockfile change.
> Regenerate lockfile after #980

- playground/src/main.tsx
- vscode/language-configuration.json
Fixes #812
Good news: This was a one line fix
Bad news: That one line was a regex
> Fix: @EntryPoint completion inserts two @ characters

- vscode/src/azure/commands.ts
- vscode/src/azure/networkRequests.ts
- vscode/src/azure/treeView.ts
- vscode/src/azure/workspaceActions.ts
Azure Quantum service errors:
Storage service errors:
Generic network errors:
Auth errors:
Failed job errors are now also included in the hover text:
> Surface service errors in the UI

- katas/content/multi_qubit_systems/common.qs
- katas/content/multi_qubit_systems/prepare_basis_state/verification.qs
- katas/content/multi_qubit_systems/prepare_superposition/index.md
- katas/content/multi_qubit_systems/prepare_superposition/solution.md
- katas/content/multi_qubit_systems/prepare_superposition/verification.qs
- katas/content/multi_qubit_systems/prepare_with_complex/index.md
- katas/content/multi_qubit_systems/prepare_with_complex/solution.md
- katas/content/multi_qubit_systems/prepare_with_complex/verification.qs
- katas/content/multi_qubit_systems/prepare_with_real/index.md
- katas/content/multi_qubit_systems/prepare_with_real/solution.md
- katas/content/multi_qubit_systems/prepare_with_real/verification.qs
Added better feedback to the Multi-Qubit Systems katas, and changed documentation to reflect little-endian format of `DumpMachine`.
Fixes #773
> Multi Qubit Katas

- compiler/qsc_project/src/js.rs
- jupyterlab/src/index.ts
- resource_estimator/src/estimates/modeling/logical_qubit.rs
- vscode/src/notebookTemplate.ts
- wasm/src/project_system.rs
I realized I had forgotted to add this to a few new files, so I went ahead and checked for others as well.
> Add missing copyright headers

- compiler/qsc_fir/src/fir.rs
This change includes blocks, statements, expressions and patterns when displaying a FIR store to help with debugging.
> More detailed FIR store display

- samples/estimation/Dynamics.qs
n = 10 illustrates the difficulty of the problem already. n= 30 is not necessary.
T factories qubits utilization is more significant for n = 10.
> change default n for quantum dynamics sample

- .ado/publish.yml
The issue at https://github.com/microsoft/vscode-vsce/issues/929 is fixed now. I just tested locally and appears to work. If we can merge this, I'll run a dev build and publish via ADO to verify.
> Unpin vsce

- npm/ux/estimatesOverview.tsx
- npm/ux/scatterChart.tsx
> RE add code distance to scatter chart label and connecting scatter circles

- CITATION.cff
- README.md
- resource_estimator/README.md
This closes #1128 by adding citations for Q#, Azure Quantum Development Kit, and Azure Quantum Resource Estimator
> Add citation information to the project

- katas/content/complex_arithmetic/Common.qs
- katas/content/complex_arithmetic/cartesian_to_polar/Placeholder.qs
- katas/content/complex_arithmetic/cartesian_to_polar/Solution.qs
- katas/content/complex_arithmetic/cartesian_to_polar/Verification.qs
- katas/content/complex_arithmetic/cartesian_to_polar/index.md
- katas/content/complex_arithmetic/cartesian_to_polar/solution.md
- katas/content/complex_arithmetic/complex_addition/index.md
- katas/content/complex_arithmetic/complex_division/index.md
- katas/content/complex_arithmetic/complex_modulus/index.md
- katas/content/complex_arithmetic/complex_multiplication/index.md
- katas/content/complex_arithmetic/index.md
- katas/content/complex_arithmetic/polar_multiplication/Placeholder.qs
- katas/content/complex_arithmetic/polar_multiplication/Solution.qs
- katas/content/complex_arithmetic/polar_multiplication/Verification.qs
- katas/content/complex_arithmetic/polar_multiplication/index.md
- katas/content/complex_arithmetic/polar_multiplication/solution.md
- katas/content/complex_arithmetic/polar_to_cartesian/Placeholder.qs
- katas/content/complex_arithmetic/polar_to_cartesian/Solution.qs
- katas/content/complex_arithmetic/polar_to_cartesian/Verification.qs
- katas/content/complex_arithmetic/polar_to_cartesian/index.md
- katas/content/complex_arithmetic/polar_to_cartesian/solution.md
> Finish Complex Arithmetic kata

- vscode/package.json
> Don't install all the browsers for integration tests

- playground/src/main.tsx
Enables the formatter to work with the playground.
> Enable Formatter Playground

- resource_estimator/src/estimates/factory.rs
- resource_estimator/src/estimates/factory/dispatch.rs
- resource_estimator/src/estimates/factory/empty.rs
- resource_estimator/src/estimates/physical_estimation/result.rs
I missed some headers in previous PRs. This PR adds them.
> Add license header to source files

- .eslintrc.cjs
- .prettierignore
Clean build works fine, but a rebuild will give you errors without these changes. Oops.
> Missed some files in the npm move

- Cargo.lock
- compiler/qsc/Cargo.toml
- compiler/qsc/src/codegen.rs
- compiler/qsc/src/interpret.rs
- compiler/qsc/src/interpret/tests.rs
- compiler/qsc/src/lib.rs
- compiler/qsc_codegen/src/qir.rs
- compiler/qsc_lowerer/src/lib.rs
- compiler/qsc_partial_eval/src/evaluation_context.rs
- compiler/qsc_partial_eval/src/lib.rs
- compiler/qsc_partial_eval/tests/test_utils.rs
- compiler/qsc_passes/src/lib.rs
- language_service/src/compilation.rs
- pip/tests/test_interpreter.py
- wasm/src/diagnostic.rs
Support for new QIR codegen for adaptive profile in Python.
> Using new QIR codegen for adaptive profile in Rust/Python

- katas/content/index.json
- katas/content/superposition/hardy_state/Placeholder.qs
- katas/content/superposition/hardy_state/Solution.qs
- katas/content/superposition/hardy_state/Verification.qs
- katas/content/superposition/hardy_state/index.md
- katas/content/superposition/hardy_state/solution.md
- katas/content/superposition/index.md
> Add Superposition task 2.5 (Hardy State)

- samples/algorithms/Teleportation.qs
Switched dumpMachine to dumpRegister to have one-qubit states #1388 @cesarzc
> switched to dumpregister

- katas/content/index.json
- katas/content/multi_qubit_gates/anti_controlled_gate/solution.md
- katas/content/superposition/index.md
- katas/content/superposition/parity_bitstrings/Placeholder.qs
- katas/content/superposition/parity_bitstrings/SolutionA.qs
- katas/content/superposition/parity_bitstrings/SolutionB.qs
- katas/content/superposition/parity_bitstrings/SolutionC.qs
- katas/content/superposition/parity_bitstrings/Verification.qs
- katas/content/superposition/parity_bitstrings/index.md
- katas/content/superposition/parity_bitstrings/solution.md
- katas/content/superposition/two_bitstrings/solution.md
> Adds Superposition task 1.14

- katas/content/index.json
- katas/content/superposition/index.md
- katas/content/superposition/wstate_power_of_two/Placeholder.qs
- katas/content/superposition/wstate_power_of_two/SolutionA.qs
- katas/content/superposition/wstate_power_of_two/SolutionB.qs
- katas/content/superposition/wstate_power_of_two/Verification.qs
- katas/content/superposition/wstate_power_of_two/index.md
- katas/content/superposition/wstate_power_of_two/solution.md
> Adds Superposition Task 2.6

- katas/content/index.json
- katas/content/superposition/even_odd/index.md
- katas/content/superposition/four_bitstrings/index.md
- katas/content/superposition/hardy_state/index.md
- katas/content/superposition/index.md
- katas/content/superposition/parity_bitstrings/index.md
- katas/content/superposition/wstate_arbitrary/Placeholder.qs
- katas/content/superposition/wstate_arbitrary/SolutionA.qs
- katas/content/superposition/wstate_arbitrary/SolutionB.qs
- katas/content/superposition/wstate_arbitrary/SolutionC.qs
- katas/content/superposition/wstate_arbitrary/Verification.qs
- katas/content/superposition/wstate_arbitrary/index.md
- katas/content/superposition/wstate_arbitrary/solution.md
- katas/content/superposition/wstate_power_of_two/SolutionA.qs
- katas/content/superposition/wstate_power_of_two/SolutionB.qs
- katas/content/superposition/wstate_power_of_two/index.md
Add the last task (2.7) from the classic Superposition kata, polish task names / descriptions for uniformity.
> Finish Superposition/Preparing quantum states kata

- compiler/qsc_rca/src/common.rs
- compiler/qsc_rca/src/core.rs
- compiler/qsc_rca/tests/loops.rs
This change fixes Runtime Capabilities Analysis (RCA) for repeat and while loops.
> Fix RCA for repeat and while loops

- samples/language/Array.qs
> Make Array.qs in /samples/language more user-friendly

- vscode/package.json
- vscode/src/codeLens.ts
- vscode/src/config.ts
- vscode/src/extension.ts
These features are now stable, so the opt-out setting can be removed.
> Remove feature enablement options for formatting and circuits

- samples/algorithms/SuperdenseCoding.qs
Changed Superdense coding example to work with adaptive profile
* Use quantum random bit generator instead of one provided in simulator
* Removed unnecessary check that wasn't compatible with the profile
* Changed return value so that correctness of the algorithm can be verified.
Now it generates QIR in adaptive profile.
CHECK: Not sure if this return type from Main is supported. Need to check.
> Superdense coding sample works in Adaptive Profile

- compiler/qsc_partial_eval/src/lib.rs
- compiler/qsc_partial_eval/tests/assigns.rs
- compiler/qsc_partial_eval/tests/operators.rs
This change implements partial evaluation support for exponentiation.
> Partial evaluation support for exponentiation

- katas/content/linear_algebra/adjoint/solution.md
- katas/content/linear_algebra/conjugate/solution.md
- katas/content/linear_algebra/index.md
- katas/content/linear_algebra/inverse/index.md
- katas/content/linear_algebra/inverse/solution.md
- katas/content/linear_algebra/multiplication/solution.md
- katas/content/linear_algebra/normalized_vector/solution.md
- katas/content/linear_algebra/scalar_multiplication/solution.md
- katas/content/linear_algebra/tensor_product/index.md
- katas/content/linear_algebra/transpose/solution.md
Review by the docs team. Checklist includes:
- Contractions
- Voice
- Clarity
- Indicate the level of knowledge in the prerequisites
> Katas UI string review - Linear Algebra

- katas/content/distinguishing_unitaries/rz_ry/index.md
- npm/qsharp/generate_katas_content.js
- npm/qsharp/src/katas.ts
- npm/qsharp/test/basics.js
- playground/src/kataViewer.tsx
- playground/src/main.tsx
Unpublished katas are listed after published ones in alphabetic order.
This closes #1419.
> Add unpublished katas to playground and tests

- katas/content/KatasLibrary.qs
- katas/content/marking_oracles/index.md
- katas/content/marking_oracles/kth_bit/Placeholder.qs
- katas/content/marking_oracles/kth_bit/Solution.qs
- katas/content/marking_oracles/kth_bit/Verification.qs
- katas/content/marking_oracles/kth_bit/index.md
- katas/content/marking_oracles/kth_bit/solution.md
- katas/content/marking_oracles/parity/Placeholder.qs
- katas/content/marking_oracles/parity/Solution.qs
- katas/content/marking_oracles/parity/Verification.qs
- katas/content/marking_oracles/parity/index.md
- katas/content/marking_oracles/parity/solution.md
- katas/content/marking_oracles/product/Placeholder.qs
- katas/content/marking_oracles/product/Solution.qs
- katas/content/marking_oracles/product/Verification.qs
- katas/content/marking_oracles/product/index.md
- katas/content/marking_oracles/product/solution.md
- katas/content/marking_oracles/product_negation/Placeholder.qs
- katas/content/marking_oracles/product_negation/Solution.qs
- katas/content/marking_oracles/product_negation/Verification.qs
- katas/content/marking_oracles/product_negation/index.md
- katas/content/marking_oracles/product_negation/solution.md
This includes the testing operation and the four introductory tasks 1.3-1.7 from old DeutschJozsaAlgorithm kata.
> Create template for MarkingOracles kata

- katas/content/teleportation/Common.qs
- katas/content/teleportation/index.md
- katas/content/teleportation/prepare_and_send_message/Placeholder.qs
- katas/content/teleportation/prepare_and_send_message/Solution.qs
- katas/content/teleportation/prepare_and_send_message/Verification.qs
- katas/content/teleportation/prepare_and_send_message/index.md
- katas/content/teleportation/prepare_and_send_message/solution.md
- katas/content/teleportation/reconstruct_and_measure_message/Placeholder.qs
- katas/content/teleportation/reconstruct_and_measure_message/Solution.qs
- katas/content/teleportation/reconstruct_and_measure_message/Verification.qs
- katas/content/teleportation/reconstruct_and_measure_message/index.md
- katas/content/teleportation/reconstruct_and_measure_message/solution.md
Added task 1.5 and 1.6 of Teleportation Kata
> Added task 1.5 and 1.6 of Teleportation Kata

- katas/content/teleportation/index.md
- katas/content/teleportation/reconstruct_message_phi_minus/Placeholder.qs
- katas/content/teleportation/reconstruct_message_phi_minus/Solution.qs
- katas/content/teleportation/reconstruct_message_phi_minus/Verification.qs
- katas/content/teleportation/reconstruct_message_phi_minus/index.md
- katas/content/teleportation/reconstruct_message_phi_minus/solution.md
- katas/content/teleportation/reconstruct_message_psi_minus/Placeholder.qs
- katas/content/teleportation/reconstruct_message_psi_minus/Solution.qs
- katas/content/teleportation/reconstruct_message_psi_minus/Verification.qs
- katas/content/teleportation/reconstruct_message_psi_minus/index.md
- katas/content/teleportation/reconstruct_message_psi_minus/solution.md
- katas/content/teleportation/reconstruct_message_psi_plus/Placeholder.qs
- katas/content/teleportation/reconstruct_message_psi_plus/Solution.qs
- katas/content/teleportation/reconstruct_message_psi_plus/Verification.qs
- katas/content/teleportation/reconstruct_message_psi_plus/index.md
- katas/content/teleportation/reconstruct_message_psi_plus/solution.md
Added teleportation tasks 2.1 to 2.3
> Added teleportation tasks 2.1 to 2.3

- katas/content/teleportation/Common.qs
- katas/content/teleportation/entangled_trio/Placeholder.qs
- katas/content/teleportation/entangled_trio/Solution.qs
- katas/content/teleportation/entangled_trio/Verification.qs
- katas/content/teleportation/entangled_trio/index.md
- katas/content/teleportation/entangled_trio/solution.md
- katas/content/teleportation/index.md
- katas/content/teleportation/measurement_free_teleportation/Placeholder.qs
- katas/content/teleportation/measurement_free_teleportation/Solution.qs
- katas/content/teleportation/measurement_free_teleportation/Verification.qs
- katas/content/teleportation/measurement_free_teleportation/index.md
- katas/content/teleportation/measurement_free_teleportation/solution.md
- katas/content/teleportation/reconstruct_message_charlie/Placeholder.qs
- katas/content/teleportation/reconstruct_message_charlie/Solution.qs
- katas/content/teleportation/reconstruct_message_charlie/Verification.qs
- katas/content/teleportation/reconstruct_message_charlie/index.md
- katas/content/teleportation/reconstruct_message_charlie/solution.md
Added teleportation section 3 and 4 of Quantum Kata
> Added teleportation section 3 and 4

- playground/src/editor.tsx
> Phantom "entry point not found" error in the Playground

- Cargo.lock
- Cargo.toml
- compiler/qsc_eval/src/backend.rs
Pulls in fixes from https://github.com/qir-alliance/qir-runner/pull/186
> Update to latest sparse simulator

- katas/content/distinguishing_states/four_bell_states/index.md
- katas/content/distinguishing_states/index.md
- katas/content/distinguishing_unitaries/index.md
- katas/content/key_distribution/random_array/Verification.qs
Also includes an improvement for flaky test in BB84 kata
> Fix minor formatting issues in Distinguishing States/Unitaries katas

- playground/src/editor.tsx
> Playground doesn't support implicit namespaces

- library/std/src/intrinsic.qs
This was supposed to be exported, but twas not...
> Export Stdlib AND

- library/std/src/diagnostics.qs
> Fix missing docs for diagnostic callables

- samples/estimation/df-chemistry/chemistry.py
Added summary table for multiple qubit parameters in chemistry.py
> Added summary section in chemistry.py

- playground/src/editor.tsx
> Remove profile selection for Katas

- resource_estimator/src/system.rs
- resource_estimator/src/system/optimization/tfactory_exhaustive.rs
This enables to interface with existing implementations for QEC codes and T factories in custom RE projects using the extensibility API.
> Add more items to RE system API

- katas/content/distinguishing_states/a_b/Verification.qs
- katas/content/multi_qubit_gates/controlled_rotation/Verification.qs
- katas/content/preparing_states/unequal_superposition/Verification.qs
- katas/content/single_qubit_measurements/a_b_basis_measurements/Verification.qs
Added DoubleAsStringWithPrecision function to following katas
1. Multi Qubit Gates
2. Preparing Quantum States
3. Measurement in Single-Qubit Systems
4. Distinguishing Quantum States
> Added DoubleAsStringWithPrecision function - Multiple Katas

- vscode/src/azure/providerProperties.ts
This change updates the Azure Quantum targets filter.
> Update filtering for targets

- compiler/qsc/src/lib.rs
- npm/qsharp/src/compiler/compiler.ts
- vscode/package.json
- vscode/src/config.ts
- vscode/src/webview/webview.tsx
- vscode/src/webviewPanel.ts
- wasm/src/lib.rs
- wasm/src/tests.rs
Added VS Code settings for the noise model to use when running histograms.
> Expose pauli noise settings in VS Code

- compiler/qsc_doc_gen/src/generate_docs.rs
- compiler/qsc_doc_gen/src/generate_docs/tests.rs
- vscode/src/documentation.ts
- vscode/src/webview/docview.tsx
- vscode/src/webview/tsconfig.json
- vscode/src/webview/webview.tsx
This adds structure, navigation, and search to the API Docs page.
> Improve the built-in API docs UX

- version.py
> Bump version to 1.10

- jupyterlab/pyproject.toml
- pip/Cargo.toml
- pip/pyproject.toml
This reverts commit 886b5935e5b8a47ec05a348805bcc28db37a1d27.
Reopen #1946
> Revert "Set min python version to 3.9 and add 3.12 to list"

- .github/workflows/devskim.yml
- .github/workflows/fuzz.yml
- .github/workflows/publish-playground.yml
Implemented the changes mentioned in #2010
> Update GitHub action versions

- .github/workflows/publish-playground.yml
> Fix publish-playground.yml

- katas/content/getting_started/index.md
Needed for accessibility on QCOM
> Add aria roles to kata headings

- jupyterlab/yarn.lock
- package-lock.json
This fixes #2033 . (Note that updating to the latest v1 of yarn changes the lock-file format a bit, hence all the lines.
> Audit fixes

- .github/CODEOWNERS
To reflect the ownership changes
> Update CODEOWNERS to remove myself

- compiler/qsc/src/interpret.rs
- compiler/qsc/src/interpret/circuit_tests.rs
- compiler/qsc_circuit/src/builder.rs
- compiler/qsc_circuit/src/builder/tests.rs
- compiler/qsc_circuit/src/circuit.rs
- npm/qsharp/ux/circuit.tsx
> put a limit on number of operations in circuit

- npm/qsharp/ux/qsharp-ux.css
- playground/src/docs.tsx
- playground/src/editor.tsx
- playground/src/main.tsx
- playground/src/results.tsx
- playground/src/tabs.tsx
This reverts commit 1255ac0b1e42fb7de70531d3bbf3c58c4e1d5eff.
Thee `html` element css update broke some things in VS Code. Reverting until I can figure it out and redo the change.
> Revert "Improve playground layout (#2098)"

- vscode/src/registry.json
> Update incorrect path in registry for fixedpoint library

- library/chemistry/src/JordanWigner/Convenience.qs
- library/chemistry/src/JordanWigner/ConvenienceVQE.qs
- library/chemistry/src/JordanWigner/JordanWignerBlockEncoding.qs
- library/chemistry/src/JordanWigner/JordanWignerEvolutionSet.qs
- library/chemistry/src/JordanWigner/JordanWignerOptimizedBlockEncoding.qs
- library/chemistry/src/JordanWigner/JordanWignerVQE.qs
- library/chemistry/src/JordanWigner/StatePreparation.qs
- library/chemistry/src/JordanWigner/Utils.qs
- library/chemistry/src/Tests.qs
Redundant code removed (Especially state preparation and LE comparison), some renames, some cleanup of old syntax.
Added test for superposition preparation.
> Some cleanup of chemistry library

- compiler/qsc_qasm3/src/lex/raw.rs
- compiler/qsc_qasm3/src/lex/raw/tests.rs
> Fix panic in qasm3 lexer found by the fuzzer

- katas/README.md
- katas/content/getting_started/index.md
> Rebranding Azure Katas to Microsoft Katas

- package-lock.json
- package.json
Resolves https://github.com/advisories/GHSA-593f-38f6-jp5m in `koa` (low impact, only used in vs code integration tests)
> update @vscode/test-web and koa

- vscode/src/registry.json
* This is Q# library implementing various integer arithmetic algorithms with quantum integers. It includes algorithms for addition, subtraction, comparison, multiplication, division, modular exponentiation, square root and greatest common divisor. 
* The library is located here: https://github.com/fedimser/quant-arith-re
* Adding it as requested in https://github.com/fedimser/quant-arith-re/issues/1
> Add reference to QuantumArithmetic library

- package-lock.json
- package.json
There've been quite a few fixes since we last updated, including one by @sezna that would improve the platform version field.
> Update @vscode/extension-telemetry to 0.9.8

- vscode/src/copilot/webview/copilot.css
- vscode/src/copilot/webview/copilot.tsx
Update the welcome blurb to be a bit more fancy.
> Update Copilot welcome

- compiler/qsc_qasm3/src/ast_builder.rs
- compiler/qsc_qasm3/src/compiler.rs
- compiler/qsc_qasm3/src/semantic/lowerer.rs
- compiler/qsc_qasm3/src/semantic/symbols.rs
- compiler/qsc_qasm3/src/tests/declaration/def.rs
- compiler/qsc_qasm3/src/tests/declaration/gate.rs
- compiler/qsc_qasm3/src/tests/expression/function_call.rs
- compiler/qsc_qasm3/src/tests/scopes.rs
- compiler/qsc_qasm3/src/tests/statement/annotation.rs
- compiler/qsc_qasm3/src/tests/statement/gate_call.rs
- compiler/qsc_qasm3/src/tests/statement/include.rs
- compiler/qsc_qasm3/src/tests/statement/switch.rs
Compile functions and operations const evaluating any references to symbol in an external scope.
> functions and operations with const eval

- compiler/qsc_qasm3/src/compiler.rs
- compiler/qsc_qasm3/src/parser/ast.rs
- compiler/qsc_qasm3/src/parser/expr.rs
- compiler/qsc_qasm3/src/semantic/ast/const_eval.rs
- compiler/qsc_qasm3/src/semantic/lowerer.rs
Remove TODO comments from code and add them as Postponed items to the tracking PR.
> Cleanup TODO items

- compiler/qsc_qasm/src/parser/error.rs
- compiler/qsc_qasm/src/semantic/const_eval.rs
- compiler/qsc_qasm/src/tests/declaration/def.rs
- compiler/qsc_qasm/src/tests/declaration/gate.rs
- compiler/qsc_qasm/src/tests/statement/const_eval.rs
Rename error diagnostic codes.
> Rename error diagnostic codes

- Cargo.lock
- compiler/qsc/Cargo.toml
- compiler/qsc_qasm/Cargo.toml
- compiler/qsc_qasm/src/io.rs
Remove source resolver default impl.
> Remove source resolver default impl

- samples/language/Tuple.qs
- samples_test/src/tests/language.rs
We didn't have much sample code unpacking tuples. Added now.
Addresses https://github.com/microsoft/qsharp/issues/2353
> Added tuple unpacking samples

- package-lock.json
- package.json
- vscode/src/webview/editor.tsx
Fix CodeQL warning about unsanitized DOM strings
> Sanitize messages

- samples/OpenQASM/BellPair.qasm
- samples/OpenQASM/OpenQasmHelloWorld.qasm
- samples/OpenQASM/RandomNumber.qasm
Added three OpenQASM samples.
* OpenQasmHelloWorld.qasm
* BellPair.qasm
* RandomNumber.qasm
For now, the samples are only added as files. No tests are added, and they are not available as quick templates.
> Added three OpenQASM samples

- samples/OpenQASM/Grover.qasm
Sample is more specific to one 5-qubit state than our Q# sample. I don't want to move multi-control gate implementation into this. At least not until we fully support includes.
> OpenQASM Grover's algorithm sample

- compiler/qsc_qasm/src/ast_builder.rs
> Fix end stmt spans for stop on failure

- compiler/qsc_linter/src/lints/hir.rs
- compiler/qsc_linter/src/tests.rs
> Needless operation lint should ignore lambdas

- samples/OpenQASM/Simple1dIsingOrder1.qasm
- samples/OpenQASM/samples.mjs
- samples_test/src/tests/OpenQASM.rs
> Added OpenQASM Ising sample

- npm/qsharp/ux/circuit-vis/contextMenu.ts
- pip/tests/circuit.qsc
- pip/tests/test_project.py
Also fixes a small capitalization inconsistency in the context menu for circuit editor.
> Adds a python integration test for circuits

- compiler/qsc_qasm/src/semantic/const_eval.rs
- compiler/qsc_qasm/src/semantic/resources/openqasm_lowerer_errors_test.qasm
- compiler/qsc_qasm/src/semantic/tests.rs
- compiler/qsc_qasm/src/semantic/tests/lowerer_errors.rs
- compiler/qsc_qasm/src/tests/statement/const_eval.rs
Fix shl overflow panic and add `lowerer_errors` test file.
> fix shl overflow panic and add lowerer_errors test

- compiler/qsc_doc_gen/src/generate_docs/tests.rs
- compiler/qsc_doc_gen/src/table_of_contents.rs
Remove Unstable references in the top level index and replace with Std references.
> Update the Top Level Index File

- samples/algorithms/SimplePhaseEstimation.qs
- samples_test/src/tests/algorithms.rs
This adds a sample for Simple Quantum Phase Estimation using ApplyQPE.
Sample is suitable for base profile.
> Simple Quantum Phase estimation sample via ApplyQPE (Base profile)

- npm/qsharp/ux/circuit-vis/index.ts
- npm/qsharp/ux/circuit-vis/panel.ts
- npm/qsharp/ux/circuit-vis/sqore.ts
- npm/qsharp/ux/circuit.tsx
- npm/qsharp/ux/data.ts
- npm/qsharp/ux/qsharp-circuit.css
- vscode/src/circuitEditor.ts
- vscode/src/debugger/activate.ts
- vscode/src/webview/editor.tsx
Adds a run button in the circuit editor's toolbox panel that allows users to run just the circuit in the editor. Qubits will be initialized in the zero state and a DumpMachine call will output the state after running the circuit.
> Circuit Editor Run Button

- .github/workflows/fuzz.yml
- .github/workflows/publish-playground.yml
Updates the paths in the .github/workflows files to respect the new repo structure.
> Update workflow paths

- library/std/src/Std/OpenQASM/Angle.qs
- source/compiler/qsc_qasm/src/stdlib/angle.rs
- source/compiler/qsc_qasm/src/stdlib/angle/tests.rs
> Angle from floats handle rounding when operating on values less than epsilon

- source/vscode/package.json
> Restore copilot instructions command

- source/npm/qsharp/src/workers/common.ts
- source/vscode/src/qirGeneration.ts
> Nicer error messages for QIR generation
